Nek5000: bdry.F90 File Reference
bdry.F90 File Reference
Functions/Subroutines
subroutine setlog ()
Subroutine to initialize logical flags.
subroutine chknord (IFALGN, IFNORX, IFNORY, IFNORZ, IFC, IEL)
Check direction of normal of an element face for alignment with the X, Y, or Z axis.
subroutine chkaxcb ()
subroutine chkcbc (CB, IEL, IFC, IFALGN)
Check for illegal boundary conditions.
subroutine bcmask
Zero out masks corresponding to Dirichlet boundary points.
subroutine bcdirvc (V1, V2, V3, mask1, mask2, mask3)
Apply Dirichlet boundary conditions to surface of vector (V1,V2,V3). Use IFIELD as a guide to which boundary conditions are to be applied.
subroutine bcdirsc (S)
Apply Dirichlet boundary conditions to surface of scalar, S. Use IFIELD as a guide to which boundary conditions are to be applied.
subroutine bcneusc (S, ITYPE)
Apply Neumann boundary conditions to surface of scalar, S. Use IFIELD as a guide to which boundary conditions are to be applied. If ITYPE = 1, then S is returned as the rhs contribution to the volumetric flux. If ITYPE =-1, then S is returned as the lhs contribution to the diagonal of A.
subroutine nekasgn (IX, IY, IZ, IEL)
Assign NEKTON variables for definition (by user) of boundary conditions at collocation point (IX,IY,IZ) of element IEL. X X-coordinate Y Y-coordinate Z Z-coordinate UX X-velocity UY Y-velocity UZ Z-velocity TEMP Temperature PS1 Passive scalar No. 1 PS2 Passive scalar No. 2 . . . . PS9 Passive scalar No. 9 SI2 Strainrate invariant II SI3 Strainrate invariant III Variables to be defined by user for imposition of boundary conditions : SH1 Shear component No. 1 SH2 Shear component No. 2 TRX X-traction TRY Y-traction TRZ Z-traction SIGMA Surface-tension coefficient FLUX Flux HC Convection heat transfer coefficient HRAD Radiation heat transfer coefficient TINF Temperature at infinity.
subroutine lfalse (IFA, N)
subroutine unitvec (X, Y, Z, N)
Function/Subroutine Documentation
subroutine bcdirsc (real(dp), dimension(lx1,ly1,lz1,lelt) S)
Apply Dirichlet boundary conditions to surface of scalar, S. Use IFIELD as a guide to which boundary conditions are to be applied.
Definition at line 748 of file bdry.F90.
References ctimer::dnekclock(), dsop(), and facev().
Referenced by cdscal().
subroutine bcdirvc (real(dp), dimension(nx1,ny1,nz1,lelv) V1, real(dp), dimension(nx1,ny1,nz1,lelv) V2, real(dp), dimension(nx1,ny1,nz1,lelv) V3, real(dp), dimension(nx1,ny1,nz1,lelv) mask1, real(dp), dimension(nx1,ny1,nz1,lelv) mask2, real(dp), dimension(nx1,ny1,nz1,lelv) mask3)
Apply Dirichlet boundary conditions to surface of vector (V1,V2,V3). Use IFIELD as a guide to which boundary conditions are to be applied.
Attention
Most of the utility of this routine has been removed to avoid temporary allocations. This modification is not valid for the boundaries
v
vl
ws
wsl
mv
mvn
d
on
Definition at line 588 of file bdry.F90.
References copy(), ctimer::dnekclock(), facev(), and opdsop().
Referenced by plan4(), and setdtc().
subroutine bcmask ()
Zero out masks corresponding to Dirichlet boundary points.
Definition at line 304 of file bdry.F90.
References chknord(), dsop(), facev(), and opdsop().
Referenced by nek_init().
subroutine bcneusc (real(dp), dimension(lx1,ly1,lz1,lelt), intent(out) S, integer ITYPE)
Apply Neumann boundary conditions to surface of scalar, S. Use IFIELD as a guide to which boundary conditions are to be applied. If ITYPE = 1, then S is returned as the rhs contribution to the volumetric flux. If ITYPE =-1, then S is returned as the lhs contribution to the diagonal of A.
Definition at line 840 of file bdry.F90.
References ctimer::dnekclock(), facind(), parallel::lglel(), and nekasgn().
Referenced by cdscal(), and wlaplacian().
subroutine chkaxcb ()
Definition at line 247 of file bdry.F90.
References exitt().
Referenced by setup_topo().
subroutine chkcbc (character(3) CB, integer IEL, integer IFC, logical IFALGN)
Check for illegal boundary conditions.
Definition at line 274 of file bdry.F90.
References exitt().
Referenced by setlog().
subroutine chknord (logical IFALGN, logical IFNORX, logical IFNORY, logical IFNORZ, integer IFC, integer IEL)
Check direction of normal of an element face for alignment with the X, Y, or Z axis.
Definition at line 176 of file bdry.F90.
Referenced by bcmask(), and setlog().
subroutine lfalse (logical, dimension(*) IFA, integer N)
Definition at line 1051 of file bdry.F90.
Referenced by rdout(), and setlog().
subroutine nekasgn (integer, intent(in) IX, integer, intent(in) IY, integer, intent(in) IZ, integer, intent(in) IEL)
Assign NEKTON variables for definition (by user) of boundary conditions at collocation point (IX,IY,IZ) of element IEL. X X-coordinate Y Y-coordinate Z Z-coordinate UX X-velocity UY Y-velocity UZ Z-velocity TEMP Temperature PS1 Passive scalar No. 1 PS2 Passive scalar No. 2 . . . . PS9 Passive scalar No. 9 SI2 Strainrate invariant II SI3 Strainrate invariant III Variables to be defined by user for imposition of boundary conditions : SH1 Shear component No. 1 SH2 Shear component No. 2 TRX X-traction TRY Y-traction TRZ Z-traction SIGMA Surface-tension coefficient FLUX Flux HC Convection heat transfer coefficient HRAD Radiation heat transfer coefficient TINF Temperature at infinity.
Definition at line 1014 of file bdry.F90.
References y, and z.
Referenced by bcneusc(), nekuf(), nekuic(), and nekuq().
subroutine setlog ()
Subroutine to initialize logical flags.
Definition at line 3 of file bdry.F90.
References chkcbc(), chknord(), exitt(), gllog(), and lfalse().
Referenced by nek_init().
subroutine unitvec (real(dp), dimension(n), intent(inout) X, real(dp), dimension(n), intent(inout) Y, real(dp), dimension(n), intent(inout) Z, integer, intent(in) N)
Definition at line 1061 of file bdry.F90.
Referenced by area3().