Nek5000: byte.c File Reference
byte.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <float.h>
#include <math.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/types.h>
Macros
#define FNAME_H
#define FORTRAN_NAME(low, up) low
#define byte_reverse FORTRAN_NAME(byte_reverse, BYTE_REVERSE)
#define byte_reverse8 FORTRAN_NAME(byte_reverse8, BYTE_REVERSE8)
#define byte_open FORTRAN_NAME(byte_open, BYTE_OPEN)
#define byte_close FORTRAN_NAME(byte_close, BYTE_CLOSE)
#define byte_rewind FORTRAN_NAME(byte_rewind, BYTE_REWIND)
#define byte_read FORTRAN_NAME(byte_read, BYTE_READ)
#define byte_write FORTRAN_NAME(byte_write, BYTE_WRITE)
#define set_bytesw_write FORTRAN_NAME(set_bytesw_write,SET_BYTESW_WRITE)
#define set_bytesw_read FORTRAN_NAME(set_bytesw_read ,SET_BYTESW_READ)
#define get_bytesw_write FORTRAN_NAME(get_bytesw_write,GET_BYTESW_WRITE)
#define get_bytesw_read FORTRAN_NAME(get_bytesw_read ,GET_BYTESW_READ)
#define READ 1
#define WRITE 2
#define MAX_NAME 132
#define SWAP(a, b) temp=(a); (a)=(b); (b)=temp;
Functions
void exitt ()
void byte_reverse (float *buf, int *nn, int *ierr)
void byte_reverse8 (float *buf, int *nn, int *ierr)
void byte_open (char *n, int *ierr)
void byte_close (int *ierr)
void byte_rewind ()
void byte_write (float *buf, int *n, int *ierr)
void byte_read (float *buf, int *n, int *ierr)
void set_bytesw_write (int *pa)
void set_bytesw_read (int *pa)
void get_bytesw_write (int *pa)
void get_bytesw_read (int *pa)
Variables
static FILE * fp =NULL
static int flag =0
static char name [MAX_NAME+1]
int bytesw_write =0
int bytesw_read =0
Macro Definition Documentation
#define byte_close FORTRAN_NAME(byte_close, BYTE_CLOSE)
Definition at line 36 of file byte.c.
Referenced by io::load_ic(), mfo_outfld(), and restart_driver().
#define byte_open FORTRAN_NAME(byte_open, BYTE_OPEN)
Definition at line 35 of file byte.c.
Referenced by mbyte_open(), outfld(), and restart_driver().
#define byte_read FORTRAN_NAME(byte_read, BYTE_READ)
Definition at line 38 of file byte.c.
Referenced by io::load_ic(), io::mfo_read_header(), io::mfo_read_scalar(), io::mfo_read_vector(), and restart_driver().
#define byte_reverse FORTRAN_NAME(byte_reverse, BYTE_REVERSE)
Definition at line 33 of file byte.c.
Referenced by byte_read(), byte_write(), if_byte_swap_test(), and mapdmp().
#define byte_reverse8 FORTRAN_NAME(byte_reverse8, BYTE_REVERSE8)
Definition at line 34 of file byte.c.
#define byte_rewind FORTRAN_NAME(byte_rewind, BYTE_REWIND)
Definition at line 37 of file byte.c.
#define byte_write FORTRAN_NAME(byte_write, BYTE_WRITE)
Definition at line 39 of file byte.c.
Referenced by mfo_mdatas(), mfo_mdatav(), mfo_outs(), mfo_outv(), and mfo_write_hdr().
#define FNAME_H
Definition at line 12 of file byte.c.
#define FORTRAN_NAME (low, up) low
Definition at line 27 of file byte.c.
#define get_bytesw_read FORTRAN_NAME(get_bytesw_read ,GET_BYTESW_READ)
Definition at line 43 of file byte.c.
#define get_bytesw_write FORTRAN_NAME(get_bytesw_write,GET_BYTESW_WRITE)
Definition at line 42 of file byte.c.
Referenced by mfo_write_hdr().
#define MAX_NAME 132
Definition at line 47 of file byte.c.
Referenced by byte_open().
#define READ 1
Definition at line 45 of file byte.c.
Referenced by byte_read().
#define set_bytesw_read FORTRAN_NAME(set_bytesw_read ,SET_BYTESW_READ)
Definition at line 41 of file byte.c.
#define set_bytesw_write FORTRAN_NAME(set_bytesw_write,SET_BYTESW_WRITE)
Definition at line 40 of file byte.c.
Referenced by echopar(), and mfo_write_hdr().
#define SWAP (a, b) temp=(a); (a)=(b); (b)=temp;
Definition at line 49 of file byte.c.
Referenced by byte_reverse(), and byte_reverse8().
#define WRITE 2
Definition at line 46 of file byte.c.
Referenced by byte_write().
Function Documentation
void byte_close (int * ierr)
Definition at line 152 of file byte.c.
References fp.
void byte_open (char * n, int * ierr)
Definition at line 115 of file byte.c.
References i, MAX_NAME, and name.
void byte_read (float * buf, int * n, int * ierr)
Definition at line 214 of file byte.c.
References byte_reverse, bytesw_read, flag, fp, name, and READ.
void byte_reverse (float * buf, int * nn, int * ierr)
Definition at line 66 of file byte.c.
References n, and SWAP.
void byte_reverse8 (float * buf, int * nn, int * ierr)
Definition at line 86 of file byte.c.
References n, and SWAP.
void byte_rewind ()
Definition at line 167 of file byte.c.
References fp.
void byte_write (float * buf, int * n, int * ierr)
Definition at line 175 of file byte.c.
References byte_reverse, bytesw_write, flag, fp, name, and WRITE.
void exitt ()
Definition at line 411 of file comm_mpi.F90.
References ctimer::dnekclock(), flush_io(), happy_check(), mpi_finalize(), nek_flops(), nekgsync(), np, and print_stack.
Referenced by build_new_filter(), byte_set_view(), chk_nel(), chkaxcb(), chkcbc(), crecv(), speclib::dgj(), speclib::dgjd(), speclib::dglj(), speclib::dgljd(), speclib::dgljgj(), speclib::dgljgjd(), echopar(), err_chk(), exitti(), gaujordf(), gbtuple_rank(), generalev(), get_vert_map(), glmapm1(), gop(), hsmg_routines::h1mg_setup_fdm(), hsmg_routines::h1mg_setup_schwarz_wt(), hsmg_routines::h1mg_setup_wtmask(), speclib::hgj(), speclib::hglj(), hsmg_routines::hsmg_setup_fdm(), hsmg_routines::hsmg_setup_schwarz_wt(), hsmg_routines::hsmg_setup_solve(), hsmg_routines::hsmg_setup_wtmask(), i8gop(), i_find_prefix(), igop(), iniproc(), io_init(), iswapt_ip(), mapelpr(), mfo_outs(), mfo_outv(), io::mfo_read_scalar(), io::mfo_read_vector(), nek_comm_io(), nekton(), outpost2(), rdbdry(), rdcurve(), rdhist(), rdmatp(), rdmesh(), rdout(), rdparam(), readat(), restart_driver(), setics(), setlog(), setvar(), solve(), specmpn(), tensr3(), verrhe(), vprops(), vrdsmsh(), speclib::zwgj(), speclib::zwgjd(), speclib::zwglj(), and speclib::zwgljd().
void get_bytesw_read (int * pa)
Definition at line 283 of file byte.c.
References bytesw_read.
void get_bytesw_write (int * pa)
Definition at line 278 of file byte.c.
References bytesw_write.
void set_bytesw_read (int * pa)
Definition at line 270 of file byte.c.
References bytesw_read.
void set_bytesw_write (int * pa)
Definition at line 262 of file byte.c.
References bytesw_write.
Variable Documentation
int bytesw_read =0
Definition at line 56 of file byte.c.
Referenced by byte_read(), get_bytesw_read(), and set_bytesw_read().
int bytesw_write =0
Definition at line 55 of file byte.c.
Referenced by byte_write(), get_bytesw_write(), and set_bytesw_write().
int flag =0 static
Definition at line 52 of file byte.c.
Referenced by byte_read(), byte_write(), and nonzero_ids().
FILE* fp =NULL static
Definition at line 51 of file byte.c.
Referenced by byte_close(), byte_read(), byte_rewind(), and byte_write().
char name[MAX_NAME+1] static
Definition at line 53 of file byte.c.
Referenced by auto_setup(), byte_open(), byte_read(), and byte_write().