Nek5000: byte_mpi.F90 File Reference
byte_mpi.F90 File Reference
Functions/Subroutines
subroutine byte_sync_mpi (mpi_fh)
subroutine byte_open_mpi (fname, mpi_fh, ierr)
subroutine byte_read_mpi (buf, icount, iorank, mpi_fh, ierr)
subroutine byte_write_mpi (buf, icount, iorank, mpi_fh, ierr)
subroutine byte_close_mpi (mpi_fh, ierr)
subroutine byte_set_view (ioff_in, mpi_fh)
subroutine nek_comm_io (nn)
Function/Subroutine Documentation
subroutine byte_close_mpi (integer mpi_fh, integer ierr)
Definition at line 117 of file byte_mpi.F90.
Referenced by mfo_outfld().
subroutine byte_open_mpi (character(132) fname, integer mpi_fh, integer ierr)
Definition at line 13 of file byte_mpi.F90.
Referenced by mbyte_open().
subroutine byte_read_mpi (real(r4), dimension(1) buf, integer icount, integer iorank, integer mpi_fh, integer ierr)
Definition at line 43 of file byte_mpi.F90.
subroutine byte_set_view (integer(i8) ioff_in, integer mpi_fh)
Definition at line 142 of file byte_mpi.F90.
References exitt().
Referenced by mfo_outfld(), and mfo_write_hdr().
subroutine byte_sync_mpi (integer, intent(in) mpi_fh)
Definition at line 1 of file byte_mpi.F90.
subroutine byte_write_mpi (real(r4), dimension(1) buf, integer icount, integer iorank, integer mpi_fh, integer ierr)
Definition at line 81 of file byte_mpi.F90.
Referenced by mfo_mdatas(), mfo_mdatav(), and mfo_write_hdr().
subroutine nek_comm_io (integer nn)
Definition at line 171 of file byte_mpi.F90.
References bcast(), crecv(), csend(), exitt(), mpi_comm_create(), mpi_comm_group(), mpi_group_free(), and np.
Referenced by io_init().