Nek5000: mesh Module Reference
mesh Module Reference
cleaned
Public Member Functions
subroutine init_mesh ()
integer function, dimension(3) ieg_to_xyz (ieg)
integer function xyz_to_ieg (xyz)
Public Attributes
integer, dimension(:), allocatable vertex
logical, dimension(:), allocatable ifdfrm
is the element deformed?
logical, dimension(:), allocatable iffast
can we use a fast method on the element?
logical ifsolv
are ifdfrm and iffast up to date?
integer niterhm
logical if_ortho = .true.
real(dp), dimension(3) start_x
real(dp), dimension(3) end_x
integer, dimension(3) shape_x
character(3), dimension(6) boundaries
character(3), dimension(6) tboundaries
Detailed Description
cleaned
Definition at line 2 of file mesh_mod.F90.
Member Function/Subroutine Documentation
integer function, dimension(3) mesh::ieg_to_xyz (integer, intent(in) ieg)
Definition at line 32 of file mesh_mod.F90.
Referenced by poisson::cos_test(), get_vert_map(), parallel::gllel(), parallel::gllnid(), poisson::init_mesh_to_grid(), and parallel::my_ieg().
subroutine mesh::init_mesh ()
Definition at line 22 of file mesh_mod.F90.
Referenced by nek_init().
integer function mesh::xyz_to_ieg (integer, dimension(3), intent(in) xyz)
Definition at line 42 of file mesh_mod.F90.
Referenced by parallel::lglel().
Member Data Documentation
character(3), dimension(6) mesh::boundaries
Definition at line 17 of file mesh_mod.F90.
real(dp), dimension(3) mesh::end_x
Definition at line 14 of file mesh_mod.F90.
logical mesh::if_ortho = .true.
Definition at line 11 of file mesh_mod.F90.
logical, dimension(:), allocatable mesh::ifdfrm
is the element deformed?
Definition at line 7 of file mesh_mod.F90.
logical, dimension(:), allocatable mesh::iffast
can we use a fast method on the element?
Definition at line 8 of file mesh_mod.F90.
logical mesh::ifsolv
are ifdfrm and iffast up to date?
Definition at line 9 of file mesh_mod.F90.
integer mesh::niterhm
Definition at line 10 of file mesh_mod.F90.
integer, dimension(3) mesh::shape_x
Definition at line 15 of file mesh_mod.F90.
real(dp), dimension(3) mesh::start_x
Definition at line 13 of file mesh_mod.F90.
character(3), dimension(6) mesh::tboundaries
Definition at line 17 of file mesh_mod.F90.
integer, dimension(:), allocatable mesh::vertex
Definition at line 6 of file mesh_mod.F90.
The documentation for this module was generated from the following file:
mesh_mod.F90