Nek5000: interp Module Reference
interp Module Reference
Module containing memoized interpolation matrices.
Public Member Functions
subroutine get_int_ptr (ip, mx, md)
Get pointer to jgl() for interpolation pair (mx,md)
subroutine get_dgl_ptr (ip, mx, md)
Get pointer to GL-GL interpolation dgl() for pair (mx,md)
Public Attributes
integer, parameter ldg =lxd**3
integer, parameter lwkd =4*lxd*lxd
integer, parameter ld =2*lxd
integer, parameter ldw = 2*(ld**ldim)
real(dp), dimension(ldg), save jgl
real(dp), dimension(ldg), save jgt
real(dp), dimension(ldg), save dgl
real(dp), dimension(ldg), save dgt
real(dp), dimension(ld **ldim, 2) w
real(dp), dimension(lwkd) wkd
Private Attributes
integer, dimension(0:ld *ld), save, private pjgl = 0
integer, dimension(0:ld *ld), save, private pdg = 0
Detailed Description
Module containing memoized interpolation matrices.
Definition at line 5 of file interp_mod.F90.
Member Function/Subroutine Documentation
subroutine interp::get_dgl_ptr (integer, intent(out) ip, integer, intent(in) mx, integer, intent(in) md)
Get pointer to GL-GL interpolation dgl() for pair (mx,md)
Definition at line 65 of file interp_mod.F90.
References gen_dgl(), and lim_chk().
Referenced by convect_new().
subroutine interp::get_int_ptr (integer, intent(out) ip, integer, intent(in) mx, integer, intent(in) md)
Get pointer to jgl() for interpolation pair (mx,md)
The interpolation matrices jgl, jgt are being memoized. pjgl is a map from (mx,md) pair to (ip) index of jgl, jgt
Definition at line 32 of file interp_mod.F90.
References gen_int(), and lim_chk().
Referenced by convect_new(), set_convect_new(), and set_dealias_rx().
Member Data Documentation
real(dp), dimension(ldg), save interp::dgl
Definition at line 18 of file interp_mod.F90.
real(dp), dimension(ldg), save interp::dgt
Definition at line 18 of file interp_mod.F90.
real(dp), dimension(ldg), save interp::jgl
Definition at line 17 of file interp_mod.F90.
real(dp), dimension(ldg), save interp::jgt
Definition at line 17 of file interp_mod.F90.
integer, parameter interp::ld =2*lxd
Definition at line 14 of file interp_mod.F90.
integer, parameter interp::ldg =lxd**3
Definition at line 13 of file interp_mod.F90.
integer, parameter interp::ldw = 2*(ld**ldim)
Definition at line 15 of file interp_mod.F90.
integer, parameter interp::lwkd =4*lxd*lxd
Definition at line 13 of file interp_mod.F90.
integer, dimension(0:ld*ld), save, private interp::pdg = 0 private
Definition at line 20 of file interp_mod.F90.
integer, dimension(0:ld*ld), save, private interp::pjgl = 0 private
Definition at line 19 of file interp_mod.F90.
real(dp), dimension(ld**ldim,2) interp::w
Definition at line 22 of file interp_mod.F90.
real(dp), dimension(lwkd) interp::wkd
Definition at line 23 of file interp_mod.F90.
The documentation for this module was generated from the following file:
interp_mod.F90