Nek5000: speclib Module Reference
speclib Module Reference
Public Member Functions
subroutine, public zwgl (Z, W, NP)
Generate NP Gauss Legendre points (Z) and weights (W) associated with Jacobi polynomial P(N)(alpha=0,beta=0). The polynomial degree N=NP-1. Z and W are in single precision, but all the arithmetic operations are done in double precision.
subroutine, public zwgll (Z, W, NP)
subroutine, public zwglj (Z, W, NP, ALPHA, BETA)
subroutine, public dgll (D, DT, Z, NZ, NZD)
subroutine, public dgllgl (D, DT, ZM1, ZM2, IM12, NZM1, NZM2, ND1, ND2)
subroutine, public igllm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
Public Attributes
integer, parameter nmax = 84
Private Member Functions
subroutine zwgj (Z, W, NP, ALPHA, BETA)
subroutine zwgjd (Z, W, NP, ALPHA, BETA)
subroutine zwgljd (Z, W, NP, ALPHA, BETA)
real(dp) function endw1 (N, ALPHA, BETA)
real(dp) function endw2 (N, ALPHA, BETA)
real(dp) function gammaf (X)
real(dp) function pnormj (N, ALPHA, BETA)
subroutine jacg (XJAC, NP, ALPHA, BETA)
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
real(dp) function hgj (II, Z, ZGJ, NP, ALPHA, BETA)
real(dp) function hgjd (II, Z, ZGJ, NP, ALPHA, BETA)
real(dp) function hglj (II, Z, ZGLJ, NP, ALPHA, BETA)
real(dp) function hgljd (I, Z, ZGLJ, NP, ALPHA, BETA)
subroutine dgj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgjd (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dglj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgljd (D, DT, Z, NZ, NZD, ALPHA, BETA)
real(dp) function hgll (I, Z, ZGLL, NZ)
real(dp) function hgl (I, Z, ZGL, NZ)
real(dp) function pnleg (Z, N)
real(dp) function pndleg (Z, N)
subroutine dgljgj (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine dgljgjd (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine iglm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine igjm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
subroutine igljm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Detailed Description
Definition at line 67 of file speclib.F90.
Member Function/Subroutine Documentation
subroutine speclib::dgj (real(dp), dimension(nzd,nzd), intent(out) D, real(dp), dimension(nzd,nzd), intent(out) DT, real(dp), dimension(nz), intent(in) Z, integer NZ, integer NZD, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 684 of file speclib.F90.
References dgjd(), and exitt().
subroutine speclib::dgjd (real(dp), dimension(nzd,nzd), intent(out) D, real(dp), dimension(nzd,nzd), intent(out) DT, real(dp), dimension(nz), intent(in) Z, integer, intent(in) NZ, integer, intent(in) NZD, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 729 of file speclib.F90.
References exitt(), and jacobf().
Referenced by dgj().
subroutine speclib::dglj (real(dp), dimension(nzd,nzd), intent(out) D, real(dp), dimension(nzd,nzd), intent(out) DT, real(dp), dimension(nz), intent(in) Z, integer, intent(in) NZ, integer, intent(in) NZD, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 772 of file speclib.F90.
References dgljd(), and exitt().
Referenced by genwz().
subroutine speclib::dgljd (real(dp), dimension(nzd,nzd), intent(out) D, real(dp), dimension(nzd,nzd), intent(out) DT, real(dp), dimension(nz), intent(in) Z, integer, intent(in) NZ, integer, intent(in) NZD, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 817 of file speclib.F90.
References exitt(), and jacobf().
Referenced by dglj().
subroutine speclib::dgljgj (real(dp), dimension(nd2,nd1), intent(out) D, real(dp), dimension(nd1,nd2), intent(out) DT, real(dp), dimension(nd1), intent(in) ZGL, real(dp), dimension(nd2), intent(in) ZG, real(dp), dimension(nd2,nd1), intent(in) IGLG, integer, intent(in) NPGL, integer, intent(in) NPG, integer, intent(in) ND1, integer, intent(in) ND2, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 1055 of file speclib.F90.
References dgljgjd(), and exitt().
Referenced by genwz().
subroutine speclib::dgljgjd (real(dp), dimension(nd2,nd1), intent(out) D, real(dp), dimension(nd1,nd2), intent(out) DT, real(dp), dimension(nd1), intent(in) ZGL, real(dp), dimension(nd2), intent(in) ZG, real(dp), dimension(nd2,nd1), intent(in) IGLG, integer, intent(in) NPGL, integer, intent(in) NPG, integer, intent(in) ND1, integer, intent(in) ND2, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 1112 of file speclib.F90.
References exitt(), and jacobf().
Referenced by dgljgj().
subroutine, public speclib::dgll (real(dp), dimension(nzd,nzd), intent(out) D, real(dp), dimension(nzd,nzd), intent(out) DT, real(dp), dimension(nz), intent(in) Z, integer, intent(in) NZ, integer, intent(in) NZD)
Definition at line 867 of file speclib.F90.
References pnleg().
Referenced by genwz().
subroutine, public speclib::dgllgl (real(dp), dimension(nd2,nd1), intent(out) D, real(dp), dimension(nd1,nd2), intent(out) DT, real(dp), dimension(nd1), intent(in) ZM1, real(dp), dimension(nd2), intent(in) ZM2, real(dp), dimension(nd2,nd1), intent(in) IM12, integer, intent(in) NZM1, integer, intent(in) NZM2, integer, intent(in) ND1, integer, intent(in) ND2)
Definition at line 1015 of file speclib.F90.
References pnleg().
Referenced by genwz().
real(dp) function speclib::endw1 (integer, intent(in) N, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 286 of file speclib.F90.
References gammaf().
Referenced by zwgljd().
real(dp) function speclib::endw2 (integer, intent(in) N, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 336 of file speclib.F90.
References gammaf().
Referenced by zwgljd().
real(dp) function speclib::gammaf (real(dp), intent(in) X) private
Definition at line 387 of file speclib.F90.
Referenced by endw1(), endw2(), pnormj(), and zwgjd().
real(dp) function speclib::hgj (integer, intent(in) II, real(dp), intent(in) Z, real(dp), dimension(np), intent(in) ZGJ, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 562 of file speclib.F90.
References exitt(), and hgjd().
Referenced by igjm().
real(dp) function speclib::hgjd (integer, intent(in) II, real(dp), intent(in) Z, real(dp), dimension(np), intent(in) ZGJ, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 593 of file speclib.F90.
References jacobf().
Referenced by hgj().
real(dp) function speclib::hgl (integer, intent(in) I, real(dp), intent(in) Z, real(dp), dimension(nz), intent(in) ZGL, integer, intent(in) NZ) private
Definition at line 930 of file speclib.F90.
References pndleg(), and pnleg().
Referenced by iglm().
real(dp) function speclib::hglj (integer, intent(in) II, real(dp), intent(in) Z, real(dp), dimension(np), intent(in) ZGLJ, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 620 of file speclib.F90.
References exitt(), and hgljd().
Referenced by igljm().
real(dp) function speclib::hgljd (integer, intent(in) I, real(dp), intent(in) Z, real(dp), dimension(np), intent(in) ZGLJ, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 652 of file speclib.F90.
References jacobf().
Referenced by hglj().
real(dp) function speclib::hgll (integer, intent(in) I, real(dp), intent(in) Z, real(dp), dimension(nz), intent(in) ZGLL, integer, intent(in) NZ) private
Definition at line 905 of file speclib.F90.
References pndleg(), and pnleg().
Referenced by igllm().
subroutine speclib::igjm (real(dp), dimension(nd2,nd1), intent(out) I12, real(dp), dimension(nd1,nd2), intent(out) IT12, real(dp), dimension(nd1), intent(in) Z1, real(dp), dimension(nd2), intent(in) Z2, integer, intent(in) NZ1, integer, intent(in) NZ2, integer, intent(in) ND1, integer, intent(in) ND2, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 1227 of file speclib.F90.
References hgj().
Referenced by genwz().
subroutine speclib::igljm (real(dp), dimension(nd2,nd1), intent(out) I12, real(dp), dimension(nd1,nd2), intent(out) IT12, real(dp), dimension(nd1), intent(in) Z1, real(dp), dimension(nd2), intent(in) Z2, integer, intent(in) NZ1, integer, intent(in) NZ2, integer, intent(in) ND1, integer, intent(in) ND2, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 1257 of file speclib.F90.
References hglj().
Referenced by genwz().
subroutine, public speclib::igllm (real(dp), dimension(nd2,nd1), intent(out) I12, real(dp), dimension(nd1,nd2), intent(out) IT12, real(dp), dimension(nd1), intent(in) Z1, real(dp), dimension(nd2), intent(in) Z2, integer, intent(in) NZ1, integer, intent(in) NZ2, integer, intent(in) ND1, integer, intent(in) ND2)
Definition at line 1197 of file speclib.F90.
References hgll().
Referenced by genwz(), mapab4r(), and q_filter().
subroutine speclib::iglm (real(dp), dimension(nd2,nd1), intent(out) I12, real(dp), dimension(nd1,nd2), intent(out) IT12, real(dp), dimension(nd1), intent(in) Z1, real(dp), dimension(nd2), intent(in) Z2, integer, intent(in) NZ1, integer, intent(in) NZ2, integer, intent(in) ND1, integer, intent(in) ND2) private
Definition at line 1167 of file speclib.F90.
References hgl().
Referenced by genwz(), and q_filter().
subroutine speclib::jacg (real(dp), dimension(np), intent(out) XJAC, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 445 of file speclib.F90.
References jacobf().
Referenced by zwgjd().
subroutine speclib::jacobf (real(dp), intent(out) POLY, real(dp), intent(out) PDER, real(dp), intent(out) POLYM1, real(dp), intent(out) PDERM1, real(dp), intent(out) POLYM2, real(dp), intent(out) PDERM2, integer, intent(in) N, real(dp), intent(in) ALP, real(dp), intent(in) BET, real(dp), intent(in) X) private
Definition at line 511 of file speclib.F90.
References n.
Referenced by dgjd(), dgljd(), dgljgjd(), hgjd(), hgljd(), jacg(), zwgjd(), and zwgljd().
real(dp) function speclib::pndleg (real(dp), intent(in) Z, integer, intent(in) N) private
Definition at line 984 of file speclib.F90.
Referenced by hgl(), and hgll().
real(dp) function speclib::pnleg (real(dp), intent(in) Z, integer, intent(in) N) private
Definition at line 953 of file speclib.F90.
Referenced by dgll(), dgllgl(), hgl(), and hgll().
real(dp) function speclib::pnormj (integer, intent(in) N, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 413 of file speclib.F90.
References gammaf().
Referenced by zwgjd().
subroutine speclib::zwgj (real(dp), dimension(np), intent(out) Z, real(dp), dimension(np), intent(out) W, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 113 of file speclib.F90.
References exitt(), and zwgjd().
Referenced by genwz(), and zwgl().
subroutine speclib::zwgjd (real(dp), dimension(np), intent(out) Z, real(dp), dimension(np), intent(out) W, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 148 of file speclib.F90.
References exitt(), gammaf(), jacg(), jacobf(), and pnormj().
Referenced by zwgj(), and zwgljd().
subroutine, public speclib::zwgl (real(dp), dimension(np), intent(out) Z, real(dp), dimension(np), intent(out) W, integer, intent(in) NP)
Generate NP Gauss Legendre points (Z) and weights (W) associated with Jacobi polynomial P(N)(alpha=0,beta=0). The polynomial degree N=NP-1. Z and W are in single precision, but all the arithmetic operations are done in double precision.
Parameters
[in] np
Definition at line 77 of file speclib.F90.
References zwgj().
Referenced by gen_dgl(), gen_fast_spacing(), gen_int(), generate_semhat(), genwz(), q_filter(), and set_dealias_rx().
subroutine, public speclib::zwglj (real(dp), dimension(np), intent(out) Z, real(dp), dimension(np), intent(out) W, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA)
Definition at line 204 of file speclib.F90.
References exitt(), and zwgljd().
Referenced by genwz(), and zwgll().
subroutine speclib::zwgljd (real(dp), dimension(np), intent(out) Z, real(dp), dimension(np), intent(out) W, integer, intent(in) NP, real(dp), intent(in) ALPHA, real(dp), intent(in) BETA) private
Definition at line 239 of file speclib.F90.
References endw1(), endw2(), exitt(), jacobf(), and zwgjd().
Referenced by zwglj().
subroutine, public speclib::zwgll (real(dp), dimension(np), intent(out) Z, real(dp), dimension(np), intent(out) W, integer, intent(in) NP)
Definition at line 95 of file speclib.F90.
References zwglj().
Referenced by gen_crs_basis(), gen_fast_spacing(), gen_int(), generate_semhat(), genwz(), mapab4r(), and q_filter().
Member Data Documentation
integer, parameter speclib::nmax = 84
Definition at line 70 of file speclib.F90.
The documentation for this module was generated from the following file:
speclib.F90