Nek5000: string Module Reference
string Module Reference
Public Member Functions
integer function i1_from_char (s1)
integer function indx2 (s1, l1, s2, l2)
integer function indx1 (S1, S2, L2)
integer function indx_cut (S1, S2, L2)
INDX_CUT is returned with the location of S2 in S1 (0 if not found) S1 is returned with 1st occurance of S2 removed.
subroutine csplit (s0, s1, s2, l0)
split string S1 into two parts, delimited by S2.
subroutine lshft (string, ipt)
shift string from IPT to the left INPUT : "abcde...... test " OUTPUT: "e...... test " if ipt.eq.5
subroutine ljust (string)
left justify string
subroutine capit (lettrs, n)
Capitalizes string of length n.
logical function ifgtrl (VALUE, LINE)
Read VALUE from LINE and set IFGTRL to .TRUE. if successful, IFGTRL to .FALSE. otherwise. This complicated function is necessary thanks to the Ardent, which won't allow free formatted reads (*) from internal strings!
logical function ifgtil (IVALUE, LINE)
Read IVALUE from LINE and set IFGTIL to .TRUE. if successful, IFGTIL to .FALSE. otherwise. This complicated function is necessary thanks to the Ardent, which won't allow free formatted reads (*) from internal strings!
integer function ltrunc (string, l)
subroutine cscan (sout, key, nk)
Detailed Description
Definition at line 1 of file string_mod.F90.
Member Function/Subroutine Documentation
subroutine string::capit (character(*) lettrs, integer, optional n)
Capitalizes string of length n.
Definition at line 161 of file string_mod.F90.
Referenced by helmholtz::hsolve(), rdbdry(), rdicdf(), rdparam(), sioflag(), and slogic().
subroutine string::cscan (character(*) sout, character(*) key, integer nk)
Definition at line 278 of file string_mod.F90.
References blank(), chcopy(), and indx1().
Referenced by readat().
subroutine string::csplit (character(*) s0, character(*) s1, character(*) s2, integer l0)
split string S1 into two parts, delimited by S2.
Definition at line 95 of file string_mod.F90.
References blank(), indx_cut(), and lshft().
Referenced by sioflag(), and slogic().
integer function string::i1_from_char (character(*) s1)
Definition at line 9 of file string_mod.F90.
References indx2().
Referenced by restart_driver().
logical function string::ifgtil (integer IVALUE, character(*) LINE)
Read IVALUE from LINE and set IFGTIL to .TRUE. if successful, IFGTIL to .FALSE. otherwise. This complicated function is necessary thanks to the Ardent, which won't allow free formatted reads (*) from internal strings!
Definition at line 229 of file string_mod.F90.
References indx1(), and ljust().
Referenced by rdicdf().
logical function string::ifgtrl (real(dp) VALUE, character(*) LINE)
Read VALUE from LINE and set IFGTRL to .TRUE. if successful, IFGTRL to .FALSE. otherwise. This complicated function is necessary thanks to the Ardent, which won't allow free formatted reads (*) from internal strings!
Definition at line 188 of file string_mod.F90.
References indx1(), and ljust().
Referenced by sioflag().
integer function string::indx1 (character(*) S1, character(*) S2, integer L2)
Definition at line 43 of file string_mod.F90.
Referenced by cscan(), err_chk(), exitti(), files(), ifgtil(), ifgtrl(), indx_cut(), mbyte_open(), rdbdry(), rdicdf(), rdparam(), restart_nfld(), sioflag(), and slogic().
integer function string::indx2 (character(*) s1, integer l1, character(*) s2, integer l2)
Definition at line 21 of file string_mod.F90.
Referenced by i1_from_char().
integer function string::indx_cut (character(*) S1, character(*) S2, integer L2)
INDX_CUT is returned with the location of S2 in S1 (0 if not found) S1 is returned with 1st occurance of S2 removed.
Definition at line 67 of file string_mod.F90.
References indx1().
Referenced by csplit(), sioflag(), and slogic().
subroutine string::ljust (character(*) string)
left justify string
Definition at line 134 of file string_mod.F90.
Referenced by ifgtil(), ifgtrl(), sioflag(), and slogic().
subroutine string::lshft (character(*) string, integer ipt)
shift string from IPT to the left INPUT : "abcde...... test " OUTPUT: "e...... test " if ipt.eq.5
Definition at line 116 of file string_mod.F90.
Referenced by csplit().
integer function string::ltrunc (character(l) string, integer l)
Definition at line 260 of file string_mod.F90.
Referenced by echopar(), files(), io::get_restart_name(), get_vert_map(), mbyte_open(), mfo_open_files(), outfld(), pprint_all(), restart_driver(), restart_nfld(), sioflag(), and slogic().
The documentation for this module was generated from the following file:
string_mod.F90