Nek5000: ctimer Module Reference
ctimer Module Reference
Public Member Functions
real(dp) function dnekclock ()
real(dp) function dnekclock_sync ()
subroutine sum_flops ()
Public Attributes
real(dp) tmxmf
real(dp) tmxms
real(dp) tdsum
real(dp) tcopy
real(dp) tinvc
real(dp) tinv3
real(dp) tsolv
real(dp) tgsum
real(dp) tdsnd
real(dp) tdadd
real(dp) tcdtp
real(dp) tmltd
real(dp) tpres
real(dp) tgop
real(dp) tgop1
real(dp) tdott
real(dp) tbsol
real(dp) tbso2
real(dp) tsett
real(dp) tslvb
real(dp) tusbc
real(dp) tddsl
real(dp) tcrsl
real(dp) tdsmx
real(dp) tdsmn
real(dp) tgsmn
real(dp) tgsmx
real(dp) teslv
real(dp) tbbbb
real(dp) tcccc
real(dp) tdddd
real(dp) teeee
real(dp) tvdss
real(dp) tspro
real(dp) tgop_sync
real(dp) tsyc
real(dp) twal
real(dp), save tproj = 0._dp
real(dp), save thconj = 0._dp
real(dp), save taxhm = 0._dp
real(dp), save tcggo = 0._dp
real(dp), save tsetfast = 0._dp
real(dp), save tintp = 0._dp
real(dp), save tgrst = 0._dp
real(dp), save tdpc = 0._dp
real(dp), save tgmres = 0._dp
real(dp), save th1mg = 0._dp
real(dp), save tscps = 0._dp
real(dp), save tcrespsp = 0._dp
real(dp), save tcresvsp = 0._dp
real(dp), save theat2 = 0._dp
real(dp), save tp4misc = 0._dp
real(dp), save tmakef = 0._dp
real(dp), save tmakeq = 0._dp
real(dp), save tprep = 0._dp
real(dp), save tscn = 0._dp
real(dp), save tmg_mask = 0._dp
real(dp), save tschw = 0._dp
real(dp), save tnmsc = 0._dp
real(dp), save tnmvc = 0._dp
real(dp), save tadvc = 0._dp
real(dp), save thmhz = 0._dp
real(dp), save tfoo = 0._dp
integer, save nproj = 0
integer, save nhconj = 0
integer, save naxhm = 0
integer, save ncggo = 0
integer, save nsetfast = 0
integer, save nintp = 0
integer, save ngrst = 0
integer, save ndpc = 0
integer, save ngmres = 0
integer, save nh1mg = 0
integer, save nscps = 0
integer, save ncrespsp = 0
integer, save ncresvsp = 0
integer, save nheat2 = 0
integer, save np4misc = 0
integer, save nmakef = 0
integer, save nmakeq = 0
integer, save nprep = 0
integer, save nscn = 0
integer, save nmg_mask = 0
integer, save nschw = 0
integer, save nnmsc = 0
integer, save nnmvc = 0
integer, save nadvc = 0
integer, save nhmhz = 0
integer, save nfoo = 0
integer nmxmf
integer nmxms
integer ndsum
integer ncopy
integer ninvc
integer ninv3
integer nsolv
integer ngsum
integer ndsnd
integer ndadd
integer ncdtp
integer nmltd
integer npres
integer ngop
integer ngop1
integer ndott
integer nbsol
integer nbso2
integer nsett
integer nslvb
integer nusbc
integer nddsl
integer ncrsl
integer ndsmx
integer ndsmn
integer ngsmn
integer ngsmx
integer neslv
integer nbbbb
integer ncccc
integer ndddd
integer neeee
integer nvdss
integer nspro
integer ngop_sync
integer nsyc
integer nwal
real(dp) pmxmf
real(dp) pmxms
real(dp) pdsum
real(dp) paxhm
real(dp) pcopy
real(dp) pinvc
real(dp) pinv3
real(dp) psolv
real(dp) pgsum
real(dp) pdsnd
real(dp) pdadd
real(dp) pcdtp
real(dp) pmltd
real(dp) ppres
real(dp) phmhz
real(dp) pgop
real(dp) pgop1
real(dp) pdott
real(dp) pbsol
real(dp) pbso2
real(dp) psett
real(dp) pslvb
real(dp) pusbc
real(dp) pddsl
real(dp) pcrsl
real(dp) pdsmx
real(dp) pdsmn
real(dp) pgsmn
real(dp) pgsmx
real(dp) peslv
real(dp) pbbbb
real(dp) pcccc
real(dp) pdddd
real(dp) peeee
real(dp) pvdss
real(dp) pspro
real(dp) pgop_sync
real(dp) psyc
real(dp) pwal
real(dp) etime1
real(dp) etime2
real(dp) etime0
real(dp) gtime1
real(dp) tscrtch
real(dp) etimes
real(dp) ttotal
real(dp) tttstp
real(dp) etims0
real(dp) ttime
integer, save icalld = 0
logical ifsync
real(dp), save time_flop = 0._dp
integer(i8), save total_flop
integer(i8), save total_mop
integer(i8), save axhelm_flop = 0
integer(i8), save axhelm_mop = 0
integer(i8), save h1mg_flop = 0
integer(i8), save h1mg_mop = 0
integer(i8), save schw_flop = 0
integer(i8), save schw_mop = 0
integer(i8), save hconj_flop = 0
integer(i8), save hconj_mop = 0
integer(i8), save proj_flop = 0
integer(i8), save proj_mop = 0
integer(i8), save cggo_flop = 0
integer(i8), save cggo_mop = 0
integer(i8), save gmres_flop = 0
integer(i8), save gmres_mop = 0
integer(i8), save intp_flop = 0
integer(i8), save intp_mop = 0
integer(i8), save grst_flop = 0
integer(i8), save grst_mop = 0
Detailed Description
Definition at line 1 of file ctimer_mod.F90.
Member Function/Subroutine Documentation
real(dp) function ctimer::dnekclock ()
Definition at line 103 of file ctimer_mod.F90.
References mpi_wtime().
Referenced by axhelm(), bcdirsc(), bcdirvc(), bcneusc(), cdscal(), cdtp(), cggo(), chktcg1(), comment(), convect_new(), convop(), crespsp(), cresvsp(), dssum(), exitt(), fluid(), gop(), hsmg_routines::h1mg_mask(), hsmg_routines::h1mg_schwarz(), hsmg_routines::h1mg_schwarz_part1(), hsmg_routines::h1mg_solve(), helmholtz::hconj(), heat(), hmh_gmres(), hmholtz(), helmholtz::hmhzpf(), hsmg_routines::hsmg_coarse_solve(), hsmg_routines::hsmg_dssum(), hsmg_routines::hsmg_schwarz_dssum(), makef(), makeq(), multd(), nek_init(), normsc(), normvc(), outpost2(), plan4(), prepost(), helmholtz::projh(), readat(), runstat(), set_convect_new(), set_up_h1_crs(), setfast(), setprec(), setprop(), setupds(), poisson::spectral_solve(), and vec_dssum().
real(dp) function ctimer::dnekclock_sync ()
Definition at line 113 of file ctimer_mod.F90.
References mpi_wtime(), and nekgsync().
Referenced by mfo_outfld(), and nek_init().
subroutine ctimer::sum_flops ()
Definition at line 124 of file ctimer_mod.F90.
Referenced by runstat().
Member Data Documentation
integer(i8), save ctimer::axhelm_flop = 0
Definition at line 90 of file ctimer_mod.F90.
integer(i8), save ctimer::axhelm_mop = 0
Definition at line 90 of file ctimer_mod.F90.
integer(i8), save ctimer::cggo_flop = 0
Definition at line 95 of file ctimer_mod.F90.
integer(i8), save ctimer::cggo_mop = 0
Definition at line 95 of file ctimer_mod.F90.
real(dp) ctimer::etime0
Definition at line 80 of file ctimer_mod.F90.
real(dp) ctimer::etime1
Definition at line 80 of file ctimer_mod.F90.
real(dp) ctimer::etime2
Definition at line 80 of file ctimer_mod.F90.
real(dp) ctimer::etimes
Definition at line 82 of file ctimer_mod.F90.
real(dp) ctimer::etims0
Definition at line 82 of file ctimer_mod.F90.
integer(i8), save ctimer::gmres_flop = 0
Definition at line 96 of file ctimer_mod.F90.
integer(i8), save ctimer::gmres_mop = 0
Definition at line 96 of file ctimer_mod.F90.
integer(i8), save ctimer::grst_flop = 0
Definition at line 98 of file ctimer_mod.F90.
integer(i8), save ctimer::grst_mop = 0
Definition at line 98 of file ctimer_mod.F90.
real(dp) ctimer::gtime1
Definition at line 80 of file ctimer_mod.F90.
integer(i8), save ctimer::h1mg_flop = 0
Definition at line 91 of file ctimer_mod.F90.
integer(i8), save ctimer::h1mg_mop = 0
Definition at line 91 of file ctimer_mod.F90.
integer(i8), save ctimer::hconj_flop = 0
Definition at line 93 of file ctimer_mod.F90.
integer(i8), save ctimer::hconj_mop = 0
Definition at line 93 of file ctimer_mod.F90.
integer, save ctimer::icalld = 0
Definition at line 84 of file ctimer_mod.F90.
logical ctimer::ifsync
Definition at line 86 of file ctimer_mod.F90.
integer(i8), save ctimer::intp_flop = 0
Definition at line 97 of file ctimer_mod.F90.
integer(i8), save ctimer::intp_mop = 0
Definition at line 97 of file ctimer_mod.F90.
integer, save ctimer::nadvc = 0
Definition at line 62 of file ctimer_mod.F90.
integer, save ctimer::naxhm = 0
Definition at line 41 of file ctimer_mod.F90.
integer ctimer::nbbbb
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nbso2
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nbsol
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ncccc
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ncdtp
Definition at line 67 of file ctimer_mod.F90.
integer, save ctimer::ncggo = 0
Definition at line 42 of file ctimer_mod.F90.
integer ctimer::ncopy
Definition at line 66 of file ctimer_mod.F90.
integer, save ctimer::ncrespsp = 0
Definition at line 50 of file ctimer_mod.F90.
integer, save ctimer::ncresvsp = 0
Definition at line 51 of file ctimer_mod.F90.
integer ctimer::ncrsl
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ndadd
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ndddd
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nddsl
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ndott
Definition at line 67 of file ctimer_mod.F90.
integer, save ctimer::ndpc = 0
Definition at line 46 of file ctimer_mod.F90.
integer ctimer::ndsmn
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ndsmx
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ndsnd
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ndsum
Definition at line 66 of file ctimer_mod.F90.
integer ctimer::neeee
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::neslv
Definition at line 67 of file ctimer_mod.F90.
integer, save ctimer::nfoo = 0
Definition at line 64 of file ctimer_mod.F90.
integer, save ctimer::ngmres = 0
Definition at line 47 of file ctimer_mod.F90.
integer ctimer::ngop
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ngop1
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ngop_sync
Definition at line 67 of file ctimer_mod.F90.
integer, save ctimer::ngrst = 0
Definition at line 45 of file ctimer_mod.F90.
integer ctimer::ngsmn
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ngsmx
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::ngsum
Definition at line 67 of file ctimer_mod.F90.
integer, save ctimer::nh1mg = 0
Definition at line 48 of file ctimer_mod.F90.
integer, save ctimer::nhconj = 0
Definition at line 40 of file ctimer_mod.F90.
integer, save ctimer::nheat2 = 0
Definition at line 52 of file ctimer_mod.F90.
integer, save ctimer::nhmhz = 0
Definition at line 63 of file ctimer_mod.F90.
integer, save ctimer::nintp = 0
Definition at line 44 of file ctimer_mod.F90.
integer ctimer::ninv3
Definition at line 66 of file ctimer_mod.F90.
integer ctimer::ninvc
Definition at line 66 of file ctimer_mod.F90.
integer, save ctimer::nmakef = 0
Definition at line 54 of file ctimer_mod.F90.
integer, save ctimer::nmakeq = 0
Definition at line 55 of file ctimer_mod.F90.
integer, save ctimer::nmg_mask = 0
Definition at line 58 of file ctimer_mod.F90.
integer ctimer::nmltd
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nmxmf
Definition at line 66 of file ctimer_mod.F90.
integer ctimer::nmxms
Definition at line 66 of file ctimer_mod.F90.
integer, save ctimer::nnmsc = 0
Definition at line 60 of file ctimer_mod.F90.
integer, save ctimer::nnmvc = 0
Definition at line 61 of file ctimer_mod.F90.
integer, save ctimer::np4misc = 0
Definition at line 53 of file ctimer_mod.F90.
integer, save ctimer::nprep = 0
Definition at line 56 of file ctimer_mod.F90.
integer ctimer::npres
Definition at line 67 of file ctimer_mod.F90.
integer, save ctimer::nproj = 0
Definition at line 39 of file ctimer_mod.F90.
integer, save ctimer::nschw = 0
Definition at line 59 of file ctimer_mod.F90.
integer, save ctimer::nscn = 0
Definition at line 57 of file ctimer_mod.F90.
integer, save ctimer::nscps = 0
Definition at line 49 of file ctimer_mod.F90.
integer, save ctimer::nsetfast = 0
Definition at line 43 of file ctimer_mod.F90.
integer ctimer::nsett
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nslvb
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nsolv
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nspro
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nsyc
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nusbc
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nvdss
Definition at line 67 of file ctimer_mod.F90.
integer ctimer::nwal
Definition at line 67 of file ctimer_mod.F90.
real(dp) ctimer::paxhm
Definition at line 73 of file ctimer_mod.F90.
real(dp) ctimer::pbbbb
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pbso2
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pbsol
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pcccc
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pcdtp
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pcopy
Definition at line 73 of file ctimer_mod.F90.
real(dp) ctimer::pcrsl
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pdadd
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pdddd
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pddsl
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pdott
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pdsmn
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pdsmx
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pdsnd
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pdsum
Definition at line 73 of file ctimer_mod.F90.
real(dp) ctimer::peeee
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::peslv
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pgop
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pgop1
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pgop_sync
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pgsmn
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pgsmx
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pgsum
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::phmhz
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pinv3
Definition at line 73 of file ctimer_mod.F90.
real(dp) ctimer::pinvc
Definition at line 73 of file ctimer_mod.F90.
real(dp) ctimer::pmltd
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pmxmf
Definition at line 73 of file ctimer_mod.F90.
real(dp) ctimer::pmxms
Definition at line 73 of file ctimer_mod.F90.
real(dp) ctimer::ppres
Definition at line 74 of file ctimer_mod.F90.
integer(i8), save ctimer::proj_flop = 0
Definition at line 94 of file ctimer_mod.F90.
integer(i8), save ctimer::proj_mop = 0
Definition at line 94 of file ctimer_mod.F90.
real(dp) ctimer::psett
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pslvb
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::psolv
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pspro
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::psyc
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pusbc
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pvdss
Definition at line 74 of file ctimer_mod.F90.
real(dp) ctimer::pwal
Definition at line 74 of file ctimer_mod.F90.
integer(i8), save ctimer::schw_flop = 0
Definition at line 92 of file ctimer_mod.F90.
integer(i8), save ctimer::schw_mop = 0
Definition at line 92 of file ctimer_mod.F90.
real(dp), save ctimer::tadvc = 0._dp
Definition at line 35 of file ctimer_mod.F90.
real(dp), save ctimer::taxhm = 0._dp
Definition at line 14 of file ctimer_mod.F90.
real(dp) ctimer::tbbbb
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tbso2
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tbsol
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tcccc
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tcdtp
Definition at line 6 of file ctimer_mod.F90.
real(dp), save ctimer::tcggo = 0._dp
Definition at line 15 of file ctimer_mod.F90.
real(dp) ctimer::tcopy
Definition at line 5 of file ctimer_mod.F90.
real(dp), save ctimer::tcrespsp = 0._dp
Definition at line 23 of file ctimer_mod.F90.
real(dp), save ctimer::tcresvsp = 0._dp
Definition at line 24 of file ctimer_mod.F90.
real(dp) ctimer::tcrsl
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tdadd
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tdddd
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tddsl
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tdott
Definition at line 6 of file ctimer_mod.F90.
real(dp), save ctimer::tdpc = 0._dp
Definition at line 19 of file ctimer_mod.F90.
real(dp) ctimer::tdsmn
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tdsmx
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tdsnd
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tdsum
Definition at line 5 of file ctimer_mod.F90.
real(dp) ctimer::teeee
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::teslv
Definition at line 6 of file ctimer_mod.F90.
real(dp), save ctimer::tfoo = 0._dp
Definition at line 37 of file ctimer_mod.F90.
real(dp), save ctimer::tgmres = 0._dp
Definition at line 20 of file ctimer_mod.F90.
real(dp) ctimer::tgop
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tgop1
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tgop_sync
Definition at line 6 of file ctimer_mod.F90.
real(dp), save ctimer::tgrst = 0._dp
Definition at line 18 of file ctimer_mod.F90.
real(dp) ctimer::tgsmn
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tgsmx
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tgsum
Definition at line 6 of file ctimer_mod.F90.
real(dp), save ctimer::th1mg = 0._dp
Definition at line 21 of file ctimer_mod.F90.
real(dp), save ctimer::thconj = 0._dp
Definition at line 13 of file ctimer_mod.F90.
real(dp), save ctimer::theat2 = 0._dp
Definition at line 25 of file ctimer_mod.F90.
real(dp), save ctimer::thmhz = 0._dp
Definition at line 36 of file ctimer_mod.F90.
real(dp), save ctimer::time_flop = 0._dp
Definition at line 88 of file ctimer_mod.F90.
real(dp), save ctimer::tintp = 0._dp
Definition at line 17 of file ctimer_mod.F90.
real(dp) ctimer::tinv3
Definition at line 5 of file ctimer_mod.F90.
real(dp) ctimer::tinvc
Definition at line 5 of file ctimer_mod.F90.
real(dp), save ctimer::tmakef = 0._dp
Definition at line 27 of file ctimer_mod.F90.
real(dp), save ctimer::tmakeq = 0._dp
Definition at line 28 of file ctimer_mod.F90.
real(dp), save ctimer::tmg_mask = 0._dp
Definition at line 31 of file ctimer_mod.F90.
real(dp) ctimer::tmltd
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tmxmf
Definition at line 5 of file ctimer_mod.F90.
real(dp) ctimer::tmxms
Definition at line 5 of file ctimer_mod.F90.
real(dp), save ctimer::tnmsc = 0._dp
Definition at line 33 of file ctimer_mod.F90.
real(dp), save ctimer::tnmvc = 0._dp
Definition at line 34 of file ctimer_mod.F90.
integer(i8), save ctimer::total_flop
Definition at line 89 of file ctimer_mod.F90.
integer(i8), save ctimer::total_mop
Definition at line 89 of file ctimer_mod.F90.
real(dp), save ctimer::tp4misc = 0._dp
Definition at line 26 of file ctimer_mod.F90.
real(dp), save ctimer::tprep = 0._dp
Definition at line 29 of file ctimer_mod.F90.
real(dp) ctimer::tpres
Definition at line 6 of file ctimer_mod.F90.
real(dp), save ctimer::tproj = 0._dp
Definition at line 12 of file ctimer_mod.F90.
real(dp), save ctimer::tschw = 0._dp
Definition at line 32 of file ctimer_mod.F90.
real(dp), save ctimer::tscn = 0._dp
Definition at line 30 of file ctimer_mod.F90.
real(dp), save ctimer::tscps = 0._dp
Definition at line 22 of file ctimer_mod.F90.
real(dp) ctimer::tscrtch
Definition at line 80 of file ctimer_mod.F90.
real(dp), save ctimer::tsetfast = 0._dp
Definition at line 16 of file ctimer_mod.F90.
real(dp) ctimer::tsett
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tslvb
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tsolv
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tspro
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tsyc
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::ttime
Definition at line 82 of file ctimer_mod.F90.
real(dp) ctimer::ttotal
Definition at line 82 of file ctimer_mod.F90.
real(dp) ctimer::tttstp
Definition at line 82 of file ctimer_mod.F90.
real(dp) ctimer::tusbc
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::tvdss
Definition at line 6 of file ctimer_mod.F90.
real(dp) ctimer::twal
Definition at line 6 of file ctimer_mod.F90.
The documentation for this module was generated from the following file:
ctimer_mod.F90