Nek5000: parallel Module Reference
parallel Module Reference
cleaned
Public Member Functions
subroutine init_parallel ()
subroutine init_gllnid ()
integer function gllnid (ieg)
logical function my_ieg (ieg)
integer function gllel (ieg)
integer function lglel (iel)
Public Attributes
integer node
integer pid
integer np
integer nullpid
integer node0
integer, dimension(:), allocatable nelg
integer nvtot
integer nelgv
integer nelgt
logical ifgprnt
integer wdsize
integer isize
integer lsize
integer csize
integer wdsizi
logical ifdblas
integer cr_h
integer gsh
integer, dimension(:), allocatable gsh_fld
integer, dimension(:), allocatable xxth
integer nekcomm
integer nekgroup
integer nekreal
integer, dimension(3) proc_pos
integer, dimension(3) proc_shape
Private Attributes
integer, dimension(30), private queue_dim
integer, dimension(30), private queue_fac
integer, dimension(30), private queue_div
integer, private num_queue
Detailed Description
cleaned
Definition at line 2 of file parallel_mod.F90.
Member Function/Subroutine Documentation
integer function parallel::gllel (integer, intent(in) ieg)
Definition at line 162 of file parallel_mod.F90.
References mesh::ieg_to_xyz().
Referenced by genmesh(), get_vert_map(), poisson::grid_to_mesh(), init_gllnid(), mapdmp(), outfld(), outhis(), rdbdry(), rdcurve(), and rdmesh().
integer function parallel::gllnid (integer, intent(in) ieg)
Definition at line 115 of file parallel_mod.F90.
References mesh::ieg_to_xyz().
Referenced by genmesh(), get_vert_map(), poisson::grid_to_mesh(), init_gllnid(), poisson::init_mesh_to_grid(), mapdmp(), poisson::mesh_to_grid(), outfld(), outhis(), rdbdry(), rdcurve(), rdmesh(), and restart_driver().
subroutine parallel::init_gllnid ()
Definition at line 47 of file parallel_mod.F90.
References gllel(), gllnid(), lglel(), and np.
Referenced by get_vert_map().
subroutine parallel::init_parallel ()
Definition at line 38 of file parallel_mod.F90.
Referenced by nek_init().
integer function parallel::lglel (integer, intent(in) iel)
Definition at line 176 of file parallel_mod.F90.
References mesh::xyz_to_ieg().
Referenced by bcneusc(), chkjac(), poisson::cos_test(), genmesh(), get_fast_bc(), get_vert_map(), poisson::grid_to_mesh(), init_gllnid(), poisson::init_mesh_to_grid(), mapelpr(), poisson::mesh_to_grid(), io::mfo_read_header(), mfo_write_hdr(), my_ieg(), nekuf(), nekuic(), nekuq(), setvert3d(), poisson::shuffle_test(), poisson::spectral_solve(), poisson::transpose_test(), verrhe(), and vrdsmsh().
logical function parallel::my_ieg (integer, intent(in) ieg)
Definition at line 133 of file parallel_mod.F90.
References mesh::ieg_to_xyz(), and lglel().
Member Data Documentation
integer parallel::cr_h
Definition at line 22 of file parallel_mod.F90.
integer parallel::csize
Definition at line 17 of file parallel_mod.F90.
integer parallel::gsh
Definition at line 22 of file parallel_mod.F90.
integer, dimension(:), allocatable parallel::gsh_fld
Definition at line 23 of file parallel_mod.F90.
logical parallel::ifdblas
Definition at line 18 of file parallel_mod.F90.
logical parallel::ifgprnt
Definition at line 16 of file parallel_mod.F90.
integer parallel::isize
Definition at line 17 of file parallel_mod.F90.
integer parallel::lsize
Definition at line 17 of file parallel_mod.F90.
integer parallel::nekcomm
Definition at line 25 of file parallel_mod.F90.
integer parallel::nekgroup
Definition at line 25 of file parallel_mod.F90.
integer parallel::nekreal
Definition at line 25 of file parallel_mod.F90.
integer, dimension(:), allocatable parallel::nelg
Definition at line 13 of file parallel_mod.F90.
integer parallel::nelgt
Definition at line 14 of file parallel_mod.F90.
integer parallel::nelgv
Definition at line 14 of file parallel_mod.F90.
integer parallel::node
Definition at line 8 of file parallel_mod.F90.
integer parallel::node0
Definition at line 8 of file parallel_mod.F90.
integer parallel::np
Definition at line 8 of file parallel_mod.F90.
integer parallel::nullpid
Definition at line 8 of file parallel_mod.F90.
integer, private parallel::num_queue private
Definition at line 31 of file parallel_mod.F90.
integer parallel::nvtot
Definition at line 14 of file parallel_mod.F90.
integer parallel::pid
Definition at line 8 of file parallel_mod.F90.
integer, dimension(3) parallel::proc_pos
Definition at line 32 of file parallel_mod.F90.
integer, dimension(3) parallel::proc_shape
Definition at line 33 of file parallel_mod.F90.
integer, dimension(30), private parallel::queue_dim private
Definition at line 28 of file parallel_mod.F90.
integer, dimension(30), private parallel::queue_div private
Definition at line 30 of file parallel_mod.F90.
integer, dimension(30), private parallel::queue_fac private
Definition at line 29 of file parallel_mod.F90.
integer parallel::wdsize
Definition at line 17 of file parallel_mod.F90.
integer parallel::wdsizi
Definition at line 17 of file parallel_mod.F90.
integer, dimension(:), allocatable parallel::xxth
Definition at line 23 of file parallel_mod.F90.
The documentation for this module was generated from the following file:
parallel_mod.F90