Nek5000: fft Module Reference
fft Module Reference
Public Member Functions
subroutine, public fft_r2r (u, length, num, kind, rescale)
Compute a number of 1D FFTs or DCTs.
real(dp) function, public wavenumber (i, N, L, kind)
Get the wavenumber of the ith mode.
subroutine, public transpose_grid (grid, grid_t, shape_x, idx, idx_t, comm)
Global (parallel) transform of grid data.
Public Attributes
integer, parameter, public w_forward = FFTW_REDFT10
integer, parameter, public w_backward = FFTW_REDFT01
integer, parameter, public p_forward = FFTW_R2HC
integer, parameter, public p_backward = FFTW_HC2R
Private Attributes
integer, parameter nplans = 10
integer n_r2r_plans = 0
type(c_ptr), dimension(nplans) r2r_plans
integer, dimension(nplans) r2r_plan_lengths
integer, dimension(nplans) r2r_plan_nums
integer(c_int), dimension(nplans) r2r_plan_kinds
Detailed Description
Definition at line 12 of file fft_fftw_mod.F90.
Member Function/Subroutine Documentation
subroutine, public fft::fft_r2r (real(dp), dimension(:,:,:), intent(inout) u, integer, intent(in) length, integer, intent(in) num, integer(c_int) kind, real(dp), intent(inout) rescale)
Compute a number of 1D FFTs or DCTs.
The transforms are performed inplace. Rescale is rescaled by the normalization factor of the transform.
Parameters
[in,out] u data, leading dim is transformed
[in] length length of leading dimension
[in] num number of transforms
kind Type of transform. See pulic parameters
[in,out] rescale Normalization factor
Definition at line 41 of file fft_fftw_mod.F90.
Referenced by poisson::cos_test(), poisson::shuffle_test(), and poisson::spectral_solve().
subroutine, public fft::transpose_grid (real(dp), dimension(0:,0:,0:), intent(inout) grid, real(dp), dimension(0:,0:,0:), intent(out) grid_t, integer, dimension(3), intent(in) shape_x, integer, intent(in) idx, integer, intent(in) idx_t, integer, intent(in) comm)
Global (parallel) transform of grid data.
Definition at line 132 of file fft_fftw_mod.F90.
References mpi_comm_size(), and transpose().
Referenced by poisson::cos_test(), poisson::shuffle_test(), poisson::spectral_solve(), and poisson::transpose_test().
real(dp) function, public fft::wavenumber (integer, intent(in) i, integer, intent(in) N, real(dp), intent(in) L, integer, intent(in) kind)
Get the wavenumber of the ith mode.
Parameters
[in] i index of mode
[in] n number of modes in transform
[in] l Length of domain in transform
[in] kind Type of transform
Definition at line 107 of file fft_fftw_mod.F90.
Referenced by poisson::poisson_kernel().
Member Data Documentation
integer fft::n_r2r_plans = 0 private
Definition at line 23 of file fft_fftw_mod.F90.
integer, parameter fft::nplans = 10 private
Definition at line 22 of file fft_fftw_mod.F90.
integer, parameter, public fft::p_backward = FFTW_HC2R
Definition at line 32 of file fft_fftw_mod.F90.
integer, parameter, public fft::p_forward = FFTW_R2HC
Definition at line 31 of file fft_fftw_mod.F90.
integer(c_int), dimension(nplans) fft::r2r_plan_kinds private
Definition at line 27 of file fft_fftw_mod.F90.
integer, dimension(nplans) fft::r2r_plan_lengths private
Definition at line 25 of file fft_fftw_mod.F90.
integer, dimension(nplans) fft::r2r_plan_nums private
Definition at line 26 of file fft_fftw_mod.F90.
type(c_ptr), dimension(nplans) fft::r2r_plans private
Definition at line 24 of file fft_fftw_mod.F90.
integer, parameter, public fft::w_backward = FFTW_REDFT01
Definition at line 30 of file fft_fftw_mod.F90.
integer, parameter, public fft::w_forward = FFTW_REDFT10
Definition at line 29 of file fft_fftw_mod.F90.
The documentation for this module was generated from the following file:
fft_fftw_mod.F90