Nek5000: comm_mpi.F90 File Reference
comm_mpi.F90 File Reference
Functions/Subroutines
subroutine iniproc (intracomm)
subroutine init_nek_comm (intracomm)
subroutine gop (x, w, op, n)
Global vector commutative operation.
subroutine igop (x, w, op, n)
Global vector commutative operation.
subroutine i8gop (x, w, op, n)
Global vector commutative operation.
subroutine csend (mtype, buf, len, jnid, jpid)
subroutine crecv (mtype, buf, lenm)
integer function numnodes ()
integer function mynode ()
subroutine lbcast (ifif)
Broadcast logical variable to all processors.
subroutine bcast (buf, len)
integer function irecv (msgtag, x, len)
subroutine nekgsync ()
subroutine exitti (stringi, idata)
subroutine err_chk (ierr, istring)
subroutine exitt0
subroutine exitt
subroutine printheader
integer function igl_running_sum (in)
subroutine msgwait (imsg)
Function/Subroutine Documentation
subroutine bcast (real(r4) buf, integer len)
Definition at line 289 of file comm_mpi.F90.
References mpi_bcast().
Referenced by genmesh(), get_session_info(), get_vert_map(), lbcast(), mfo_outfld(), io::mfo_read_header(), nek_comm_io(), outfld(), rdhist(), rdicdf(), rdmatp(), rdobj(), rdout(), rdparam(), readat(), and restart_driver().
subroutine crecv (integer mtype, real(r4), dimension(1) buf, integer lenm)
Definition at line 223 of file comm_mpi.F90.
References exitt(), and mpi_recv().
Referenced by mapdmp(), mapelpr(), mfo_mdatas(), mfo_mdatav(), mfo_outs(), mfo_outv(), io::mfo_read_header(), io::mfo_read_scalar(), io::mfo_read_vector(), mfo_write_hdr(), nek_comm_io(), opcount(), outfld(), outhis(), and pprint_all().
subroutine csend (integer mtype, real(r4), dimension(1) buf, integer len, integer jnid, integer jpid)
Definition at line 209 of file comm_mpi.F90.
References mpi_send().
Referenced by mapdmp(), mapelpr(), mfo_mdatas(), mfo_mdatav(), mfo_outs(), mfo_outv(), io::mfo_read_header(), io::mfo_read_scalar(), io::mfo_read_vector(), mfo_write_hdr(), nek_comm_io(), opcount(), outfld(), outhis(), and pprint_all().
subroutine err_chk (integer ierr, character(*) istring)
Definition at line 356 of file comm_mpi.F90.
References blank(), chcopy(), exitt(), and string::indx1().
Referenced by get_session_info(), mapdmp(), mfo_mdatas(), mfo_mdatav(), mfo_outfld(), mfo_outs(), mfo_outv(), io::mfo_read_header(), io::mfo_read_scalar(), io::mfo_read_vector(), mfo_write_hdr(), outfld(), prepost(), rdhist(), rdobj(), and restart_driver().
subroutine exitt ()
Definition at line 411 of file comm_mpi.F90.
References ctimer::dnekclock(), flush_io(), happy_check(), mpi_finalize(), nek_flops(), nekgsync(), np, and print_stack.
Referenced by build_new_filter(), byte_set_view(), chk_nel(), chkaxcb(), chkcbc(), crecv(), speclib::dgj(), speclib::dgjd(), speclib::dglj(), speclib::dgljd(), speclib::dgljgj(), speclib::dgljgjd(), echopar(), err_chk(), exitti(), gaujordf(), gbtuple_rank(), generalev(), get_vert_map(), glmapm1(), gop(), hsmg_routines::h1mg_setup_fdm(), hsmg_routines::h1mg_setup_schwarz_wt(), hsmg_routines::h1mg_setup_wtmask(), speclib::hgj(), speclib::hglj(), hsmg_routines::hsmg_setup_fdm(), hsmg_routines::hsmg_setup_schwarz_wt(), hsmg_routines::hsmg_setup_solve(), hsmg_routines::hsmg_setup_wtmask(), i8gop(), i_find_prefix(), igop(), iniproc(), io_init(), iswapt_ip(), mapelpr(), mfo_outs(), mfo_outv(), io::mfo_read_scalar(), io::mfo_read_vector(), nek_comm_io(), nekton(), outpost2(), rdbdry(), rdcurve(), rdhist(), rdmatp(), rdmesh(), rdout(), rdparam(), readat(), restart_driver(), setics(), setlog(), setvar(), solve(), specmpn(), tensr3(), verrhe(), vprops(), vrdsmsh(), speclib::zwgj(), speclib::zwgjd(), speclib::zwglj(), and speclib::zwgljd().
subroutine exitt0 ()
Definition at line 390 of file comm_mpi.F90.
References flush_io(), mpi_finalize(), and print_stack.
Referenced by get_vert_map().
subroutine exitti (character(132) stringi, integer idata)
Definition at line 328 of file comm_mpi.F90.
References blank(), chcopy(), exitt(), and string::indx1().
Referenced by assign_gllnid(), get_fast_bc(), hsmg_routines::h1mg_setup_mask(), hsmg_routines::hsmg_setup_fast(), lim_chk(), mapdmp(), ortho(), rdicdf(), rdout(), rdparam(), readat(), setup_convect(), and setzgml().
subroutine gop (real(dp), dimension(n) x, real(dp), dimension(n) w, character(3) op, integer n)
Global vector commutative operation.
Definition at line 104 of file comm_mpi.F90.
References copy(), ctimer::dnekclock(), exitt(), mpi_allreduce(), and nekgsync().
Referenced by cggo(), glamax(), gllog(), glmax(), glmin(), glsc2(), glsc23(), glsc3(), glsum(), helmholtz::hconj(), hmh_gmres(), opcount(), prepost(), helmholtz::projh(), runstat(), and vrdsmsh().
subroutine i8gop (integer(i8), dimension(n) x, integer(i8), dimension(n) w, character(3) op, integer n)
Global vector commutative operation.
Definition at line 181 of file comm_mpi.F90.
References exitt(), and mpi_allreduce().
Referenced by i8glmax(), and i8glsum().
integer function igl_running_sum (integer in)
Definition at line 493 of file comm_mpi.F90.
References mpi_scan().
subroutine igop (integer, dimension(n), intent(inout) x, integer, dimension(n), intent(inout) w, character(3), intent(in) op, integer, intent(in) n)
Global vector commutative operation.
Definition at line 152 of file comm_mpi.F90.
References exitt(), and mpi_allreduce().
Referenced by iglmax(), iglmin(), and iglsum().
subroutine iniproc (integer intracomm)
Definition at line 2 of file comm_mpi.F90.
References exitt(), init_nek_comm(), mpi_attr_get(), np, and printheader().
Referenced by get_session_info().
subroutine init_nek_comm (integer intracomm)
Definition at line 89 of file comm_mpi.F90.
References np.
Referenced by iniproc().
integer function irecv (integer msgtag, integer, dimension(1) x, integer len)
Definition at line 304 of file comm_mpi.F90.
References mpi_irecv().
subroutine lbcast (logical ifif)
Broadcast logical variable to all processors.
Definition at line 270 of file comm_mpi.F90.
References bcast(), and np.
Referenced by restart_driver().
subroutine msgwait (integer imsg)
Definition at line 510 of file comm_mpi.F90.
References mpi_wait().
integer function mynode ()
Definition at line 258 of file comm_mpi.F90.
References mpi_comm_rank().
subroutine nekgsync ()
Definition at line 318 of file comm_mpi.F90.
References mpi_barrier().
Referenced by ctimer::dnekclock_sync(), dsop(), dssum(), exitt(), get_vert_map(), gop(), hsmg_routines::hsmg_coarse_solve(), hsmg_routines::hsmg_dsprod(), hsmg_routines::hsmg_dssum(), hsmg_routines::hsmg_schwarz_dssum(), poisson::init_comm_infrastructure(), poisson::init_mesh_to_grid(), mfo_mdatas(), mfo_mdatav(), mfo_outs(), mfo_outv(), io::mfo_read_header(), io::mfo_read_scalar(), io::mfo_read_vector(), mfo_write_hdr(), nek_advance(), nek_solve(), outfld(), pprint_all(), readat(), setics(), vec_dsop(), and vec_dssum().
integer function numnodes ()
Definition at line 248 of file comm_mpi.F90.
References mpi_comm_size().
subroutine printheader ()
Definition at line 486 of file comm_mpi.F90.
Referenced by iniproc().