Nek5000: jl/comm.h File Reference
comm.h File Reference
Classes
struct comm
Macros
#define comm_allreduce PREFIXED_NAME(comm_allreduce)
#define comm_scan PREFIXED_NAME(comm_scan)
#define comm_dot PREFIXED_NAME(comm_dot)
#define comm_gbl_id PREFIXED_NAME(comm_gbl_id)
#define comm_gbl_np PREFIXED_NAME(comm_gbl_np)
#define comm_init_check(c, ce, np) comm_init_check_(c,ce,np,__FILE__,__LINE__)
#define comm_dup(d, s) comm_dup_(d,s,__FILE__,__LINE__)
Typedefs
typedef int comm_ext
typedef int comm_req
typedef int MPI_Fint
Functions
static void comm_init (struct comm *c, comm_ext ce)
static void comm_free (struct comm *c)
static double comm_time (void)
static void comm_barrier (const struct comm *c)
static void comm_recv (const struct comm *c, void *p, size_t n, uint src, int tag)
static void comm_send (const struct comm *c, void *p, size_t n, uint dst, int tag)
static void comm_irecv (comm_req *req, const struct comm *c, void *p, size_t n, uint src, int tag)
static void comm_isend (comm_req *req, const struct comm *c, void *p, size_t n, uint dst, int tag)
static void comm_wait (comm_req *req, int n)
double comm_dot (const struct comm *comm, double *v, double *w, uint n)
static void comm_init_check_ (struct comm *c, MPI_Fint ce, uint np, const char *file, unsigned line)
static void comm_dup_ (struct comm *d, const struct comm *s, const char *file, unsigned line)
static void comm_bcast (const struct comm *c, void *p, size_t n, uint root)
Variables
uint comm_gbl_id
uint comm_gbl_np
Macro Definition Documentation
#define comm_allreduce PREFIXED_NAME(comm_allreduce)
Definition at line 74 of file comm.h.
#define comm_dot PREFIXED_NAME(comm_dot)
Definition at line 76 of file comm.h.
#define comm_dup (d, s) comm_dup_(d,s,__FILE__,__LINE__)
Definition at line 174 of file comm.h.
Referenced by crs_setup(), crystal_init(), and gs_setup().
#define comm_gbl_id PREFIXED_NAME(comm_gbl_id)
Definition at line 80 of file comm.h.
Referenced by comm_init(), die(), scalloc(), smalloc(), srealloc(), and vdiagnostic().
#define comm_gbl_np PREFIXED_NAME(comm_gbl_np)
Definition at line 81 of file comm.h.
Referenced by comm_init().
#define comm_init_check (c, ce, np) comm_init_check_(c,ce,np,__FILE__,__LINE__)
Definition at line 161 of file comm.h.
Referenced by fcrs_setup(), fcrystal_setup(), ffindpts_setup(), and fgs_setup_pick().
#define comm_scan PREFIXED_NAME(comm_scan)
Definition at line 75 of file comm.h.
Typedef Documentation
typedef int comm_ext
Definition at line 69 of file comm.h.
typedef int comm_req
Definition at line 70 of file comm.h.
typedef int MPI_Fint
Definition at line 71 of file comm.h.
Function Documentation
static void comm_barrier (const struct comm * c) static
Definition at line 192 of file comm.h.
References comm::c.
Referenced by dry_run_time(), and main().
static void comm_bcast (const struct comm * c, void * p, size_t n, uint root) static
Definition at line 249 of file comm.h.
References comm::c.
double comm_dot (const struct comm * comm, double * v, double * w, uint n)
Definition at line 143 of file comm.c.
References comm_allreduce(), and tensor_dot.
static void comm_dup_ (struct comm * d, const struct comm * s, const char * file, unsigned line) static
Definition at line 164 of file comm.h.
References comm::c, fail(), comm::id, and comm::np.
static void comm_free (struct comm * c) static
Definition at line 176 of file comm.h.
References comm::c.
Referenced by crs_free(), crystal_free(), fcrs_setup(), gs_free(), and main().
static void comm_init (struct comm * c, comm_ext ce) static
Definition at line 133 of file comm.h.
References comm::c, comm_gbl_id, comm_gbl_np, i, comm::id, and comm::np.
Referenced by comm_init_check_(), and main().
static void comm_init_check_ (struct comm * c, MPI_Fint ce, uint np, const char * file, unsigned line) static
Definition at line 145 of file comm.h.
References comm_init(), fail(), and comm::np.
static void comm_irecv (comm_req * req, const struct comm * c, void * p, size_t n, uint src, int tag) static
Definition at line 220 of file comm.h.
References comm::c.
Referenced by cr_exec(), cr_learn(), crystal_exchange(), pw_exec_recvs(), and scan_imp().
static void comm_isend (comm_req * req, const struct comm * c, void * p, size_t n, uint dst, int tag) static
Definition at line 228 of file comm.h.
References comm::c.
Referenced by apply_QQt(), cr_exec(), cr_learn(), crystal_exchange(), pw_exec_sends(), scan_imp(), and sum().
static void comm_recv (const struct comm * c, void * p, size_t n, uint src, int tag) static
Definition at line 199 of file comm.h.
References comm::c.
Referenced by allreduce_imp(), apply_QQt(), discover_sep_ids(), discover_sep_sizes(), scan_imp(), and sum().
static void comm_send (const struct comm * c, void * p, size_t n, uint dst, int tag) static
Definition at line 212 of file comm.h.
References comm::c.
Referenced by allreduce_imp(), apply_QQt(), discover_sep_ids(), discover_sep_sizes(), scan_imp(), and sum().
static double comm_time (void) static
Definition at line 183 of file comm.h.
Referenced by dry_run_time().
static void comm_wait (comm_req * req, int n) static
Definition at line 236 of file comm.h.
Referenced by apply_QQt(), cr_exec(), cr_learn(), crystal_exchange(), pw_exec(), scan_imp(), and sum().
Variable Documentation
uint comm_gbl_id
Definition at line 14 of file comm.c.
uint comm_gbl_np
Definition at line 14 of file comm.c.