Nek5000: conduct.F90 File Reference
conduct.F90 File Reference
Functions/Subroutines
subroutine cdscal (igeom)
Solve the convection-diffusion equation for passive scalar IPSCAL.
subroutine makeuq
Fill up user defined forcing function and collocate will the mass matrix on the Gauss-Lobatto mesh.
subroutine setqvol (bql)
Set user specified volumetric forcing function (e.g. heat source).
subroutine nekuq (bql, iel)
Generate user-specified volumetric source term (temp./p.s.)
subroutine convab ()
Eulerian scheme, add convection term to forcing function at current time step.
subroutine makeabq
Sum up contributions to 3rd order Adams-Bashforth scheme.
subroutine makebdq ()
Add contributions to F from lagged BD terms.
subroutine lagscal
Keep old passive scalar field(s)
Function/Subroutine Documentation
subroutine cdscal (integer, intent(in) igeom)
Solve the convection-diffusion equation for passive scalar IPSCAL.
Definition at line 3 of file conduct.F90.
References axhelm(), bcdirsc(), bcneusc(), cvgnlps(), ctimer::dnekclock(), helmholtz::hsolve(), lagscal(), makeq(), and sethlm().
Referenced by heat().
subroutine convab ()
Eulerian scheme, add convection term to forcing function at current time step.
Definition at line 217 of file conduct.F90.
References convop().
Referenced by makeq().
subroutine lagscal ()
Keep old passive scalar field(s)
Definition at line 308 of file conduct.F90.
References copy().
Referenced by cdscal().
subroutine makeabq ()
Sum up contributions to 3rd order Adams-Bashforth scheme.
Definition at line 240 of file conduct.F90.
Referenced by makeq().
subroutine makebdq ()
Add contributions to F from lagged BD terms.
Definition at line 270 of file conduct.F90.
Referenced by makeq().
subroutine makeuq ()
Fill up user defined forcing function and collocate will the mass matrix on the Gauss-Lobatto mesh.
Definition at line 122 of file conduct.F90.
References setqvol().
Referenced by makeq_aux().
subroutine nekuq (real(dp), dimension(lx1,ly1,lz1,lelt) bql, integer iel)
Generate user-specified volumetric source term (temp./p.s.)
Definition at line 186 of file conduct.F90.
References parallel::lglel(), and nekasgn().
Referenced by setqvol().
subroutine setqvol (real(dp), dimension(lx1*ly1*lz1,lelt) bql)
Set user specified volumetric forcing function (e.g. heat source).
Definition at line 147 of file conduct.F90.
References nekuq().
Referenced by makeuq().