Nek5000: connect2.F90 File Reference
connect2.F90 File Reference
Functions/Subroutines
subroutine readat ()
Read in data from preprocessor input file (.rea)
subroutine rdparam
Read in parameters supplied by preprocessor and (eventually) echo check. .Broadcast run parameters to all processors.
subroutine genmesh
Generate local mesh elements.
subroutine rdmesh
Read number of elements. .Construct sequential element-processor partition according to number of elements and processors .Selectively read mesh (defined by element vertices, and group numbers) on each processor.
subroutine rdcurve
.Read curve side data .Disperse curve side data to all processors according to sequential partition scheme
subroutine rdbdry
Read Boundary Conditions (and connectivity data). .Disperse boundary condition data to all processors according to sequential partition scheme.
subroutine rdicdf
Read Initial Conditions / Drive Force. Broadcast ICFILE to all processors.
subroutine rdmatp
.Read materials property data .Disperse material properties to all processors according to sequential partition scheme
subroutine rdhist
.Read history data .Broadcast to all processors
subroutine rdout
Read output specs, broadcast to all processors.
subroutine rdobj
Read objects, Broadcast to all processors.
subroutine vrdsmsh ()
Verify that mesh and dssum are properly defined by performing a direct stiffness operation on the X,Y and Z coordinates. Note that periodic faces are not checked here.
subroutine chk_nel
Function/Subroutine Documentation
subroutine chk_nel ()
Definition at line 1827 of file connect2.F90.
References exitt(), and np.
Referenced by readat().
subroutine genmesh ()
Generate local mesh elements.
Populate xc, yc, zc with element corner positions Populate cbc, bc with element boundary conditions
Note
Can't handle curves (zeros out)
Definition at line 731 of file connect2.F90.
References bcast(), blank(), parallel::gllel(), parallel::gllnid(), and parallel::lglel().
Referenced by readat().
subroutine rdbdry ()
Read Boundary Conditions (and connectivity data). .Disperse boundary condition data to all processors according to sequential partition scheme.
Definition at line 1057 of file connect2.F90.
References blank(), string::capit(), exitt(), parallel::gllel(), parallel::gllnid(), and string::indx1().
Referenced by readat().
subroutine rdcurve ()
.Read curve side data .Disperse curve side data to all processors according to sequential partition scheme
Definition at line 964 of file connect2.F90.
References blank(), exitt(), parallel::gllel(), and parallel::gllnid().
Referenced by readat().
subroutine rdhist ()
.Read history data .Broadcast to all processors
Definition at line 1362 of file connect2.F90.
References bcast(), blank(), err_chk(), and exitt().
Referenced by readat().
subroutine rdicdf ()
Read Initial Conditions / Drive Force. Broadcast ICFILE to all processors.
Definition at line 1243 of file connect2.F90.
References bcast(), blank(), string::capit(), exitti(), string::ifgtil(), and string::indx1().
Referenced by readat().
subroutine rdmatp ()
.Read materials property data .Disperse material properties to all processors according to sequential partition scheme
Definition at line 1312 of file connect2.F90.
References bcast(), and exitt().
Referenced by readat().
subroutine rdmesh ()
Read number of elements. .Construct sequential element-processor partition according to number of elements and processors .Selectively read mesh (defined by element vertices, and group numbers) on each processor.
Definition at line 878 of file connect2.F90.
References exitt(), parallel::gllel(), and parallel::gllnid().
Referenced by readat().
subroutine rdobj ()
Read objects, Broadcast to all processors.
Definition at line 1520 of file connect2.F90.
References bcast(), and err_chk().
Referenced by readat().
subroutine rdout ()
Read output specs, broadcast to all processors.
Definition at line 1436 of file connect2.F90.
References bcast(), exitt(), exitti(), and lfalse().
Referenced by readat().
subroutine rdparam ()
Read in parameters supplied by preprocessor and (eventually) echo check. .Broadcast run parameters to all processors.
Definition at line 232 of file connect2.F90.
References bcast(), string::capit(), exitt(), exitti(), and string::indx1().
Referenced by readat().
subroutine readat ()
Read in data from preprocessor input file (.rea)
Definition at line 3 of file connect2.F90.
References bcast(), chk_nel(), string::cscan(), ctimer::dnekclock(), exitt(), exitti(), genmesh(), mapelpr(), nekgsync(), np, rdbdry(), rdcurve(), rdhist(), rdicdf(), rdmatp(), rdmesh(), rdobj(), rdout(), and rdparam().
Referenced by nek_init().
subroutine vrdsmsh ()
Verify that mesh and dssum are properly defined by performing a direct stiffness operation on the X,Y and Z coordinates. Note that periodic faces are not checked here.
Todo:
clean up ta,tb,qmask
Definition at line 1578 of file connect2.F90.
References copy(), dsop(), dssum(), exitt(), facev(), gop(), and parallel::lglel().
Referenced by nek_init().