Nek5000: convect.F90 File Reference
convect.F90 File Reference
Macros
#define INLINE_INTP
Functions/Subroutines
subroutine setup_convect (igeom)
subroutine convect_new (bdu, u, ifuf, cx, cy, cz, ifcf)
Compute dealiased form: J^T Bf *JC .grad Ju w/ correct Jacobians.
subroutine set_convect_new (cr, cs, ct, ux, uy, uz)
Put vxd,vyd,vzd into rst form on fine mesh For rst form, see eq. (4.8.5) in Deville, Fischer, Mund (2002).
Macro Definition Documentation
#define INLINE_INTP
Function/Subroutine Documentation
subroutine convect_new (real(dp), dimension(*) bdu, real(dp), dimension(*) u, logical ifuf, real(dp), dimension(*) cx, real(dp), dimension(*) cy, real(dp), dimension(*) cz, logical ifcf)
Compute dealiased form: J^T Bf *JC .grad Ju w/ correct Jacobians.
Definition at line 50 of file convect.F90.
References copy(), ctimer::dnekclock(), interp::get_dgl_ptr(), interp::get_int_ptr(), local_grad3(), and specmpn().
Referenced by convop().
subroutine set_convect_new (real(dp), dimension(ltd,*) cr, real(dp), dimension(ltd,*) cs, real(dp), dimension(ltd,*) ct, real(dp), dimension(lxy,*) ux, real(dp), dimension(lxy,*) uy, real(dp), dimension(lxy,*) uz)
Put vxd,vyd,vzd into rst form on fine mesh For rst form, see eq. (4.8.5) in Deville, Fischer, Mund (2002).
Definition at line 175 of file convect.F90.
References ctimer::dnekclock(), interp::get_int_ptr(), set_dealias_rx(), and specmpn().
Referenced by setup_convect().
subroutine setup_convect (integer, intent(in) igeom)
Definition at line 11 of file convect.F90.
References exitti(), and set_convect_new().
Referenced by nek_advance(), restart_driver(), and setics().