Nek5000: jl/crs.h File Reference
crs.h File Reference
Macros
#define crs_setup PREFIXED_NAME(crs_setup)
#define crs_solve PREFIXED_NAME(crs_solve)
#define crs_stats PREFIXED_NAME(crs_stats)
#define crs_free PREFIXED_NAME(crs_free)
Functions
struct crs_data * crs_setup (uint n, const ulong *id, uint nz, const uint *Ai, const uint *Aj, const double *A, uint null_space, const struct comm *comm)
void crs_solve (double *x, struct crs_data *data, double *b)
void crs_stats (struct crs_data *data)
void crs_free (struct crs_data *data)
Macro Definition Documentation
#define crs_free PREFIXED_NAME(crs_free)
Definition at line 11 of file crs.h.
Referenced by main(), and test().
#define crs_setup PREFIXED_NAME(crs_setup)
Definition at line 8 of file crs.h.
Referenced by main(), set_up_h1_crs(), and test().
#define crs_solve PREFIXED_NAME(crs_solve)
Definition at line 9 of file crs.h.
Referenced by hsmg_routines::hsmg_coarse_solve(), main(), and test().
#define crs_stats PREFIXED_NAME(crs_stats)
Definition at line 10 of file crs.h.
Referenced by main(), nek_end(), and test().
Function Documentation
void crs_free (struct crs_data * data)
struct crs_data* crs_setup (uint n, const ulong * id, uint nz, const uint * Ai, const uint * Aj, const double * A, uint null_space, const struct comm * comm)
Definition at line 710 of file xxt.c.
References csr_mat::A, xxt::A_sl, csr_mat::Aj, csr_mat::Arp, array_free, buffer_free, buffer_init, xxt::cn, xxt::combuf, xxt::comm, comm_dup, dof::count, discover_dofs(), discover_sep_ids(), discover_sep_sizes(), xxt::fac_A_ll, i, xxt::ln, locate_proc(), csr_mat::n, xxt::null_space, orthogonalize(), xxt::perm_u2c, array::ptr, separate_matrix(), xxt::share_weight, sint, xxt::sn, sparse_cholesky_factor, sum(), tmalloc, uint, xxt::vc, xxt::vl, xxt::vx, and xxt::xn.
void crs_solve (double * x, struct crs_data * data, double * b)
void crs_stats (struct crs_data * data)