Nek5000: jl/crystal.h File Reference
crystal.h File Reference
Classes
struct crystal
Macros
#define crystal_init PREFIXED_NAME(crystal_init)
#define crystal_free PREFIXED_NAME(crystal_free)
#define crystal_router PREFIXED_NAME(crystal_router)
Functions
void crystal_init (struct crystal *cr, const struct comm *comm)
void crystal_free (struct crystal *cr)
void crystal_router (struct crystal *cr)
Macro Definition Documentation
#define crystal_free PREFIXED_NAME(crystal_free)
Definition at line 9 of file crystal.h.
#define crystal_init PREFIXED_NAME(crystal_init)
Definition at line 8 of file crystal.h.
#define crystal_router PREFIXED_NAME(crystal_router)
Definition at line 10 of file crystal.h.
Function Documentation
void crystal_free (struct crystal * cr)
Definition at line 62 of file crystal.c.
References buffer_free, crystal::comm, comm_free(), crystal::data, and crystal::work.
void crystal_init (struct crystal * cr, const struct comm * comm)
Definition at line 55 of file crystal.c.
References buffer_init, crystal::comm, comm_dup, crystal::data, and crystal::work.
void crystal_router (struct crystal * cr)
Definition at line 124 of file crystal.c.
References crystal::comm, crystal_exchange(), crystal_move(), comm::id, n, comm::np, and uint.