Nek5000: drive1.F90 File Reference
drive1.F90 File Reference
top-level drivers for initialization, stepping, and cleanup
Functions/Subroutines
subroutine nek_init (intracomm)
initialize nek
subroutine nek_solve
integrate the governing equations in time
subroutine nek_advance
take a single time-step
subroutine nek_end
perform any end-of-run reporting
subroutine nek__multi_advance (kstep, msteps)
take a chunk of time-steps
Detailed Description
top-level drivers for initialization, stepping, and cleanup
Contains: nek_init, nek_solve, nek_advance, nek_end
Definition in file drive1.F90.
Function/Subroutine Documentation
subroutine nek__multi_advance (integer, intent(in) kstep, integer, intent(in) msteps)
take a chunk of time-steps
Calls nek_advance in a loop
Definition at line 365 of file drive1.F90.
References nek_advance().
Referenced by nek_solve().
subroutine nek_advance ()
take a single time-step
Includes the primary Pn/Pn vs Pn/Pn-2 branch
Definition at line 284 of file drive1.F90.
References comment(), fluid(), geneig(), gengeom(), heat(), nekgsync(), q_filter(), setprop(), setsolv(), settime(), setup_convect(), and userchk_set_xfer().
Referenced by nek__multi_advance().
subroutine nek_end ()
perform any end-of-run reporting
Definition at line 350 of file drive1.F90.
References crs_stats, and runstat().
Referenced by nekton().
subroutine nek_init (integer, intent(inout) intracomm)
initialize nek
This includes reading the input files
Definition at line 9 of file drive1.F90.
References bcmask(), comment(), ctimer::dnekclock(), ctimer::dnekclock_sync(), dofcnt(), echopar(), estrat(), files(), geneig(), gengeom(), genwz(), geom_reset(), get_session_info(), dealias::init_dealias(), domain::init_domain(), dxyz::init_dxyz(), esolv::init_esolv(), fdmh1::init_fdmh1(), geom::init_geom(), hsmg::init_hsmg(), input::init_input(), ixyz::init_ixyz(), mesh::init_mesh(), mvgeom::init_mvgeom(), parallel::init_parallel(), scratch::init_scratch(), semhat::init_semhat(), soln::init_soln(), topol::init_topol(), turbo::init_turbo(), zper::init_zper(), initdat(), initdim(), io_init(), opcount(), readat(), set_overlap(), setics(), setlog(), setprop(), setup_topo(), setvar(), time00(), and vrdsmsh().
Referenced by nekton().
subroutine nek_solve ()
integrate the governing equations in time
This routine includes the outer-most time loop
Definition at line 219 of file drive1.F90.
References comment(), nek__multi_advance(), nek_comm_settings, nek_comm_startstat, nekgsync(), and prepost().
Referenced by nekton().