Nek5000: drive2.F90 File Reference
drive2.F90 File Reference
second level drivers called from drive1.F90
Functions/Subroutines
subroutine initdim
Transfer array dimensions to common.
subroutine initdat
Initialize and set default values.
subroutine comment
No need to comment !!
subroutine setvar
Initialize variables.
subroutine echopar
Echo the nonzero parameters from the readfile to the logfile.
subroutine gengeom (igeom)
Generate geometry data.
subroutine files
Defines machine specific input and output file names.
subroutine settime
setup time-stepping
subroutine geneig (igeom)
Compute eigenvalues.
subroutine fluid (igeom)
Driver for solving the incompressible Navier-Stokes equations.
subroutine heat (igeom)
Driver for temperature or passive scalar.
subroutine time00
zero the ctimer
subroutine runstat
print run statistics from ctimer
subroutine pprint_all (s, n_in, io)
pretty-print from runstat
subroutine opcount (ICALL)
init opcounter
subroutine dofcnt
count degrees of freedom
subroutine print_times (label, num_calls, time, total_time, cum_time)
subroutine print_flops (label, flops, mops, time)
Detailed Description
second level drivers called from drive1.F90
Definition in file drive2.F90.
Function/Subroutine Documentation
subroutine comment ()
No need to comment !!
Definition at line 94 of file drive2.F90.
References ctimer::dnekclock().
Referenced by nek_advance(), nek_init(), and nek_solve().
subroutine dofcnt ()
count degrees of freedom
Definition at line 1415 of file drive2.F90.
Referenced by nek_init().
subroutine echopar ()
Echo the nonzero parameters from the readfile to the logfile.
Definition at line 320 of file drive2.F90.
References blank(), chcopy(), exitt(), string::ltrunc(), and set_bytesw_write.
Referenced by nek_init().
subroutine files ()
Defines machine specific input and output file names.
Definition at line 484 of file drive2.F90.
References blank(), chcopy(), string::indx1(), and string::ltrunc().
Referenced by nek_init().
subroutine fluid (integer, intent(inout) igeom)
Driver for solving the incompressible Navier-Stokes equations.
Current version: (1) Velocity/stress formulation. (2) Constant/variable properties. (3) Implicit/explicit time stepping. (4) Automatic setting of tolerances . (5) Lagrangian/"Eulerian"(operator splitting) modes
Definition at line 732 of file drive2.F90.
References ctimer::dnekclock(), plan4(), settolv(), and unorm().
Referenced by nek_advance().
subroutine geneig (integer, intent(in) igeom)
Compute eigenvalues.
Used for automatic setting of tolerances and to find critical time step for explicit mode. Currently eigenvalues are computed only for the velocity mesh.
Definition at line 674 of file drive2.F90.
References eigenv(), and esteig().
Referenced by nek_advance(), and nek_init().
subroutine gengeom (integer, intent(in) igeom)
Generate geometry data.
Definition at line 412 of file drive2.F90.
References dssum(), gencoor(), geom1(), geom2(), lagmass(), setdef(), setinvm(), sfastax(), and volume().
Referenced by nek_advance(), and nek_init().
subroutine heat (integer, intent(inout) igeom)
Driver for temperature or passive scalar.
Current version: (1) Varaiable properties. (2) Implicit time stepping. (3) User specified tolerance for the Helmholtz solver (not based on eigenvalues). (4) A passive scalar can be defined on either the temperatur or the velocity mesh. (5) A passive scalar has its own multiplicity (B.C.).
Definition at line 812 of file drive2.F90.
References cdscal(), ctimer::dnekclock(), settolt(), and unorm().
Referenced by nek_advance().
subroutine initdat ()
Initialize and set default values.
Definition at line 39 of file drive2.F90.
References blank().
Referenced by nek_init().
subroutine initdim ()
Transfer array dimensions to common.
Definition at line 7 of file drive2.F90.
Referenced by nek_init().
subroutine opcount (integer, intent(in) ICALL)
init opcounter
Definition at line 1357 of file drive2.F90.
References crecv(), csend(), gop(), iswap(), np, and sort().
Referenced by nek_init().
subroutine pprint_all (character(n_in), intent(in) s, integer, intent(in) n_in, integer, intent(in) io)
pretty-print from runstat
Definition at line 1311 of file drive2.F90.
References blank(), crecv(), csend(), string::ltrunc(), nekgsync(), and np.
Referenced by runstat().
subroutine print_flops (character(*) label, integer(i8) flops, integer(i8) mops, real(dp) time)
Definition at line 1474 of file drive2.F90.
Referenced by runstat().
subroutine print_times (character(*), intent(in) label, integer, intent(in) num_calls, real(dp), intent(in) time, real(dp), intent(in) total_time, real(dp), intent(inout) cum_time)
Definition at line 1460 of file drive2.F90.
Referenced by runstat().
subroutine runstat ()
print run statistics from ctimer
Definition at line 943 of file drive2.F90.
References blank(), ctimer::dnekclock(), gop(), nek_comm_getstat, np, pprint_all(), print_flops(), print_times(), and ctimer::sum_flops().
Referenced by nek_end().
subroutine settime ()
setup time-stepping
Store old time steps and compute new time step, time and timef. Set time-dependent coefficients in time-stepping schemes.
Definition at line 612 of file drive2.F90.
References setabbd(), setbd(), setdt(), and setordbd().
Referenced by nek_advance().
subroutine setvar ()
Initialize variables.
Definition at line 148 of file drive2.F90.
References exitt(), and setchar().
Referenced by nek_init().
subroutine time00 ()
zero the ctimer
Definition at line 872 of file drive2.F90.
Referenced by nek_init().