Nek5000: eigsolv.F90 File Reference
eigsolv.F90 File Reference
routines for estimating and calculating eigenvalues
Functions/Subroutines
subroutine esteig
Estimate eigenvalues.
subroutine eigenv
Compute the following eigenvalues:. EIGAA = minimum eigenvalue of the matrix A (=Laplacian) EIGAE = minimum eigenvalue of the matrix E (=DB-1DT) EIGAS = minimum eigenvalue of the matrix S (=DA-1DT) EIGAST = minimum eigenvalue of the matrix St (=D(A+B/dt)-1DT EIGGA = maximum eigenvalue of the matrix A EIGGS = maximum eigenvalue of the matrix S EIGGE = maximum eigenvalue of the matrix E EIGGST = maximum eigenvalue of the matrix St Method : Power method/Inverse iteration & Rayleigh quotient wo shift.
subroutine gammam1 (GAMMA, MASK, MULT, H1, H2, ISD)
Compute maximum eigenvalue of the discrete Helmholtz operator.
subroutine startx1 (X1, Y1, MASK, MULT, NEL)
Compute startvector for finding an eigenvalue on mesh 1. Normalization: XT*B*X = 1.
Detailed Description
routines for estimating and calculating eigenvalues
Definition in file eigsolv.F90.
Function/Subroutine Documentation
subroutine eigenv ()
Compute the following eigenvalues:. EIGAA = minimum eigenvalue of the matrix A (=Laplacian) EIGAE = minimum eigenvalue of the matrix E (=DB-1DT) EIGAS = minimum eigenvalue of the matrix S (=DA-1DT) EIGAST = minimum eigenvalue of the matrix St (=D(A+B/dt)-1DT EIGGA = maximum eigenvalue of the matrix A EIGGS = maximum eigenvalue of the matrix S EIGGE = maximum eigenvalue of the matrix E EIGGST = maximum eigenvalue of the matrix St Method : Power method/Inverse iteration & Rayleigh quotient wo shift.
Definition at line 107 of file eigsolv.F90.
References gammam1(), and sethlm().
Referenced by geneig().
subroutine esteig ()
Estimate eigenvalues.
Definition at line 9 of file eigsolv.F90.
Referenced by geneig().
subroutine gammam1 (real(dp) GAMMA, real(dp), dimension (lx1,ly1,lz1,*) MASK, real(dp), dimension (lx1,ly1,lz1,*) MULT, real(dp), dimension (lx1,ly1,lz1,*) H1, real(dp), dimension (lx1,ly1,lz1,*) H2, integer ISD)
Compute maximum eigenvalue of the discrete Helmholtz operator.
Definition at line 232 of file eigsolv.F90.
References axhelm(), dssum(), and startx1().
Referenced by eigenv().
subroutine startx1 (real(dp), dimension (lx1,ly1,lz1,nel), intent(out) X1, real(dp), dimension (lx1,ly1,lz1,nel) Y1, real(dp), dimension (lx1,ly1,lz1,nel), intent(in) MASK, real(dp), dimension (lx1,ly1,lz1,nel), intent(in) MULT, integer NEL)
Compute startvector for finding an eigenvalue on mesh 1. Normalization: XT*B*X = 1.
Definition at line 295 of file eigsolv.F90.
References copy(), dssum(), and rand_fld_h1().
Referenced by gammam1().