Nek5000: jl/fail.c File Reference
fail.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include "name.h"
#include "fail.h"
#include "types.h"
#include "comm.h"
Macros
#define nek_exitt FORTRAN_UNPREFIXED(exitt,EXITT)
Functions
void die (int status)
void vdiagnostic (const char *prefix, const char *file, unsigned line, const char *fmt, va_list ap)
void diagnostic (const char *prefix, const char *file, unsigned line, const char *fmt,...)
void vfail (int status, const char *file, unsigned line, const char *fmt, va_list ap)
void fail (int status, const char *file, unsigned line, const char *fmt,...)
Macro Definition Documentation
#define nek_exitt FORTRAN_UNPREFIXED(exitt,EXITT)
Definition at line 10 of file fail.c.
Referenced by die().
Function Documentation
void diagnostic (const char * prefix, const char * file, unsigned line, const char * fmt, ...)
Definition at line 32 of file fail.c.
References vdiagnostic().
Referenced by main().
void die (int status)
Definition at line 11 of file fail.c.
References comm_gbl_id, and nek_exitt.
Referenced by vfail().
void fail (int status, const char * file, unsigned line, const char * fmt, ...)
Definition at line 47 of file fail.c.
References vfail().
Referenced by comm_dup_(), comm_init_check_(), fcrystal_tuple_sort(), ffindpts_setup(), fgs_check_handle(), fgs_check_parms(), main(), scalloc(), smalloc(), sortv(), and srealloc().
void vdiagnostic (const char * prefix, const char * file, unsigned line, const char * fmt, va_list ap)
Definition at line 20 of file fail.c.
References findpts_local_data::buf, comm_gbl_id, i, and n.
Referenced by diagnostic(), and vfail().
void vfail (int status, const char * file, unsigned line, const char * fmt, va_list ap)
Definition at line 40 of file fail.c.
References die(), and vdiagnostic().
Referenced by fail().