Nek5000: jl/findpts_local.c File Reference
findpts_local.c File Reference
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "c99.h"
#include "types.h"
#include "name.h"
#include "fail.h"
#include "mem.h"
#include "obbox.h"
#include "poly.h"
#include "sort.h"
#include "sarray_sort.h"
#include "findpts_el.h"
#include "findpts_local_imp.h"
Classes
struct uint_range
struct index_el
Macros
#define CODE_INTERNAL 0
#define CODE_BORDER 1
#define CODE_NOT_FOUND 2
#define D 2
#define WHEN_3D(a)
#define D 3
#define WHEN_3D(a) a
Functions
static struct dbl_range dbl_range_merge (struct dbl_range a, struct dbl_range b)
static sint ifloor (double x)
static sint iceil (double x)
static uint hash_index_aux (double low, double fac, uint n, double x)
Macro Definition Documentation
#define CODE_BORDER 1
Definition at line 39 of file findpts_local.c.
#define CODE_INTERNAL 0
Definition at line 38 of file findpts_local.c.
#define CODE_NOT_FOUND 2
Definition at line 40 of file findpts_local.c.
#define D 2
Definition at line 48 of file findpts_local.c.
#define D 3
Definition at line 48 of file findpts_local.c.
#define WHEN_3D (a)
Definition at line 49 of file findpts_local.c.
#define WHEN_3D (a) a
Definition at line 49 of file findpts_local.c.
Function Documentation
static struct dbl_range dbl_range_merge (struct dbl_range a, struct dbl_range b) static
Definition at line 21 of file findpts_local.c.
References dbl_range::max, and dbl_range::min.
Referenced by hash_bb().
static uint hash_index_aux (double low, double fac, uint n, double x) static
Definition at line 32 of file findpts_local.c.
References i, ifloor(), sint, and uint.
static sint iceil (double x) static
Definition at line 30 of file findpts_local.c.
Referenced by hash_range().
static sint ifloor (double x) static
Definition at line 29 of file findpts_local.c.
Referenced by hash_index_aux(), and hash_range().