Nek5000: jl/findpts_el.h File Reference
findpts_el.h File Reference
Classes
struct findpts_el_pt_2
struct findpts_el_gedge_2
struct findpts_el_gpt_2
struct findpts_el_data_2
struct findpts_el_pt_3
struct findpts_el_gface_3
struct findpts_el_gedge_3
struct findpts_el_gpt_3
struct findpts_el_data_3
Macros
#define findpts_el_setup_2 PREFIXED_NAME(findpts_el_setup_2)
#define findpts_el_free_2 PREFIXED_NAME(findpts_el_free_2)
#define findpts_el_2 PREFIXED_NAME(findpts_el_2)
#define findpts_el_eval_2 PREFIXED_NAME(findpts_el_eval_2)
#define findpts_el_setup_3 PREFIXED_NAME(findpts_el_setup_3)
#define findpts_el_free_3 PREFIXED_NAME(findpts_el_free_3)
#define findpts_el_3 PREFIXED_NAME(findpts_el_3)
#define findpts_el_eval_3 PREFIXED_NAME(findpts_el_eval_3)
Functions
void findpts_el_setup_2 (struct findpts_el_data_2 *const fd, const unsigned n[2], const unsigned npt_max)
void findpts_el_free_2 (struct findpts_el_data_2 *const fd)
void findpts_el_2 (struct findpts_el_data_2 *fd, unsigned npt, const double tol)
void findpts_el_eval_2 (double *const out_base, const unsigned out_stride, const double *const r_base, const unsigned r_stride, const unsigned pn, const double *const in, struct findpts_el_data_2 *const fd)
static void findpts_el_start_2 (struct findpts_el_data_2 *const fd, const double *const x[2])
static struct findpts_el_pt_2 * findpts_el_points_2 (struct findpts_el_data_2 *const fd)
void findpts_el_setup_3 (struct findpts_el_data_3 *const fd, const unsigned n[3], const unsigned npt_max)
void findpts_el_free_3 (struct findpts_el_data_3 *const fd)
void findpts_el_3 (struct findpts_el_data_3 *const fd, const unsigned npt, const double tol)
void findpts_el_eval_3 (double *const out_base, const unsigned out_stride, const double *const r_base, const unsigned r_stride, const unsigned pn, const double *const in, struct findpts_el_data_3 *const fd)
static void findpts_el_start_3 (struct findpts_el_data_3 *const fd, const double *const x[3])
static struct findpts_el_pt_3 * findpts_el_points_3 (struct findpts_el_data_3 *const fd)
Macro Definition Documentation
#define findpts_el_2 PREFIXED_NAME(findpts_el_2)
Definition at line 10 of file findpts_el.h.
Referenced by main().
#define findpts_el_3 PREFIXED_NAME(findpts_el_3)
Definition at line 65 of file findpts_el.h.
Referenced by main().
#define findpts_el_eval_2 PREFIXED_NAME(findpts_el_eval_2)
Definition at line 11 of file findpts_el.h.
#define findpts_el_eval_3 PREFIXED_NAME(findpts_el_eval_3)
Definition at line 66 of file findpts_el.h.
#define findpts_el_free_2 PREFIXED_NAME(findpts_el_free_2)
Definition at line 9 of file findpts_el.h.
Referenced by main().
#define findpts_el_free_3 PREFIXED_NAME(findpts_el_free_3)
Definition at line 64 of file findpts_el.h.
Referenced by main().
#define findpts_el_setup_2 PREFIXED_NAME(findpts_el_setup_2)
Definition at line 8 of file findpts_el.h.
Referenced by main().
#define findpts_el_setup_3 PREFIXED_NAME(findpts_el_setup_3)
Definition at line 63 of file findpts_el.h.
Referenced by main().
Function Documentation
void findpts_el_2 (struct findpts_el_data_2 * fd, unsigned npt, const double tol)
Definition at line 734 of file findpts_el_2.c.
References findpt_area(), findpt_edge(), findpt_pt(), FLAG_MASK, findpts_el_pt_2::flags, i, findpts_el_pt_2::index, num_constrained(), p, findpts_el_data_2::p, pt_flags_to_bin(), pt_flags_to_bin_noC(), findpts_el_pt_2::r, seed(), sum(), and findpts_el_pt_2::x.
void findpts_el_3 (struct findpts_el_data_3 *const fd, const unsigned npt, const double tol)
Definition at line 1211 of file findpts_el_3.c.
References findpt_edge(), findpt_face(), findpt_pt(), findpt_vol(), FLAG_MASK, findpts_el_pt_3::flags, i, findpts_el_pt_3::index, n, findpts_el_data_3::n, num_constrained(), p, findpts_el_data_3::p, pt_flags_to_bin(), pt_flags_to_bin_noC(), findpts_el_pt_3::r, seed(), sum(), findpts_el_pt_3::x, and findpts_el_data_3::x.
void findpts_el_eval_2 (double *const out_base, const unsigned out_stride, const double *const r_base, const unsigned r_stride, const unsigned pn, const double *const in, struct findpts_el_data_2 *const fd)
Definition at line 798 of file findpts_el_2.c.
References i, findpts_el_data_2::lag, findpts_el_data_2::lag_data, findpts_el_data_2::n, nr, ns, out, findpts_el_pt_2::r, tensor_i1(), tensor_mxm(), and findpts_el_data_2::work.
void findpts_el_eval_3 (double *const out_base, const unsigned out_stride, const double *const r_base, const unsigned r_stride, const unsigned pn, const double *const in, struct findpts_el_data_3 *const fd)
Definition at line 1294 of file findpts_el_3.c.
References i, findpts_el_data_3::lag, findpts_el_data_3::lag_data, findpts_el_data_3::n, nr, ns, out, findpts_el_pt_3::r, tensor_i2(), tensor_mxm(), and findpts_el_data_3::work.
void findpts_el_free_2 (struct findpts_el_data_2 *const fd)
Definition at line 194 of file findpts_el_2.c.
References findpts_el_data_2::p, and findpts_el_data_2::z.
void findpts_el_free_3 (struct findpts_el_data_3 *const fd)
Definition at line 283 of file findpts_el_3.c.
References findpts_el_data_3::p, and findpts_el_data_3::z.
static struct findpts_el_pt_2* findpts_el_points_2 (struct findpts_el_data_2 *const fd) static
Definition at line 57 of file findpts_el.h.
References findpts_el_data_2::p.
Referenced by main().
static struct findpts_el_pt_3* findpts_el_points_3 (struct findpts_el_data_3 *const fd) static
Definition at line 116 of file findpts_el.h.
References findpts_el_data_3::p.
Referenced by main().
void findpts_el_setup_2 (struct findpts_el_data_2 *const fd, const unsigned n[2], const unsigned npt_max)
Definition at line 143 of file findpts_el_2.c.
References findpts_el_gedge_2::dxdn, findpts_el_data_2::edge, gll_lag_setup, gll_lag_size, i, findpts_el_data_2::lag, findpts_el_data_2::lag_data, lobatto_nodes, findpts_el_data_2::n, n, findpts_el_data_2::npt_max, nr, ns, findpts_el_data_2::p, findpts_el_data_2::side_init, findpts_el_data_2::sides, tmalloc, findpts_el_data_2::work, work_size(), findpts_el_data_2::wtend, findpts_el_gedge_2::x, and findpts_el_data_2::z.
void findpts_el_setup_3 (struct findpts_el_data_3 *const fd, const unsigned n[3], const unsigned npt_max)
Definition at line 202 of file findpts_el_3.c.
References findpts_el_gface_3::dxdn, findpts_el_data_3::face, gll_lag_setup, gll_lag_size, i, findpts_el_data_3::lag, findpts_el_data_3::lag_data, lobatto_nodes, n, findpts_el_data_3::n, findpts_el_data_3::npt_max, nr, ns, findpts_el_data_3::p, SET_EDGE, SET_FACE, findpts_el_data_3::side_init, findpts_el_data_3::sides, tmalloc, findpts_el_data_3::work, work_size(), findpts_el_data_3::wtend, findpts_el_gface_3::x, and findpts_el_data_3::z.
static void findpts_el_start_2 (struct findpts_el_data_2 *const fd, const double *const x[2]) static
Definition at line 51 of file findpts_el.h.
References findpts_el_data_2::side_init, and findpts_el_data_2::x.
Referenced by main().
static void findpts_el_start_3 (struct findpts_el_data_3 *const fd, const double *const x[3]) static
Definition at line 110 of file findpts_el.h.
References findpts_el_data_3::side_init, and findpts_el_data_3::x.
Referenced by main().