Nek5000: jl/findpts_local.h File Reference
findpts_local.h File Reference
Classes
struct findpts_local_hash_data_2
struct findpts_local_data_2
struct findpts_local_hash_data_3
struct findpts_local_data_3
Macros
#define findpts_local_setup_2 PREFIXED_NAME(findpts_local_setup_2)
#define findpts_local_free_2 PREFIXED_NAME(findpts_local_free_2)
#define findpts_local_2 PREFIXED_NAME(findpts_local_2)
#define findpts_local_eval_2 PREFIXED_NAME(findpts_local_eval_2)
#define findpts_local_setup_3 PREFIXED_NAME(findpts_local_setup_3)
#define findpts_local_free_3 PREFIXED_NAME(findpts_local_free_3)
#define findpts_local_3 PREFIXED_NAME(findpts_local_3)
#define findpts_local_eval_3 PREFIXED_NAME(findpts_local_eval_3)
Functions
void findpts_local_setup_2 (struct findpts_local_data_2 *const fd, const double *const elx[2], const unsigned n[2], const uint nel, const unsigned m[2], const double bbox_tol, const uint max_hash_size, const unsigned npt_max, const double newt_tol)
void findpts_local_free_2 (struct findpts_local_data_2 *const fd)
void findpts_local_2 (uint *const code_base, const unsigned code_stride, uint *const el_base, const unsigned el_stride, double *const r_base, const unsigned r_stride, double *const dist2_base, const unsigned dist2_stride, const double *const x_base[2], const unsigned x_stride[2], const uint npt, struct findpts_local_data_2 *const fd, buffer *buf)
void findpts_local_eval_2 (double *const out_base, const unsigned out_stride, const uint *const el_base, const unsigned el_stride, const double *const r_base, const unsigned r_stride, const uint npt, const double *const in, struct findpts_local_data_2 *const fd)
void findpts_local_setup_3 (struct findpts_local_data_3 *const fd, const double *const elx[3], const unsigned n[3], const uint nel, const unsigned m[3], const double bbox_tol, const uint max_hash_size, const unsigned npt_max, const double newt_tol)
void findpts_local_free_3 (struct findpts_local_data_3 *const fd)
void findpts_local_3 (uint *const code_base, const unsigned code_stride, uint *const el_base, const unsigned el_stride, double *const r_base, const unsigned r_stride, double *const dist2_base, const unsigned dist2_stride, const double *const x_base[3], const unsigned x_stride[3], const uint npt, struct findpts_local_data_3 *const fd, buffer *buf)
void findpts_local_eval_3 (double *const out_base, const unsigned out_stride, const uint *const el_base, const unsigned el_stride, const double *const r_base, const unsigned r_stride, const uint npt, const double *const in, struct findpts_local_data_3 *const fd)
Macro Definition Documentation
#define findpts_local_2 PREFIXED_NAME(findpts_local_2)
Definition at line 10 of file findpts_local.h.
#define findpts_local_3 PREFIXED_NAME(findpts_local_3)
Definition at line 54 of file findpts_local.h.
#define findpts_local_eval_2 PREFIXED_NAME(findpts_local_eval_2)
Definition at line 11 of file findpts_local.h.
#define findpts_local_eval_3 PREFIXED_NAME(findpts_local_eval_3)
Definition at line 55 of file findpts_local.h.
#define findpts_local_free_2 PREFIXED_NAME(findpts_local_free_2)
Definition at line 9 of file findpts_local.h.
#define findpts_local_free_3 PREFIXED_NAME(findpts_local_free_3)
Definition at line 53 of file findpts_local.h.
#define findpts_local_setup_2 PREFIXED_NAME(findpts_local_setup_2)
Definition at line 8 of file findpts_local.h.
#define findpts_local_setup_3 PREFIXED_NAME(findpts_local_setup_3)
Definition at line 52 of file findpts_local.h.
Function Documentation
void findpts_local_2 (uint *const code_base, const unsigned code_stride, uint *const el_base, const unsigned el_stride, double *const r_base, const unsigned r_stride, double *const dist2_base, const unsigned dist2_stride, const double *const x_base[2], const unsigned x_stride[2], const uint npt, struct findpts_local_data_2 *const fd, buffer * buf)
Referenced by findpts_local().
void findpts_local_3 (uint *const code_base, const unsigned code_stride, uint *const el_base, const unsigned el_stride, double *const r_base, const unsigned r_stride, double *const dist2_base, const unsigned dist2_stride, const double *const x_base[3], const unsigned x_stride[3], const uint npt, struct findpts_local_data_3 *const fd, buffer * buf)
Referenced by findpts_local().
void findpts_local_eval_2 (double *const out_base, const unsigned out_stride, const uint *const el_base, const unsigned el_stride, const double *const r_base, const unsigned r_stride, const uint npt, const double *const in, struct findpts_local_data_2 *const fd)
Referenced by findpts_local_eval().
void findpts_local_eval_3 (double *const out_base, const unsigned out_stride, const uint *const el_base, const unsigned el_stride, const double *const r_base, const unsigned r_stride, const uint npt, const double *const in, struct findpts_local_data_3 *const fd)
Referenced by findpts_local_eval().
void findpts_local_free_2 (struct findpts_local_data_2 *const fd)
Referenced by findpts_local_free().
void findpts_local_free_3 (struct findpts_local_data_3 *const fd)
Referenced by findpts_local_free().
void findpts_local_setup_2 (struct findpts_local_data_2 *const fd, const double *const elx[2], const unsigned n[2], const uint nel, const unsigned m[2], const double bbox_tol, const uint max_hash_size, const unsigned npt_max, const double newt_tol)
Referenced by findpts_local_setup().
void findpts_local_setup_3 (struct findpts_local_data_3 *const fd, const double *const elx[3], const unsigned n[3], const uint nel, const unsigned m[3], const double bbox_tol, const uint max_hash_size, const unsigned npt_max, const double newt_tol)
Referenced by findpts_local_setup().