Nek5000: gauss.F90 File Reference
gauss.F90 File Reference
routines for direct solves with Gaussian elimination (LU decomposition).
Functions/Subroutines
subroutine lu (A, N, NDIM, IR, IC)
the first subroutine to compute the matrix inverse
subroutine solve (F, A, K, N, NDIM, IR, IC)
second part of the matrix inverse
Detailed Description
routines for direct solves with Gaussian elimination (LU decomposition).
Definition in file gauss.F90.
Function/Subroutine Documentation
subroutine lu (real(dp), dimension(ndim,*) A, integer N, integer NDIM, integer, dimension(*) IR, integer, dimension(*) IC)
the first subroutine to compute the matrix inverse
Definition at line 6 of file gauss.F90.
Referenced by setbd().
subroutine solve (real(dp), dimension(ndim,*) F, real(dp), dimension(ndim,*) A, integer K, integer N, integer NDIM, integer, dimension(*) IR, integer, dimension(*) IC)
second part of the matrix inverse
Definition at line 79 of file gauss.F90.
References exitt().
Referenced by setbd().