Nek5000: genxyz.F90 File Reference
genxyz.F90 File Reference
Functions/Subroutines
subroutine setdef ()
Set up deformed element logical switches.
logical function ifvchk (VEC, I1, I2, I3)
Take the dot product of the three components of VEC to see if it's zero.
subroutine gencoor ()
Generate xyz coordinates for all elements. Velocity formulation : mesh 3 is used Stress formulation : mesh 1 is used.
subroutine genxyz (xml, yml, zml, nxl, nyl, nzl)
subroutine sethmat (h, zgml, nxl, nyl, nzl)
subroutine setzgml (zgml, e, nxl, nyl, nzl, ifaxl)
real(dp) function dot (V1, V2, N)
Compute Cartesian vector dot product.
subroutine linquad (xl, yl, zl, nxl, nyl, nzl)
subroutine xyzlin (xl, yl, zl, nxl, nyl, nzl, e, ifaxl)
Generate bi- or trilinear mesh.
Function/Subroutine Documentation
real(dp) function dot (real(dp), dimension(n) V1, real(dp), dimension(n) V2, integer N)
Compute Cartesian vector dot product.
Definition at line 348 of file genxyz.F90.
subroutine gencoor ()
Generate xyz coordinates for all elements. Velocity formulation : mesh 3 is used Stress formulation : mesh 1 is used.
Definition at line 196 of file genxyz.F90.
References genxyz().
Referenced by gengeom().
subroutine genxyz (real(dp), dimension(nxl,nyl,nzl,1) xml, real(dp), dimension(nxl,nyl,nzl,1) yml, real(dp), dimension(nxl,nyl,nzl,1) zml, integer nxl, integer nyl, integer nzl)
Definition at line 215 of file genxyz.F90.
References linquad(), sethmat(), and setzgml().
Referenced by gencoor().
logical function ifvchk (real(dp), dimension(3,12) VEC, integer I1, integer I2, integer I3)
Take the dot product of the three components of VEC to see if it's zero.
Definition at line 164 of file genxyz.F90.
subroutine linquad (real(dp), dimension(nxl*nyl*nzl,*) xl, real(dp), dimension(nxl*nyl*nzl,*) yl, real(dp), dimension(nxl*nyl*nzl,*) zl, integer nxl, integer nyl, integer nzl)
Definition at line 367 of file genxyz.F90.
References xyzlin().
Referenced by genxyz().
subroutine setdef ()
Set up deformed element logical switches.
Definition at line 4 of file genxyz.F90.
Referenced by gengeom(), and geom_reset().
subroutine sethmat (real(dp), dimension(lx1,3,2) h, real(dp), dimension(lx1,3) zgml, integer nxl, integer nyl, integer nzl)
Definition at line 272 of file genxyz.F90.
Referenced by genxyz().
subroutine setzgml (real(dp), dimension(lx1,3), intent(out) zgml, integer e, integer nxl, integer nyl, integer nzl, logical ifaxl)
Definition at line 304 of file genxyz.F90.
References copy(), and exitti().
Referenced by genxyz(), and xyzlin().
subroutine xyzlin (real(dp), dimension(nxl,nyl,nzl) xl, real(dp), dimension(nxl,nyl,nzl) yl, real(dp), dimension(nxl,nyl,nzl) zl, integer nxl, integer nyl, integer nzl, integer e, logical ifaxl)
Generate bi- or trilinear mesh.
Definition at line 402 of file genxyz.F90.
References fd_weights_full(), setzgml(), tensr3(), and transpose().
Referenced by linquad().