Nek5000: gmres.F90 File Reference
gmres.F90 File Reference
Solve the Helmholtz equation by right-preconditioned GMRES iteration.
Functions/Subroutines
subroutine ax (w, x, h1, h2, n)
w = A*x for pressure iteration
subroutine hmh_gmres (res, h1, h2, wt, iter)
Solve the Helmholtz equation by right-preconditioned GMRES iteration.
Detailed Description
Solve the Helmholtz equation by right-preconditioned GMRES iteration.
Definition in file gmres.F90.
Function/Subroutine Documentation
subroutine ax (real(dp), dimension(n) w, real(dp), dimension(n) x, real(dp), dimension(n) h1, real(dp), dimension(n) h2, integer n)
w = A*x for pressure iteration
Definition at line 6 of file gmres.F90.
References axhelm(), and dssum().
Referenced by hmh_gmres().
subroutine hmh_gmres (real(dp), dimension (lx1*ly1*lz1*lelv) res, real(dp), dimension (lx1,ly1,lz1,lelv) h1, real(dp), dimension (lx1,ly1,lz1,lelv) h2, real(dp), dimension (lx1*ly1*lz1*lelv) wt, integer iter)
Solve the Helmholtz equation by right-preconditioned GMRES iteration.
Todo:
move these allocations to where they are needed
Todo:
check if these inits are nessesary
Todo:
Do we need this?
Definition at line 27 of file gmres.F90.
References ax(), chktcg1(), ctimer::dnekclock(), gop(), hsmg_routines::h1mg_solve(), ortho(), and sum().
Referenced by cggo().