Nek5000: jl/tests/gs_test_old.c File Reference
gs_test_old.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "name.h"
#include "types.h"
Macros
#define fgs_setup FORTRAN_NAME(gs_setup ,GS_SETUP)
#define fgs_op FORTRAN_NAME(gs_op ,GS_OP)
#define fgs_op_vec FORTRAN_NAME(gs_op_vec ,GS_OP_VEC)
#define fgs_op_many FORTRAN_NAME(gs_op_many ,GS_OP_MANY)
#define fgs_op_fields FORTRAN_NAME(gs_op_fields,GS_OP_FIELDS)
#define fgs_free FORTRAN_NAME(gs_free ,GS_FREE)
Typedefs
typedef void MPI_Comm
typedef long real
Functions
void fgs_setup (sint *handle, const slong id[], const sint *n, const MPI_Comm *comm, const sint *np)
void fgs_op (const sint *handle, void *u, const sint *dom, const sint *op, const sint *transpose)
void fgs_op_vec (const sint *handle, void *u, const sint *n, const sint *dom, const sint *op, const sint *transpose)
void fgs_op_many (const sint *handle, void *u1, void *u2, void *u3, void *u4, void *u5, void *u6, const sint *n, const sint *dom, const sint *op, const sint *transpose)
void fgs_free (const sint *handle)
void assert_is_zero (real v)
int main (int narg, char *arg[])
Variables
sint datatype = 4
Macro Definition Documentation
#define fgs_free FORTRAN_NAME(gs_free ,GS_FREE)
Definition at line 36 of file gs_test_old.c.
Referenced by main().
#define fgs_op FORTRAN_NAME(gs_op ,GS_OP)
Definition at line 32 of file gs_test_old.c.
Referenced by main().
#define fgs_op_fields FORTRAN_NAME(gs_op_fields,GS_OP_FIELDS)
Definition at line 35 of file gs_test_old.c.
#define fgs_op_many FORTRAN_NAME(gs_op_many ,GS_OP_MANY)
Definition at line 34 of file gs_test_old.c.
Referenced by main().
#define fgs_op_vec FORTRAN_NAME(gs_op_vec ,GS_OP_VEC)
Definition at line 33 of file gs_test_old.c.
Referenced by main().
#define fgs_setup FORTRAN_NAME(gs_setup ,GS_SETUP)
Definition at line 31 of file gs_test_old.c.
Referenced by main().
Typedef Documentation
typedef void MPI_Comm
Definition at line 23 of file gs_test_old.c.
typedef long real
Definition at line 28 of file gs_test_old.c.
Function Documentation
void assert_is_zero (real v)
Definition at line 49 of file gs_test_old.c.
Referenced by main().
void fgs_free (const sint * handle)
Definition at line 1284 of file gs.c.
References cgs_free, and fgs_check_handle().
void fgs_op (const sint * handle, void * u, const sint * dom, const sint * op, const sint * transpose)
void fgs_op_many (const sint * handle, void * u1, void * u2, void * u3, void * u4, void * u5, void * u6, const sint * n, const sint * dom, const sint * op, const sint * transpose)
void fgs_op_vec (const sint * handle, void * u, const sint * n, const sint * dom, const sint * op, const sint * transpose)
void fgs_setup (sint * handle, const slong id[], const sint * n, const MPI_Comm * comm, const sint * np)
int main (int narg, char * arg[])
Definition at line 56 of file gs_test_old.c.
References assert_is_zero(), datatype, fgs_free, fgs_op, fgs_op_many, fgs_op_vec, fgs_setup, i, np, sint, slong, and transpose().
Variable Documentation
sint datatype = 4
Definition at line 29 of file gs_test_old.c.
Referenced by main().