Nek5000: ic.F90 File Reference
ic.F90 File Reference
Macros
#define SIMPLE_IO
Functions/Subroutines
subroutine setics
Set initial conditions.
subroutine slogic (iffort, ifrest, ifprsl, nfiles)
Set up logicals for initial conditions.
subroutine restart_driver (nfiles)
driver for restarts (1) Open restart file(s) (2) Check previous spatial discretization (3) Map (K1,N1) => (K2,N2) if necessary nfiles > 1 has several implications: i. For std. run, data is taken from last file in list, unless explicitly specified in argument list of filename ii. For MHD and perturbation cases, 1st file is for U,P,T; subsequent files are for B-field or perturbation fields
subroutine sioflag (ndumps, fname, rsopts)
Set IO flags according to Restart Options File, RSOPTS.
subroutine mapdmp (sdump, tdump, ieg, nxr, nyr, nzr, if_byte_sw)
subroutine mapab4r (x, y, nxr, nel)
Interpolate Y(NXR,NYR,NZR,NEL) to X(NX1,NY1,NZ1,NEL) (assumes that NXR=NYR=NZR, or NXR=NYR, NZR=1) Input: real*4, Output: default precision.
subroutine nekuic
User specified fortran function (=0 if not specified)
logical function if_byte_swap_test (bytetest, ierr)
subroutine geom_reset (icall)
Generate geometry data.
subroutine dsavg (u)
Take direct stiffness avg of u.
subroutine mbyte_open (hname, fid, ierr)
open blah000.fldnn
Macro Definition Documentation
#define SIMPLE_IO
Function/Subroutine Documentation
subroutine dsavg (real(dp), dimension(lx1,ly1,lz1,lelt) u)
Take direct stiffness avg of u.
Definition at line 1559 of file ic.F90.
References dssum().
Referenced by hsmg_routines::h1mg_solve(), rand_fld_h1(), and setics().
subroutine geom_reset (integer icall)
Generate geometry data.
Definition at line 1513 of file ic.F90.
References geom1(), geom2(), setdef(), setinvm(), sfastax(), updmsys(), and volume().
Referenced by hsmg_routines::h1mg_setup(), nek_init(), and setics().
logical function if_byte_swap_test (real(r4) bytetest, integer ierr)
Definition at line 1486 of file ic.F90.
References byte_reverse.
subroutine mapab4r (real(dp), dimension(nx1,ny1,nz1,nel) x, real(r4), dimension(nxr,nxr,nxr,nel) y, integer nxr, integer nel)
Interpolate Y(NXR,NYR,NZR,NEL) to X(NX1,NY1,NZ1,NEL) (assumes that NXR=NYR=NZR, or NXR=NYR, NZR=1) Input: real*4, Output: default precision.
Definition at line 1331 of file ic.F90.
References copy(), copy4r(), speclib::igllm(), mxm(), and speclib::zwgll().
Referenced by mapdmp().
subroutine mapdmp (real(dp), dimension(:,:), allocatable sdump, real(r4), dimension(lxyzr) tdump, integer ieg, integer nxr, integer nyr, integer nzr, logical if_byte_sw)
Definition at line 1246 of file ic.F90.
References byte_reverse, copy4r(), crecv(), csend(), err_chk(), exitti(), parallel::gllel(), parallel::gllnid(), mapab4r(), and np.
Referenced by restart_driver().
subroutine mbyte_open (character(132) hname, integer fid, integer ierr)
open blah000.fldnn
Definition at line 1592 of file ic.F90.
References byte_open, byte_open_mpi(), chcopy(), string::indx1(), string::ltrunc(), and np.
Referenced by io::load_ic(), and mfo_open_files().
subroutine nekuic ()
User specified fortran function (=0 if not specified)
Definition at line 1393 of file ic.F90.
References parallel::lglel(), and nekasgn().
Referenced by setics().
subroutine restart_driver (integer, intent(in) nfiles)
driver for restarts (1) Open restart file(s) (2) Check previous spatial discretization (3) Map (K1,N1) => (K2,N2) if necessary nfiles > 1 has several implications: i. For std. run, data is taken from last file in list, unless explicitly specified in argument list of filename ii. For MHD and perturbation cases, 1st file is for U,P,T; subsequent files are for B-field or perturbation fields
Definition at line 547 of file ic.F90.
References bcast(), byte_close, byte_open, byte_read, chcopy(), copy(), err_chk(), exitt(), parallel::gllnid(), glmax(), string::i1_from_char(), lbcast(), string::ltrunc(), mapdmp(), setup_convect(), and sioflag().
Referenced by setics().
subroutine setics ()
Set initial conditions.
Definition at line 5 of file ic.F90.
References dsavg(), dssum(), exitt(), geom_reset(), lagvel(), io::load_ic(), nekgsync(), nekuic(), opcolv(), opcopy(), opdssum(), ortho(), restart_driver(), setup_convect(), and slogic().
Referenced by nek_init().
subroutine sioflag (integer ndumps, character(132) fname, character(132) rsopts)
Set IO flags according to Restart Options File, RSOPTS.
Definition at line 1092 of file ic.F90.
References blank(), string::capit(), chcopy(), string::csplit(), string::ifgtrl(), string::indx1(), string::indx_cut(), string::ljust(), and string::ltrunc().
Referenced by restart_driver(), and slogic().
subroutine slogic (logical, dimension(ldimt1,0:lpert) iffort, logical, dimension(0:ldimt1,0:lpert) ifrest, logical, dimension(ldimt1,0:lpert) ifprsl, integer nfiles)
Set up logicals for initial conditions.
Definition at line 406 of file ic.F90.
References blank(), string::capit(), string::csplit(), string::indx1(), string::indx_cut(), string::ljust(), string::ltrunc(), and sioflag().
Referenced by setics().