Nek5000: induct.F90 File Reference
induct.F90 File Reference
Functions/Subroutines
subroutine compute_cfl (cfl, u, v, w, dt)
Given velocity field (u,v,w) and dt, compute current CFL number.
subroutine getdr (dri, zgm1, nx1)
subroutine set_dealias_rx
Eulerian scheme, add convection term to forcing function.
Function/Subroutine Documentation
subroutine compute_cfl (real(dp) cfl, real(dp), dimension(nx1,ny1,nz1,nelv) u, real(dp), dimension(nx1,ny1,nz1,nelv) v, real(dp), dimension(nx1,ny1,nz1,nelv) w, real(dp) dt)
Given velocity field (u,v,w) and dt, compute current CFL number.
Definition at line 7 of file induct.F90.
References getdr().
Referenced by setdt().
subroutine getdr (real(dp), dimension(nx1) dri, real(dp), dimension(nx1) zgm1, integer nx1)
Definition at line 106 of file induct.F90.
Referenced by compute_cfl().
subroutine set_dealias_rx ()
Eulerian scheme, add convection term to forcing function.
Definition at line 128 of file induct.F90.
References interp::get_int_ptr(), specmpn(), and speclib::zwgl().
Referenced by set_convect_new().