Nek5000: jl/lob_bnd.c File Reference
lob_bnd.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "c99.h"
#include "name.h"
#include "types.h"
#include "fail.h"
#include "mem.h"
#include "poly.h"
Classes
struct dbl_range
Macros
#define lob_bnd_setup PREFIXED_NAME(lob_bnd_setup)
#define lob_bnd_lin_1 PREFIXED_NAME(lob_bnd_lin_1)
#define lob_bnd_lin_2 PREFIXED_NAME(lob_bnd_lin_2)
#define lob_bnd_lin_3 PREFIXED_NAME(lob_bnd_lin_3)
#define lob_bnd_1 PREFIXED_NAME(lob_bnd_1)
#define lob_bnd_2 PREFIXED_NAME(lob_bnd_2)
#define lob_bnd_3 PREFIXED_NAME(lob_bnd_3)
#define PI 3.1415926535897932384626433832795028841971693993751058209749445923
Functions
void lob_bnd_setup (double *restrict data, unsigned n, unsigned m)
static void lob_bnd_fst (double *restrict b, const double *restrict z, const double *restrict Q, const double *restrict h, const double *restrict lb, unsigned n, unsigned m, const double *restrict u)
static void lob_bnd_ext (double *restrict b_, const double *restrict z, const double *restrict Q, const double *restrict h, const double *restrict lbnp, unsigned n, unsigned m, const double *restrict br_, unsigned mr, double *restrict a)
void lob_bnd_lin_1 (double *restrict b, const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, uint un)
void lob_bnd_lin_2 (double *restrict b, const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, uint un, double *restrict work)
void lob_bnd_lin_3 (double *restrict b, const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, uint un, double *restrict work)
static struct dbl_range minmax (const double *restrict b, unsigned m)
struct dbl_range lob_bnd_1 (const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, double *restrict work)
struct dbl_range lob_bnd_2 (const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, double *restrict work)
struct dbl_range lob_bnd_3 (const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, double *restrict work)
Macro Definition Documentation
#define lob_bnd_1 PREFIXED_NAME(lob_bnd_1)
Definition at line 17 of file lob_bnd.c.
#define lob_bnd_2 PREFIXED_NAME(lob_bnd_2)
Definition at line 18 of file lob_bnd.c.
Referenced by main(), and rand_elt_2().
#define lob_bnd_3 PREFIXED_NAME(lob_bnd_3)
Definition at line 19 of file lob_bnd.c.
Referenced by main(), and rand_elt_3().
#define lob_bnd_lin_1 PREFIXED_NAME(lob_bnd_lin_1)
Definition at line 14 of file lob_bnd.c.
Referenced by lob_bnd_1(), and main().
#define lob_bnd_lin_2 PREFIXED_NAME(lob_bnd_lin_2)
Definition at line 15 of file lob_bnd.c.
Referenced by lob_bnd_2(), and main().
#define lob_bnd_lin_3 PREFIXED_NAME(lob_bnd_lin_3)
Definition at line 16 of file lob_bnd.c.
Referenced by lob_bnd_3(), and main().
#define lob_bnd_setup PREFIXED_NAME(lob_bnd_setup)
Definition at line 13 of file lob_bnd.c.
Referenced by main(), rand_elt_2(), and rand_elt_3().
#define PI 3.1415926535897932384626433832795028841971693993751058209749445923
Definition at line 71 of file lob_bnd.c.
Referenced by lob_bnd_setup().
Function Documentation
struct dbl_range lob_bnd_1 (const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, double *restrict work)
Definition at line 250 of file lob_bnd.c.
References lob_bnd_lin_1, minmax(), n, and work.
struct dbl_range lob_bnd_2 (const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, double *restrict work)
Definition at line 260 of file lob_bnd.c.
References lob_bnd_lin_2, minmax(), mr, nr, ns, and work.
struct dbl_range lob_bnd_3 (const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double * lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, double *restrict work)
Definition at line 273 of file lob_bnd.c.
References lob_bnd_lin_3, minmax(), mr, nr, ns, and work.
static void lob_bnd_ext (double *restrict b_, const double *restrict z, const double *restrict Q, const double *restrict h, const double *restrict lbnp, unsigned n, unsigned m, const double *restrict br_, unsigned mr, double *restrict a) static
Definition at line 146 of file lob_bnd.c.
References i, mr, n, and restrict.
Referenced by lob_bnd_lin_2(), and lob_bnd_lin_3().
static void lob_bnd_fst (double *restrict b, const double *restrict z, const double *restrict Q, const double *restrict h, const double *restrict lb, unsigned n, unsigned m, const double *restrict u) static
Definition at line 127 of file lob_bnd.c.
References i, and n.
Referenced by lob_bnd_lin_1(), lob_bnd_lin_2(), and lob_bnd_lin_3().
void lob_bnd_lin_1 (double *restrict b, const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, uint un)
Definition at line 189 of file lob_bnd.c.
References lob_bnd_fst(), n, Q, and z.
void lob_bnd_lin_2 (double *restrict b, const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, uint un, double *restrict work)
Definition at line 198 of file lob_bnd.c.
References i, lob_bnd_ext(), lob_bnd_fst(), mr, nr, ns, Qs, work, zr, and zs.
void lob_bnd_lin_3 (double *restrict b, const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double * lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, uint un, double *restrict work)
Definition at line 217 of file lob_bnd.c.
References i, lob_bnd_ext(), lob_bnd_fst(), mr, nr, ns, Qs, work, zr, zs, and zt.
void lob_bnd_setup (double *restrict data, unsigned n, unsigned m)
Definition at line 73 of file lob_bnd.c.
References cr, gll_lag_setup, gll_lag_size, i, lobatto_quad, n, p, PI, Q, restrict, tmalloc, x, and z.
static struct dbl_range minmax (const double *restrict b, unsigned m) static
Definition at line 239 of file lob_bnd.c.
References dbl_range::max, and dbl_range::min.
Referenced by lob_bnd_1(), lob_bnd_2(), and lob_bnd_3().