Nek5000: jl/lob_bnd.h File Reference
lob_bnd.h File Reference
Classes
struct dbl_range
Macros
#define lob_bnd_setup PREFIXED_NAME(lob_bnd_setup)
#define lob_bnd_lin_1 PREFIXED_NAME(lob_bnd_lin_1)
#define lob_bnd_lin_2 PREFIXED_NAME(lob_bnd_lin_2)
#define lob_bnd_lin_3 PREFIXED_NAME(lob_bnd_lin_3)
#define lob_bnd_1 PREFIXED_NAME(lob_bnd_1)
#define lob_bnd_2 PREFIXED_NAME(lob_bnd_2)
#define lob_bnd_3 PREFIXED_NAME(lob_bnd_3)
Functions
static unsigned lob_bnd_size (unsigned n, unsigned m)
void lob_bnd_setup (double *restrict data, unsigned n, unsigned m)
void lob_bnd_lin_1 (double *restrict b, const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, uint un)
void lob_bnd_lin_2 (double *restrict b, const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, uint un, double *restrict work)
void lob_bnd_lin_3 (double *restrict b, const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, uint un, double *restrict work)
struct dbl_range lob_bnd_1 (const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, double *restrict work)
struct dbl_range lob_bnd_2 (const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, double *restrict work)
struct dbl_range lob_bnd_3 (const double *lob_bnd_data_r, unsigned nr, unsigned mr, const double *lob_bnd_data_s, unsigned ns, unsigned ms, const double *lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, double *restrict work)
Macro Definition Documentation
#define lob_bnd_1 PREFIXED_NAME(lob_bnd_1)
Definition at line 12 of file lob_bnd.h.
#define lob_bnd_2 PREFIXED_NAME(lob_bnd_2)
Definition at line 13 of file lob_bnd.h.
#define lob_bnd_3 PREFIXED_NAME(lob_bnd_3)
Definition at line 14 of file lob_bnd.h.
#define lob_bnd_lin_1 PREFIXED_NAME(lob_bnd_lin_1)
Definition at line 9 of file lob_bnd.h.
#define lob_bnd_lin_2 PREFIXED_NAME(lob_bnd_lin_2)
Definition at line 10 of file lob_bnd.h.
#define lob_bnd_lin_3 PREFIXED_NAME(lob_bnd_lin_3)
Definition at line 11 of file lob_bnd.h.
#define lob_bnd_setup PREFIXED_NAME(lob_bnd_setup)
Definition at line 8 of file lob_bnd.h.
Function Documentation
struct dbl_range lob_bnd_1 (const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, double *restrict work)
Definition at line 250 of file lob_bnd.c.
References lob_bnd_lin_1, minmax(), n, and work.
struct dbl_range lob_bnd_2 (const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, double *restrict work)
Definition at line 260 of file lob_bnd.c.
References lob_bnd_lin_2, minmax(), mr, nr, ns, and work.
struct dbl_range lob_bnd_3 (const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double * lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, double *restrict work)
Definition at line 273 of file lob_bnd.c.
References lob_bnd_lin_3, minmax(), mr, nr, ns, and work.
void lob_bnd_lin_1 (double *restrict b, const double *restrict lob_bnd_data, unsigned n, unsigned m, const double *restrict u, uint un)
Definition at line 189 of file lob_bnd.c.
References lob_bnd_fst(), n, Q, and z.
void lob_bnd_lin_2 (double *restrict b, const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double *restrict u, uint un, double *restrict work)
Definition at line 198 of file lob_bnd.c.
References i, lob_bnd_ext(), lob_bnd_fst(), mr, nr, ns, Qs, work, zr, and zs.
void lob_bnd_lin_3 (double *restrict b, const double * lob_bnd_data_r, unsigned nr, unsigned mr, const double * lob_bnd_data_s, unsigned ns, unsigned ms, const double * lob_bnd_data_t, unsigned nt, unsigned mt, const double *restrict u, uint un, double *restrict work)
Definition at line 217 of file lob_bnd.c.
References i, lob_bnd_ext(), lob_bnd_fst(), mr, nr, ns, Qs, work, zr, zs, and zt.
void lob_bnd_setup (double *restrict data, unsigned n, unsigned m)
Definition at line 73 of file lob_bnd.c.
References cr, gll_lag_setup, gll_lag_size, i, lobatto_quad, n, p, PI, Q, restrict, tmalloc, x, and z.
static unsigned lob_bnd_size (unsigned n, unsigned m) static
Definition at line 64 of file lob_bnd.h.
Referenced by main(), obbox_calc_2(), and obbox_calc_3().