Nek5000: makeq.F90 File Reference
makeq.F90 File Reference
Generate forcing function for the solution of a passive scalar. !! NOTE: Do not change the content of the array BQ until the current.
Functions/Subroutines
subroutine makeq ()
Generate forcing function for the solution of a passive scalar. !! NOTE: Do not change the content of the array BQ until the current.
Detailed Description
Generate forcing function for the solution of a passive scalar. !! NOTE: Do not change the content of the array BQ until the current.
Definition in file makeq.F90.
Function/Subroutine Documentation
subroutine makeq ()
Generate forcing function for the solution of a passive scalar. !! NOTE: Do not change the content of the array BQ until the current.
Definition at line 6 of file makeq.F90.
References convab(), ctimer::dnekclock(), dssum(), makeabq(), makebdq(), makeq_aux(), and wlaplacian().
Referenced by cdscal().