Nek5000: math.F90 File Reference
math.F90 File Reference
Functions/Subroutines
real(dp) function vlsc3 (X, Y, B, N)
local inner product, with weight
subroutine blank (A, N)
blank a string
subroutine copy (a, b, n)
subroutine chcopy (a, b, n)
real(dp) function vlamax (vec, n)
vector local max(abs())
subroutine vcross (u1, u2, u3, v1, v2, v3, w1, w2, w3, n)
Compute a Cartesian vector cross product.
integer function mod1 (i, n)
Yields MOD(I,N) with the exception that if I=K*N, result is N.
integer function log2 (k)
subroutine iswap (b, ind, n, temp)
SORT ASSOCIATED ELEMENTS BY PUTTING ITEM(JJ) into item(i) where JJ = ind(i)
real(dp) function glsc3 (a, b, mult, n)
Perform inner-product in double precision.
real(dp) function glsc2 (x, y, n)
Perform inner-product in double precision.
real(dp) function glsc23 (x, y, z, n)
Perform inner-product x*x*y*z.
real(dp) function glsum (x, n)
real(dp) function glamax (a, n)
integer function iglmin (a, n)
integer function iglmax (a, n)
integer function iglsum (a, n)
integer(i8) function i8glsum (a, n)
global sum (long integer)
real(dp) function glmax (a, n)
real(dp) function glmin (a, n)
subroutine gllog (la, lb)
If ANY LA=LB, then ALL LA=LB.
subroutine isort (a, ind, n)
Use Heap Sort (p 231 Num. Rec., 1st Ed.)
subroutine sort (a, ind, n)
Use Heap Sort (p 231 Num. Rec., 1st Ed.)
integer(i8) function i8glmax (a, n)
Global maximum of long integer array.
subroutine ident (a, n)
Construct A = I_n (identity matrix)
subroutine iswapt_ip (x, p, n)
Function/Subroutine Documentation
subroutine blank (character(1), dimension(*) A, integer N)
blank a string
Definition at line 38 of file math.F90.
Referenced by string::cscan(), string::csplit(), echopar(), err_chk(), exitti(), files(), genmesh(), get_session_info(), get_vert_map(), initdat(), mfo_open_files(), mfo_write_hdr(), outfld(), pprint_all(), rdbdry(), rdcurve(), rdhist(), rdicdf(), runstat(), sioflag(), and slogic().
subroutine chcopy (character(1), dimension(n) a, character(1), dimension(n) b, integer n)
Definition at line 63 of file math.F90.
Referenced by string::cscan(), echopar(), err_chk(), exitti(), files(), io::get_restart_name(), get_session_info(), get_vert_map(), hmholtz(), helmholtz::hsolve(), mbyte_open(), mfo_open_files(), outfld(), restart_driver(), and sioflag().
subroutine copy (real(dp), dimension(n) a, real(dp), dimension(n) b, integer n)
Definition at line 52 of file math.F90.
Referenced by bcdirvc(), build_new_filter(), cdtp(), cggo(), convect_new(), filterq(), gen_crs_basis(), generalev(), helmholtz::gensh(), genwz(), get_local_crs_galerkin(), glmapm1(), gop(), hsmg_routines::h1mg_setup_semhat(), hsmg_routines::h1mg_solve(), hsmg_routines::hsmg_setup_semhat(), lagmass(), lagscal(), lagvel(), makeabf(), mapab4r(), mfo_outs(), mfo_outv(), io::mfo_read_scalar(), io::mfo_read_vector(), mpi_scan(), multd(), op_curl(), opcopy(), opdiv(), outpost2(), prepost_map(), restart_driver(), sethlm(), setinvm(), setup_topo(), setzgml(), startx1(), and vrdsmsh().
real(dp) function glamax (real(dp), dimension(n) a, integer n)
Definition at line 279 of file math.F90.
References gop().
subroutine gllog (logical la, logical lb)
If ANY LA=LB, then ALL LA=LB.
Definition at line 402 of file math.F90.
References gop().
Referenced by setlog(), and verrhe().
real(dp) function glmax (real(dp), dimension(n), intent(in) a, integer, intent(in) n)
Definition at line 363 of file math.F90.
References gop().
Referenced by restart_driver().
real(dp) function glmin (real(dp), dimension(n), intent(in) a, integer, intent(in) n)
Definition at line 383 of file math.F90.
References gop().
real(dp) function glsc2 (real(dp), dimension(n), intent(in) x, real(dp), dimension(n), intent(in) y, integer, intent(in) n)
Perform inner-product in double precision.
Definition at line 210 of file math.F90.
References gop().
Referenced by helmholtz::projh().
real(dp) function glsc23 (real(dp), dimension(n), intent(in) x, real(dp), dimension(n), intent(in) y, real(dp), dimension(n), intent(in) z, integer n)
Perform inner-product x*x*y*z.
Definition at line 242 of file math.F90.
References gop().
real(dp) function glsc3 (real(dp), dimension(n), intent(in) a, real(dp), dimension(n), intent(in) b, real(dp), dimension(n), intent(in) mult, integer, intent(in) n)
Perform inner-product in double precision.
Definition at line 177 of file math.F90.
References gop().
real(dp) function glsum (real(dp), dimension(n), intent(in) x, integer, intent(in) n)
Definition at line 261 of file math.F90.
References gop().
integer(i8) function i8glmax (integer(i8), dimension(n), intent(inout) a, integer, intent(in) n)
Global maximum of long integer array.
Definition at line 532 of file math.F90.
References i8gop().
integer(i8) function i8glsum (integer(i8), dimension(n), intent(in) a, integer, intent(in) n)
global sum (long integer)
Definition at line 344 of file math.F90.
References i8gop().
subroutine ident (real(dp), dimension(n,n), intent(out) a, integer, intent(in) n)
Construct A = I_n (identity matrix)
Definition at line 555 of file math.F90.
Referenced by build_new_filter(), and q_filter().
integer function iglmax (integer, dimension(n), intent(in) a, integer, intent(in) n)
Definition at line 312 of file math.F90.
References igop().
integer function iglmin (integer, dimension(n), intent(in) a, integer, intent(in) n)
Definition at line 297 of file math.F90.
References igop().
integer function iglsum (integer, dimension(n), intent(in) a, integer, intent(in) n)
Definition at line 327 of file math.F90.
References igop().
subroutine isort (integer, dimension(n) a, integer, dimension(n) ind, integer n)
Use Heap Sort (p 231 Num. Rec., 1st Ed.)
Definition at line 421 of file math.F90.
Referenced by assign_gllnid(), and setvert3d().
subroutine iswap (integer, dimension(n), intent(inout) b, integer, dimension(n), intent(in) ind, integer, intent(in) n, integer, dimension(n), intent(out) temp)
SORT ASSOCIATED ELEMENTS BY PUTTING ITEM(JJ) into item(i) where JJ = ind(i)
Definition at line 152 of file math.F90.
Referenced by opcount().
subroutine iswapt_ip (integer, dimension(n), intent(inout) x, integer, dimension(n), intent(inout) p, integer, intent(in) n)
Definition at line 570 of file math.F90.
References exitt().
Referenced by assign_gllnid().
integer function log2 (integer, intent(in) k)
Definition at line 135 of file math.F90.
integer function mod1 (integer, intent(in) i, integer, intent(in) n)
Yields MOD(I,N) with the exception that if I=K*N, result is N.
Definition at line 116 of file math.F90.
Referenced by outfld().
subroutine sort (real(dp), dimension(n) a, integer, dimension(n) ind, integer n)
Use Heap Sort (p 231 Num. Rec., 1st Ed.)
Definition at line 476 of file math.F90.
Referenced by opcount().
subroutine vcross (real(dp), dimension(n), intent(out) u1, real(dp), dimension(n), intent(out) u2, real(dp), dimension(n), intent(out) u3, real(dp), dimension(n), intent(in) v1, real(dp), dimension(n), intent(in) v2, real(dp), dimension(n), intent(in) v3, real(dp), dimension(n), intent(in) w1, real(dp), dimension(n), intent(in) w2, real(dp), dimension(n), intent(in) w3, integer, intent(in) n)
Compute a Cartesian vector cross product.
Definition at line 95 of file math.F90.
Referenced by area3().
real(dp) function vlamax (real(dp), dimension(n), intent(in) vec, integer, intent(in) n)
vector local max(abs())
Definition at line 76 of file math.F90.
real(dp) function vlsc3 (real(dp), dimension(n), intent(in) X, real(dp), dimension(n), intent(in) Y, real(dp), dimension(n), intent(in) B, integer, intent(in) N)
local inner product, with weight
Definition at line 2 of file math.F90.