Nek5000: mpi_dummy.F90 File Reference
mpi_dummy.F90 File Reference
Functions/Subroutines
subroutine mpi_scan (data1, data2, n, datatype, operation, comm, ierror)
subroutine mpi_abort (comm, errorcode, ierror)
subroutine mpi_allgather (data1, nsend, sendtype, data2, nrecv, recvtype, comm, ierror)
subroutine mpi_allgatherv (data1, nsend, sendtype, data2, nrecv, ndispls, recvtype, comm, ierror)
subroutine mpi_allreduce (data1, data2, n, datatype, operation, comm, ierror)
subroutine mpi_barrier (comm, ierror)
subroutine mpi_bcast (data, n, datatype, node, comm, ierror)
subroutine mpi_bsend (data, n, datatype, iproc, itag, comm, ierror)
subroutine mpi_cart_create (comm, ndims, dims, periods, reorder, comm_cart, ierror)
subroutine mpi_cart_get (comm, ndims, dims, periods, coords, ierror)
subroutine mpi_cart_shift (comm, idir, idisp, isource, idest, ierror)
subroutine mpi_comm_dup (comm, comm_out, ierror)
subroutine mpi_comm_free (comm, ierror)
subroutine mpi_comm_rank (comm, me, ierror)
subroutine mpi_comm_size (comm, nprocs, ierror)
subroutine mpi_comm_split (comm, icolor, ikey, comm_new, ierror)
subroutine mpi_copy_double_precision (data1, data2, n, ierror)
subroutine mpi_copy_integer (data1, data2, n, ierror)
subroutine mpi_copy_real (data1, data2, n, ierror)
subroutine mpi_finalize (ierror)
subroutine mpi_get_count (istatus, datatype, icount, ierror)
subroutine mpi_init (ierror)
subroutine mpi_irecv (data, n, datatype, iproc, itag, comm, irequest, ierror)
subroutine mpi_isend (data, n, datatype, iproc, itag, comm, request, ierror)
subroutine mpi_recv (data, n, datatype, iproc, itag, comm, istatus, ierror)
subroutine mpi_reduce (data1, data2, n, datatype, operation, receiver, comm, ierror)
subroutine mpi_reduce_double_precision (data1, data2, n, operation, ierror)
subroutine mpi_reduce_integer8 (data1, data2, n, operation, ierror)
subroutine mpi_reduce_integer (data1, data2, n, operation, ierror)
subroutine mpi_reduce_real (data1, data2, n, operation, ierror)
subroutine mpi_reduce_scatter (data1, data2, n, datatype, operation, comm, ierror)
subroutine mpi_rsend (data, n, datatype, iproc, itag, comm, ierror)
subroutine mpi_send (data, n, datatype, iproc, itag, comm, ierror)
subroutine mpi_wait (irequest, istatus, ierror)
subroutine mpi_waitall (icount, irequest, istatus, ierror)
subroutine mpi_waitany (icount, array_of_requests, index, istatus, ierror)
real *8 function mpi_wtick ()
real *8 function mpi_wtime ()
subroutine mpi_initialized (mpi_is_initialized, ierr)
subroutine mpi_comm_create (icomm, igroup, icommd, ierr)
subroutine mpi_comm_group (icomm, igroup, ierr)
subroutine mpi_group_free
subroutine mpi_attr_get (icomm, ikey, ival, iflag, ierr)
Function/Subroutine Documentation
subroutine mpi_abort (integer comm, integer errorcode, integer ierror)
Definition at line 46 of file mpi_dummy.F90.
subroutine mpi_allgather (integer, dimension(nsend) data1, integer nsend, integer sendtype, integer, dimension(nsend) data2, integer nrecv, integer recvtype, integer comm, integer ierror)
Definition at line 71 of file mpi_dummy.F90.
References mpi_copy_double_precision(), mpi_copy_integer(), and mpi_copy_real().
subroutine mpi_allgatherv (integer, dimension(nsend) data1, integer nsend, integer sendtype, integer, dimension(nsend) data2, integer nrecv, integer ndispls, integer recvtype, integer comm, integer ierror)
Definition at line 106 of file mpi_dummy.F90.
References mpi_copy_double_precision(), mpi_copy_integer(), and mpi_copy_real().
subroutine mpi_allreduce (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer datatype, integer operation, integer comm, integer ierror)
Definition at line 142 of file mpi_dummy.F90.
References mpi_reduce_double_precision(), mpi_reduce_integer(), mpi_reduce_integer8(), and mpi_reduce_real().
Referenced by gop(), i8gop(), and igop().
subroutine mpi_attr_get (icomm, ikey, ival, logical iflag, ierr)
Definition at line 1076 of file mpi_dummy.F90.
Referenced by iniproc().
subroutine mpi_barrier (integer comm, integer ierror)
Definition at line 193 of file mpi_dummy.F90.
Referenced by nekgsync().
subroutine mpi_bcast (integer, dimension(n) data, integer n, integer datatype, integer node, integer comm, integer ierror)
Definition at line 212 of file mpi_dummy.F90.
Referenced by bcast().
subroutine mpi_bsend (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer ierror)
Definition at line 236 of file mpi_dummy.F90.
subroutine mpi_cart_create (integer comm, integer ndims, integer, dimension(*) dims, logical, dimension(*) periods, logical reorder, integer comm_cart, integer ierror)
Definition at line 266 of file mpi_dummy.F90.
subroutine mpi_cart_get (integer comm, integer ndims, integer, dimension(*) dims, logical, dimension(*) periods, integer, dimension(*) coords, integer ierror)
Definition at line 292 of file mpi_dummy.F90.
subroutine mpi_cart_shift (integer comm, integer idir, integer idisp, integer isource, integer idest, integer ierror)
Definition at line 322 of file mpi_dummy.F90.
subroutine mpi_comm_create (icomm, igroup, icommd, ierr)
Definition at line 1056 of file mpi_dummy.F90.
Referenced by nek_comm_io().
subroutine mpi_comm_dup (integer comm, integer comm_out, integer ierror)
Definition at line 348 of file mpi_dummy.F90.
Referenced by get_session_info().
subroutine mpi_comm_free (integer comm, integer ierror)
Definition at line 369 of file mpi_dummy.F90.
Referenced by poisson::init_comm_infrastructure().
subroutine mpi_comm_group (icomm, igroup, ierr)
Definition at line 1063 of file mpi_dummy.F90.
Referenced by nek_comm_io().
subroutine mpi_comm_rank (integer comm, integer me, integer ierror)
Definition at line 388 of file mpi_dummy.F90.
Referenced by poisson::init_comm_infrastructure(), and mynode().
subroutine mpi_comm_size (integer comm, integer nprocs, integer ierror)
Definition at line 409 of file mpi_dummy.F90.
Referenced by poisson::init_comm_infrastructure(), numnodes(), and fft::transpose_grid().
subroutine mpi_comm_split (integer comm, integer icolor, integer ikey, integer comm_new, integer ierror)
Definition at line 430 of file mpi_dummy.F90.
Referenced by poisson::init_comm_infrastructure().
subroutine mpi_copy_double_precision (real*8, dimension(n) data1, real*8, dimension(n) data2, integer n, integer ierror)
Definition at line 453 of file mpi_dummy.F90.
Referenced by mpi_allgather(), mpi_allgatherv(), and mpi_reduce_scatter().
subroutine mpi_copy_integer (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer ierror)
Definition at line 480 of file mpi_dummy.F90.
Referenced by mpi_allgather(), mpi_allgatherv(), and mpi_reduce_scatter().
subroutine mpi_copy_real (real, dimension(n) data1, real, dimension(n) data2, integer n, integer ierror)
Definition at line 507 of file mpi_dummy.F90.
Referenced by mpi_allgather(), mpi_allgatherv(), and mpi_reduce_scatter().
subroutine mpi_finalize (integer ierror)
Definition at line 532 of file mpi_dummy.F90.
Referenced by exitt(), and exitt0().
subroutine mpi_get_count (integer istatus, integer datatype, integer icount, integer ierror)
Definition at line 550 of file mpi_dummy.F90.
subroutine mpi_group_free ()
Definition at line 1071 of file mpi_dummy.F90.
Referenced by nek_comm_io().
subroutine mpi_init (integer ierror)
Definition at line 575 of file mpi_dummy.F90.
Referenced by get_session_info().
subroutine mpi_initialized (mpi_is_initialized, ierr)
Definition at line 1048 of file mpi_dummy.F90.
Referenced by get_session_info().
subroutine mpi_irecv (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer irequest, integer ierror)
Definition at line 593 of file mpi_dummy.F90.
Referenced by poisson::grid_to_mesh(), irecv(), and poisson::mesh_to_grid().
subroutine mpi_isend (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer request, integer ierror)
Definition at line 624 of file mpi_dummy.F90.
Referenced by poisson::grid_to_mesh(), and poisson::mesh_to_grid().
subroutine mpi_recv (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer istatus, integer ierror)
Definition at line 656 of file mpi_dummy.F90.
Referenced by crecv().
subroutine mpi_reduce (integer, dimension(n) data1, integer data2, integer n, integer datatype, integer operation, integer receiver, integer comm, integer ierror)
Definition at line 687 of file mpi_dummy.F90.
References mpi_reduce_double_precision(), mpi_reduce_integer(), and mpi_reduce_real().
subroutine mpi_reduce_double_precision (real*8, dimension(n) data1, real*8, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 733 of file mpi_dummy.F90.
References n.
Referenced by mpi_allreduce(), and mpi_reduce().
subroutine mpi_reduce_integer (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 790 of file mpi_dummy.F90.
References n.
Referenced by mpi_allreduce(), and mpi_reduce().
subroutine mpi_reduce_integer8 (integer*8, dimension(n) data1, integer*8, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 762 of file mpi_dummy.F90.
References n.
Referenced by mpi_allreduce().
subroutine mpi_reduce_real (real, dimension(n) data1, real, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 818 of file mpi_dummy.F90.
References n.
Referenced by mpi_allreduce(), and mpi_reduce().
subroutine mpi_reduce_scatter (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer datatype, integer operation, integer comm, integer ierror)
Definition at line 847 of file mpi_dummy.F90.
References mpi_copy_double_precision(), mpi_copy_integer(), and mpi_copy_real().
subroutine mpi_rsend (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer ierror)
Definition at line 881 of file mpi_dummy.F90.
subroutine mpi_scan (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer datatype, integer operation, integer comm, integer ierror)
Definition at line 2 of file mpi_dummy.F90.
References copy().
Referenced by igl_running_sum().
subroutine mpi_send (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer ierror)
Definition at line 911 of file mpi_dummy.F90.
Referenced by csend().
subroutine mpi_wait (integer irequest, integer istatus, integer ierror)
Definition at line 941 of file mpi_dummy.F90.
Referenced by poisson::grid_to_mesh(), poisson::mesh_to_grid(), and msgwait().
subroutine mpi_waitall (integer icount, integer irequest, integer istatus, integer ierror)
Definition at line 965 of file mpi_dummy.F90.
subroutine mpi_waitany (integer icount, integer, dimension(*) array_of_requests, integer index, integer istatus, integer ierror)
Definition at line 990 of file mpi_dummy.F90.
real*8 function mpi_wtick ()
Definition at line 1017 of file mpi_dummy.F90.
real*8 function mpi_wtime ()
Definition at line 1031 of file mpi_dummy.F90.
Referenced by ctimer::dnekclock(), and ctimer::dnekclock_sync().