Nek5000: mxm_bgq.F90 File Reference
mxm_bgq.F90 File Reference
Functions/Subroutines
subroutine mxm_bgq_8 (a, n1, b, n2, c, n3)
subroutine mxm_bgq_12 (a, n1, b, n2, c, n3)
subroutine mxm_bgq_16 (a, n1, b, n2, c, n3)
subroutine mxm_bgq_6 (a, n1, b, n2, c, n3)
subroutine mxm_bgq_10 (a, n1, b, n2, c, n3)
Function/Subroutine Documentation
subroutine mxm_bgq_10 (real(dp), dimension(n1,n2), intent(in) a, integer, intent(in) n1, real(dp), dimension(n2,n3), intent(in) b, integer, intent(in) n2, real(dp), dimension(n1,n3), intent(out) c, integer, intent(in) n3)
Definition at line 287 of file mxm_bgq.F90.
Referenced by mxm().
subroutine mxm_bgq_12 (real(dp), dimension(n1,n2), intent(in) a, integer, intent(in) n1, real(dp), dimension(n2,n3), intent(in) b, integer, intent(in) n2, real(dp), dimension(n1,n3), intent(out) c, integer, intent(in) n3)
Definition at line 56 of file mxm_bgq.F90.
Referenced by mxm().
subroutine mxm_bgq_16 (real(dp), dimension(n1,n2), intent(in) a, integer, intent(in) n1, real(dp), dimension(n2,n3), intent(in) b, integer, intent(in) n2, real(dp), dimension(n1,n3), intent(out) c, integer, intent(in) n3)
Definition at line 129 of file mxm_bgq.F90.
Referenced by mxm().
subroutine mxm_bgq_6 (real(dp), dimension(n1,n2), intent(in) a, integer, intent(in) n1, real(dp), dimension(n2,n3), intent(in) b, integer, intent(in) n2, real(dp), dimension(n1,n3), intent(out) c, integer, intent(in) n3)
Definition at line 217 of file mxm_bgq.F90.
Referenced by mxm().
subroutine mxm_bgq_8 (real(dp), dimension(n1,n2), intent(in) a, integer, intent(in) n1, real(dp), dimension(n2,n3), intent(in) b, integer, intent(in) n2, real(dp), dimension(n1,n3), intent(out) c, integer, intent(in) n3)
Definition at line 1 of file mxm_bgq.F90.
Referenced by mxm().