Nek5000: mxm_std.F90 File Reference
mxm_std.F90 File Reference
Functions/Subroutines
subroutine mxmf2 (A, N1, B, N2, C, N3)
unrolled loop version
subroutine mxf1 (a, n1, b, n2, c, n3)
subroutine mxf2 (a, n1, b, n2, c, n3)
subroutine mxf3 (a, n1, b, n2, c, n3)
subroutine mxf4 (a, n1, b, n2, c, n3)
subroutine mxf5 (a, n1, b, n2, c, n3)
subroutine mxf6 (a, n1, b, n2, c, n3)
subroutine mxf7 (a, n1, b, n2, c, n3)
subroutine mxf8 (a, n1, b, n2, c, n3)
subroutine mxf9 (a, n1, b, n2, c, n3)
subroutine mxf10 (a, n1, b, n2, c, n3)
subroutine mxf11 (a, n1, b, n2, c, n3)
subroutine mxf12 (a, n1, b, n2, c, n3)
subroutine mxf13 (a, n1, b, n2, c, n3)
subroutine mxf14 (a, n1, b, n2, c, n3)
subroutine mxf15 (a, n1, b, n2, c, n3)
subroutine mxf16 (a, n1, b, n2, c, n3)
subroutine mxf17 (a, n1, b, n2, c, n3)
subroutine mxf18 (a, n1, b, n2, c, n3)
subroutine mxf19 (a, n1, b, n2, c, n3)
subroutine mxf20 (a, n1, b, n2, c, n3)
subroutine mxf21 (a, n1, b, n2, c, n3)
subroutine mxf22 (a, n1, b, n2, c, n3)
subroutine mxf23 (a, n1, b, n2, c, n3)
subroutine mxf24 (a, n1, b, n2, c, n3)
subroutine mxm44_0 (a, m, b, k, c, n)
subroutine mxm44_2 (a, m, b, k, c, n)
subroutine initab (a, b, n)
subroutine mxms (a, n1, b, n2, c, n3)
subroutine mxmu4 (a, n1, b, n2, c, n3)
subroutine madd (a, n1, b, n2, c, n3)
subroutine mxmur2 (a, n1, b, n2, c, n3)
subroutine mxmur2_1 (a, n1, b, n2, c, n3)
subroutine mxmur2_2 (a, n1, b, n2, c, n3)
subroutine mxmur2_3 (a, n1, b, n2, c, n3)
subroutine mxmur2_4 (a, n1, b, n2, c, n3)
subroutine mxmur2_5 (a, n1, b, n2, c, n3)
subroutine mxmur2_6 (a, n1, b, n2, c, n3)
subroutine mxmur2_7 (a, n1, b, n2, c, n3)
subroutine mxmur2_8 (a, n1, b, n2, c, n3)
subroutine mxmur2_9 (a, n1, b, n2, c, n3)
subroutine mxmur2_10 (a, n1, b, n2, c, n3)
subroutine mxmur2_11 (a, n1, b, n2, c, n3)
subroutine mxmur2_12 (a, n1, b, n2, c, n3)
subroutine mxmur2_13 (a, n1, b, n2, c, n3)
subroutine mxmur2_14 (a, n1, b, n2, c, n3)
subroutine mxmur2_15 (a, n1, b, n2, c, n3)
subroutine mxmur2_16 (a, n1, b, n2, c, n3)
subroutine mxmur3 (a, n1, b, n2, c, n3)
subroutine mxmur3_16 (a, n1, b, n2, c, n3)
subroutine mxmur3_15 (a, n1, b, n2, c, n3)
subroutine mxmur3_14 (a, n1, b, n2, c, n3)
subroutine mxmur3_13 (a, n1, b, n2, c, n3)
subroutine mxmur3_12 (a, n1, b, n2, c, n3)
subroutine mxmur3_11 (a, n1, b, n2, c, n3)
subroutine mxmur3_10 (a, n1, b, n2, c, n3)
subroutine mxmur3_9 (a, n1, b, n2, c, n3)
subroutine mxmur3_8 (a, n1, b, n2, c, n3)
subroutine mxmur3_7 (a, n1, b, n2, c, n3)
subroutine mxmur3_6 (a, n1, b, n2, c, n3)
subroutine mxmur3_5 (a, n1, b, n2, c, n3)
subroutine mxmur3_4 (a, n1, b, n2, c, n3)
subroutine mxmur3_3 (a, n1, b, n2, c, n3)
subroutine mxmur3_2 (a, n1, b, n2, c, n3)
subroutine mxmur3_1 (a, n1, b, n2, c, n3)
subroutine mxmd (a, n1, b, n2, c, n3)
subroutine mxmfb (a, n1, b, n2, c, n3)
subroutine mxmfb_1 (a, n1, b, n2, c, n3)
subroutine mxmfb_2 (a, n1, b, n2, c, n3)
subroutine mxmfb_3 (a, n1, b, n2, c, n3)
subroutine mxmfb_4 (a, n1, b, n2, c, n3)
subroutine mxmfb_5 (a, n1, b, n2, c, n3)
subroutine mxmfb_6 (a, n1, b, n2, c, n3)
subroutine mxmfb_7 (a, n1, b, n2, c, n3)
subroutine mxmfb_8 (a, n1, b, n2, c, n3)
subroutine mxmfb_9 (a, n1, b, n2, c, n3)
subroutine mxmfb_10 (a, n1, b, n2, c, n3)
subroutine mxmfb_11 (a, n1, b, n2, c, n3)
subroutine mxmfb_12 (a, n1, b, n2, c, n3)
subroutine mxmfb_13 (a, n1, b, n2, c, n3)
subroutine mxmfb_14 (a, n1, b, n2, c, n3)
subroutine mxmfb_15 (a, n1, b, n2, c, n3)
subroutine mxmfb_16 (a, n1, b, n2, c, n3)
subroutine mxmfb_17 (a, n1, b, n2, c, n3)
subroutine mxmfb_18 (a, n1, b, n2, c, n3)
subroutine mxmfb_19 (a, n1, b, n2, c, n3)
subroutine mxmfb_20 (a, n1, b, n2, c, n3)
subroutine mxmfb_21 (a, n1, b, n2, c, n3)
subroutine mxmfb_22 (a, n1, b, n2, c, n3)
subroutine mxmfb_23 (a, n1, b, n2, c, n3)
subroutine mxmfb_24 (a, n1, b, n2, c, n3)
subroutine mxmf3 (a, n1, b, n2, c, n3)
subroutine mxmf3_1 (a, n1, b, n2, c, n3)
subroutine mxmf3_2 (a, n1, b, n2, c, n3)
subroutine mxmf3_3 (a, n1, b, n2, c, n3)
subroutine mxmf3_4 (a, n1, b, n2, c, n3)
subroutine mxmf3_5 (a, n1, b, n2, c, n3)
subroutine mxmf3_6 (a, n1, b, n2, c, n3)
subroutine mxmf3_7 (a, n1, b, n2, c, n3)
subroutine mxmf3_8 (a, n1, b, n2, c, n3)
subroutine mxmf3_9 (a, n1, b, n2, c, n3)
subroutine mxmf3_10 (a, n1, b, n2, c, n3)
subroutine mxmf3_11 (a, n1, b, n2, c, n3)
subroutine mxmf3_12 (a, n1, b, n2, c, n3)
subroutine mxmf3_13 (a, n1, b, n2, c, n3)
subroutine mxmf3_14 (a, n1, b, n2, c, n3)
subroutine mxmf3_15 (a, n1, b, n2, c, n3)
subroutine mxmf3_16 (a, n1, b, n2, c, n3)
subroutine mxmf3_17 (a, n1, b, n2, c, n3)
subroutine mxmf3_18 (a, n1, b, n2, c, n3)
subroutine mxmf3_19 (a, n1, b, n2, c, n3)
subroutine mxmf3_20 (a, n1, b, n2, c, n3)
subroutine mxmf3_21 (a, n1, b, n2, c, n3)
subroutine mxmf3_22 (a, n1, b, n2, c, n3)
subroutine mxmf3_23 (a, n1, b, n2, c, n3)
subroutine mxmf3_24 (a, n1, b, n2, c, n3)
subroutine mxm44 (a, n1, b, n2, c, n3)
subroutine mxm44_0_t (a, m, b, k, c, n)
subroutine mxm44_2_t (a, m, b, k, c, n)
Function/Subroutine Documentation
subroutine initab (real(dp), dimension(1) a, real(dp), dimension(1) b, n)
Definition at line 1145 of file mxm_std.F90.
References i, and n.
subroutine madd (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1215 of file mxm_std.F90.
References i.
subroutine mxf1 (real(dp), dimension(n1,1) a, n1, real(dp), dimension(1,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 73 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf10 (real(dp), dimension(n1,10) a, n1, real(dp), dimension(10,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 226 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf11 (real(dp), dimension(n1,11) a, n1, real(dp), dimension(11,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 248 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf12 (real(dp), dimension(n1,12) a, n1, real(dp), dimension(12,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 271 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf13 (real(dp), dimension(n1,13) a, n1, real(dp), dimension(13,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 295 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf14 (real(dp), dimension(n1,14) a, n1, real(dp), dimension(14,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 320 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf15 (real(dp), dimension(n1,15) a, n1, real(dp), dimension(15,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 346 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf16 (real(dp), dimension(n1,16) a, n1, real(dp), dimension(16,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 373 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf17 (real(dp), dimension(n1,17) a, n1, real(dp), dimension(17,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 408 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf18 (real(dp), dimension(n1,18) a, n1, real(dp), dimension(18,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 437 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf19 (real(dp), dimension(n1,19) a, n1, real(dp), dimension(19,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 467 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf2 (real(dp), dimension(n1,2) a, n1, real(dp), dimension(2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 86 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf20 (real(dp), dimension(n1,20) a, n1, real(dp), dimension(20,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 498 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf21 (real(dp), dimension(n1,21) a, n1, real(dp), dimension(21,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 530 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf22 (real(dp), dimension(n1,22) a, n1, real(dp), dimension(22,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 563 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf23 (real(dp), dimension(n1,23) a, n1, real(dp), dimension(23,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 597 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf24 (real(dp), dimension(n1,24) a, n1, real(dp), dimension(24,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 632 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf3 (real(dp), dimension(n1,3) a, n1, real(dp), dimension(3,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 100 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf4 (real(dp), dimension(n1,4) a, n1, real(dp), dimension(4,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 115 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf5 (real(dp), dimension(n1,5) a, n1, real(dp), dimension(5,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 131 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf6 (real(dp), dimension(n1,6) a, n1, real(dp), dimension(6,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 148 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf7 (real(dp), dimension(n1,7) a, n1, real(dp), dimension(7,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 166 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf8 (real(dp), dimension(n1,8) a, n1, real(dp), dimension(8,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 185 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxf9 (real(dp), dimension(n1,9) a, n1, real(dp), dimension(9,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 205 of file mxm_std.F90.
References i.
Referenced by mxmf2().
subroutine mxm44 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3515 of file mxm_std.F90.
References mxm44_0_t(), and mxm44_2_t().
subroutine mxm44_0 (real(dp), dimension(m,k) a, m, real(dp), dimension(k,n) b, k, real(dp), dimension(m,n) c, n)
Definition at line 668 of file mxm_std.F90.
References i, and n.
Referenced by mxm(), and mxmf2().
subroutine mxm44_0_t (real(dp), dimension(m,k) a, m, real(dp), dimension(k,n) b, k, real(dp), dimension(m,n) c, n)
Definition at line 3544 of file mxm_std.F90.
References i, and n.
Referenced by mxm44().
subroutine mxm44_2 (real(dp), dimension(m,2) a, m, real(dp), dimension(2,n) b, k, real(dp), dimension(m,n) c, n)
Definition at line 1098 of file mxm_std.F90.
References i, and n.
Referenced by mxm().
subroutine mxm44_2_t (real(dp), dimension(m,2) a, m, real(dp), dimension(2,n) b, k, real(dp), dimension(m,n) c, n)
Definition at line 3976 of file mxm_std.F90.
References i, and n.
Referenced by mxm44().
subroutine mxmd (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2128 of file mxm_std.F90.
subroutine mxmf2 (real(dp), dimension(n1,n2) A, integer N1, real(dp), dimension(n2,n3) B, integer N2, real(dp), dimension(n1,n3) C, integer N3)
unrolled loop version
Definition at line 2 of file mxm_std.F90.
References mxf1(), mxf10(), mxf11(), mxf12(), mxf13(), mxf14(), mxf15(), mxf16(), mxf17(), mxf18(), mxf19(), mxf2(), mxf20(), mxf21(), mxf22(), mxf23(), mxf24(), mxf3(), mxf4(), mxf5(), mxf6(), mxf7(), mxf8(), mxf9(), and mxm44_0().
Referenced by mxm().
subroutine mxmf3 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2825 of file mxm_std.F90.
References mxmf3_1(), mxmf3_10(), mxmf3_11(), mxmf3_12(), mxmf3_13(), mxmf3_14(), mxmf3_15(), mxmf3_16(), mxmf3_17(), mxmf3_18(), mxmf3_19(), mxmf3_2(), mxmf3_20(), mxmf3_21(), mxmf3_22(), mxmf3_23(), mxmf3_24(), mxmf3_3(), mxmf3_4(), mxmf3_5(), mxmf3_6(), mxmf3_7(), mxmf3_8(), and mxmf3_9().
subroutine mxmf3_1 (real(dp), dimension(n1,1) a, n1, real(dp), dimension(1,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2927 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_10 (real(dp), dimension(n1,10) a, n1, real(dp), dimension(10,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3080 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_11 (real(dp), dimension(n1,11) a, n1, real(dp), dimension(11,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3102 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_12 (real(dp), dimension(n1,12) a, n1, real(dp), dimension(12,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3125 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_13 (real(dp), dimension(n1,13) a, n1, real(dp), dimension(13,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3149 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_14 (real(dp), dimension(n1,14) a, n1, real(dp), dimension(14,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3174 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_15 (real(dp), dimension(n1,15) a, n1, real(dp), dimension(15,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3200 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_16 (real(dp), dimension(n1,16) a, n1, real(dp), dimension(16,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3227 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_17 (real(dp), dimension(n1,17) a, n1, real(dp), dimension(17,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3255 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_18 (real(dp), dimension(n1,18) a, n1, real(dp), dimension(18,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3284 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_19 (real(dp), dimension(n1,19) a, n1, real(dp), dimension(19,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3314 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_2 (real(dp), dimension(n1,2) a, n1, real(dp), dimension(2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2940 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_20 (real(dp), dimension(n1,20) a, n1, real(dp), dimension(20,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3345 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_21 (real(dp), dimension(n1,21) a, n1, real(dp), dimension(21,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3377 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_22 (real(dp), dimension(n1,22) a, n1, real(dp), dimension(22,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3410 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_23 (real(dp), dimension(n1,23) a, n1, real(dp), dimension(23,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3444 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_24 (real(dp), dimension(n1,24) a, n1, real(dp), dimension(24,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3479 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_3 (real(dp), dimension(n1,3) a, n1, real(dp), dimension(3,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2954 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_4 (real(dp), dimension(n1,4) a, n1, real(dp), dimension(4,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2969 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_5 (real(dp), dimension(n1,5) a, n1, real(dp), dimension(5,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2985 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_6 (real(dp), dimension(n1,6) a, n1, real(dp), dimension(6,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3002 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_7 (real(dp), dimension(n1,7) a, n1, real(dp), dimension(7,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3020 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_8 (real(dp), dimension(n1,8) a, n1, real(dp), dimension(8,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3039 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmf3_9 (real(dp), dimension(n1,9) a, n1, real(dp), dimension(9,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 3059 of file mxm_std.F90.
References i.
Referenced by mxmf3().
subroutine mxmfb (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2146 of file mxm_std.F90.
References mxmfb_1(), mxmfb_10(), mxmfb_11(), mxmfb_12(), mxmfb_13(), mxmfb_14(), mxmfb_15(), mxmfb_16(), mxmfb_17(), mxmfb_18(), mxmfb_19(), mxmfb_2(), mxmfb_20(), mxmfb_21(), mxmfb_22(), mxmfb_23(), mxmfb_24(), mxmfb_3(), mxmfb_4(), mxmfb_5(), mxmfb_6(), mxmfb_7(), mxmfb_8(), and mxmfb_9().
subroutine mxmfb_1 (real(dp), dimension(n1,1) a, n1, real(dp), dimension(1,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2237 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_10 (real(dp), dimension(n1,10) a, n1, real(dp), dimension(10,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2390 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_11 (real(dp), dimension(n1,11) a, n1, real(dp), dimension(11,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2412 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_12 (real(dp), dimension(n1,12) a, n1, real(dp), dimension(12,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2435 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_13 (real(dp), dimension(n1,13) a, n1, real(dp), dimension(13,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2459 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_14 (real(dp), dimension(n1,14) a, n1, real(dp), dimension(14,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2484 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_15 (real(dp), dimension(n1,15) a, n1, real(dp), dimension(15,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2510 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_16 (real(dp), dimension(n1,16) a, n1, real(dp), dimension(16,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2537 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_17 (real(dp), dimension(n1,17) a, n1, real(dp), dimension(17,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2565 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_18 (real(dp), dimension(n1,18) a, n1, real(dp), dimension(18,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2594 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_19 (real(dp), dimension(n1,19) a, n1, real(dp), dimension(19,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2624 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_2 (real(dp), dimension(n1,2) a, n1, real(dp), dimension(2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2250 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_20 (real(dp), dimension(n1,20) a, n1, real(dp), dimension(20,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2655 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_21 (real(dp), dimension(n1,21) a, n1, real(dp), dimension(21,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2687 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_22 (real(dp), dimension(n1,22) a, n1, real(dp), dimension(22,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2720 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_23 (real(dp), dimension(n1,23) a, n1, real(dp), dimension(23,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2754 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_24 (real(dp), dimension(n1,24) a, n1, real(dp), dimension(24,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2789 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_3 (real(dp), dimension(n1,3) a, n1, real(dp), dimension(3,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2264 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_4 (real(dp), dimension(n1,4) a, n1, real(dp), dimension(4,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2279 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_5 (real(dp), dimension(n1,5) a, n1, real(dp), dimension(5,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2295 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_6 (real(dp), dimension(n1,6) a, n1, real(dp), dimension(6,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2312 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_7 (real(dp), dimension(n1,7) a, n1, real(dp), dimension(7,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2330 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_8 (real(dp), dimension(n1,8) a, n1, real(dp), dimension(8,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2349 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxmfb_9 (real(dp), dimension(n1,9) a, n1, real(dp), dimension(9,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 2369 of file mxm_std.F90.
References i.
Referenced by mxmfb().
subroutine mxms (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1161 of file mxm_std.F90.
References i.
subroutine mxmu4 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1184 of file mxm_std.F90.
References i.
subroutine mxmur2 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1229 of file mxm_std.F90.
References i, mxmur2_1(), mxmur2_10(), mxmur2_11(), mxmur2_12(), mxmur2_13(), mxmur2_14(), mxmur2_15(), mxmur2_16(), mxmur2_2(), mxmur2_3(), mxmur2_4(), mxmur2_5(), mxmur2_6(), mxmur2_7(), mxmur2_8(), and mxmur2_9().
subroutine mxmur2_1 (real(dp), dimension(n1,1) a, n1, real(dp), dimension(1,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1290 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_10 (real(dp), dimension(n1,10) a, n1, real(dp), dimension(10,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1434 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_11 (real(dp), dimension(n1,11) a, n1, real(dp), dimension(11,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1455 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_12 (real(dp), dimension(n1,12) a, n1, real(dp), dimension(12,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1477 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_13 (real(dp), dimension(n1,13) a, n1, real(dp), dimension(13,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1500 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_14 (real(dp), dimension(n1,14) a, n1, real(dp), dimension(14,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1524 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_15 (real(dp), dimension(n1,15) a, n1, real(dp), dimension(15,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1549 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_16 (real(dp), dimension(n1,16) a, n1, real(dp), dimension(16,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1575 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_2 (real(dp), dimension(n1,2) a, n1, real(dp), dimension(2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1302 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_3 (real(dp), dimension(n1,3) a, n1, real(dp), dimension(3,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1315 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_4 (real(dp), dimension(n1,4) a, n1, real(dp), dimension(4,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1329 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_5 (real(dp), dimension(n1,5) a, n1, real(dp), dimension(5,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1344 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_6 (real(dp), dimension(n1,6) a, n1, real(dp), dimension(6,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1360 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_7 (real(dp), dimension(n1,7) a, n1, real(dp), dimension(7,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1377 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_8 (real(dp), dimension(n1,8) a, n1, real(dp), dimension(8,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1395 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur2_9 (real(dp), dimension(n1,9) a, n1, real(dp), dimension(9,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1414 of file mxm_std.F90.
References i.
Referenced by mxmur2().
subroutine mxmur3 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,n3) b, n2, real(dp), dimension(n1,n3) c, n3)
Definition at line 1603 of file mxm_std.F90.
References i, mxmur3_1(), mxmur3_10(), mxmur3_11(), mxmur3_12(), mxmur3_13(), mxmur3_14(), mxmur3_15(), mxmur3_16(), mxmur3_2(), mxmur3_3(), mxmur3_4(), mxmur3_5(), mxmur3_6(), mxmur3_7(), mxmur3_8(), and mxmur3_9().
subroutine mxmur3_1 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,1) b, n2, real(dp), dimension(n1,1) c, n3)
Definition at line 2114 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_10 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,10) b, n2, real(dp), dimension(n1,10) c, n3)
Definition at line 1898 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_11 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,11) b, n2, real(dp), dimension(n1,11) c, n3)
Definition at line 1864 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_12 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,12) b, n2, real(dp), dimension(n1,12) c, n3)
Definition at line 1828 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_13 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,13) b, n2, real(dp), dimension(n1,13) c, n3)
Definition at line 1790 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_14 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,14) b, n2, real(dp), dimension(n1,14) c, n3)
Definition at line 1750 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_15 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,15) b, n2, real(dp), dimension(n1,15) c, n3)
Definition at line 1708 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_16 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,16) b, n2, real(dp), dimension(n1,16) c, n3)
Definition at line 1664 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_2 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,2) b, n2, real(dp), dimension(n1,2) c, n3)
Definition at line 2098 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_3 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,3) b, n2, real(dp), dimension(n1,3) c, n3)
Definition at line 2080 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_4 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,4) b, n2, real(dp), dimension(n1,4) c, n3)
Definition at line 2060 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_5 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,5) b, n2, real(dp), dimension(n1,5) c, n3)
Definition at line 2038 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_6 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,6) b, n2, real(dp), dimension(n1,6) c, n3)
Definition at line 2014 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_7 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,7) b, n2, real(dp), dimension(n1,7) c, n3)
Definition at line 1988 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_8 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,8) b, n2, real(dp), dimension(n1,8) c, n3)
Definition at line 1960 of file mxm_std.F90.
References i.
Referenced by mxmur3().
subroutine mxmur3_9 (real(dp), dimension(n1,n2) a, n1, real(dp), dimension(n2,9) b, n2, real(dp), dimension(n1,9) c, n3)
Definition at line 1930 of file mxm_std.F90.
References i.
Referenced by mxmur3().