Nek5000: navier5.F90 File Reference
navier5.F90 File Reference
Functions/Subroutines
subroutine q_filter (wght)
filter vx,vy,vz, and p by simple interpolation
subroutine filterq (v, f, nx, nz, w1, w2, ft, if3d, dmax)
subroutine local_grad3 (ur, us, ut, u, N, e, D, Dt)
Output: ur,us,ut Input:u,N,e,D,Dt.
subroutine gaujordf (a, m, n, indr, indc, ipiv, ierr, rmult)
Gauss-Jordan matrix inversion with full pivoting. Num. Rec. p. 30, 2nd Ed., Fortran a is an m x n matrix rmult is a work array of dimension m.
subroutine legendre_poly (L, x, N)
Evaluate Legendre polynomials of degrees 0-N at point x.
subroutine build_new_filter (intv, zpts, nx, kut, wght, nid)
This routing builds a 1D filter with a transfer function that looks like: ^ d_k | | | 1 |__________ v | -_ | \ wght | \ ___ | | ^ 0 |----------—|—|> 0 c N k–> Where c := N-kut is the point below which d_k = 1. Here, nx = number of points.
real(dp) function ran1 (idum)
subroutine rand_fld_h1 (x)
Function/Subroutine Documentation
subroutine build_new_filter (real(dp), dimension(nx,nx) intv, real(dp), dimension(nx) zpts, integer nx, integer kut, real(dp) wght, integer nid)
This routing builds a 1D filter with a transfer function that looks like: ^ d_k | | | 1 |__________ v | -_ | \ wght | \ ___ | | ^ 0 |----------—|—|> 0 c N k–> Where c := N-kut is the point below which d_k = 1. Here, nx = number of points.
Definition at line 405 of file navier5.F90.
References copy(), exitt(), gaujordf(), ident(), legendre_poly(), mxm(), and transpose().
Referenced by q_filter().
subroutine filterq (real(dp), dimension(nx*nx*nz,nelt) v, real(dp), dimension(nx,nx) f, integer nx, integer nz, real(dp), dimension(*) w1, real(dp), dimension(*) w2, real(dp), dimension(nx,nx) ft, logical if3d, real(dp) dmax)
Todo:
Is this supposed to be nx*ny*nz?
Definition at line 167 of file navier5.F90.
References copy(), mxm(), and transpose().
Referenced by q_filter().
subroutine gaujordf (real(dp), dimension(m,n) a, integer m, integer n, integer, dimension(m) indr, integer, dimension(n) indc, integer, dimension(n) ipiv, integer ierr, real(dp), dimension(m) rmult)
Gauss-Jordan matrix inversion with full pivoting. Num. Rec. p. 30, 2nd Ed., Fortran a is an m x n matrix rmult is a work array of dimension m.
Definition at line 256 of file navier5.F90.
References exitt().
Referenced by build_new_filter().
subroutine legendre_poly (real(dp), dimension(0:n) L, real(dp) x, integer N)
Evaluate Legendre polynomials of degrees 0-N at point x.
Definition at line 373 of file navier5.F90.
Referenced by build_new_filter().
subroutine local_grad3 (real(dp), dimension(0:n,0:n,0:n) ur, real(dp), dimension(0:n,0:n,0:n) us, real(dp), dimension(0:n,0:n,0:n) ut, real(dp), dimension (0:n,0:n,0:n,*) u, integer N, integer e, real(dp), dimension (0:n,0:n) D, real(dp), dimension(0:n,0:n) Dt)
Output: ur,us,ut Input:u,N,e,D,Dt.
Definition at line 230 of file navier5.F90.
References mxm().
Referenced by convect_new(), and wgradm1().
subroutine q_filter (real(dp) wght)
filter vx,vy,vz, and p by simple interpolation
Definition at line 3 of file navier5.F90.
References build_new_filter(), filterq(), ident(), speclib::igllm(), speclib::iglm(), mxm(), speclib::zwgl(), and speclib::zwgll().
Referenced by nek_advance().
real(dp) function ran1 (integer idum)
Definition at line 471 of file navier5.F90.
subroutine rand_fld_h1 (real(dp), dimension(*) x)
Definition at line 510 of file navier5.F90.
References dsavg().
Referenced by startx1().