Nek5000: jl/obbox.h File Reference
obbox.h File Reference
Classes
struct dbl_range
struct obbox_2
struct obbox_3
Macros
#define obbox_calc_2 PREFIXED_NAME(obbox_calc_2)
#define obbox_calc_3 PREFIXED_NAME(obbox_calc_3)
Functions
void obbox_calc_2 (struct obbox_2 *out, const double *const elx[2], const unsigned n[2], uint nel, const unsigned m[2], const double tol)
void obbox_calc_3 (struct obbox_3 *out, const double *const elx[3], const unsigned n[3], uint nel, const unsigned m[3], const double tol)
static double obbox_axis_test_2 (const struct obbox_2 *const b, const double x[2])
static double obbox_test_2 (const struct obbox_2 *const b, const double x[2])
static double obbox_axis_test_3 (const struct obbox_3 *const b, const double x[3])
static double obbox_test_3 (const struct obbox_3 *const b, const double x[3])
Macro Definition Documentation
#define obbox_calc_2 PREFIXED_NAME(obbox_calc_2)
Definition at line 8 of file obbox.h.
#define obbox_calc_3 PREFIXED_NAME(obbox_calc_3)
Definition at line 9 of file obbox.h.
Function Documentation
static double obbox_axis_test_2 (const struct obbox_2 *const b, const double x[2]) static
Definition at line 69 of file obbox.h.
References dbl_range::max, dbl_range::min, and obbox_2::x.
Referenced by obbox_test_2().
static double obbox_axis_test_3 (const struct obbox_3 *const b, const double x[3]) static
Definition at line 90 of file obbox.h.
References dbl_range::max, dbl_range::min, and obbox_3::x.
Referenced by obbox_test_3().
void obbox_calc_2 (struct obbox_2 * out, const double *const elx[2], const unsigned n[2], uint nel, const unsigned m[2], const double tol)
Definition at line 127 of file obbox.c.
References obbox_2::A, obbox_2::c0, dbl_range_expand(), DO_EDGE, DO_MAX, GET_EDGE, gll_lag_size, lob_bnd_size(), mat_inv_2(), dbl_range::max, dbl_range::min, mr, nr, ns, out, SETUP_DIR, tensor_ig2(), tmalloc, work, and obbox_2::x.
void obbox_calc_3 (struct obbox_3 * out, const double *const elx[3], const unsigned n[3], uint nel, const unsigned m[3], const double tol)
Definition at line 225 of file obbox.c.
References obbox_3::A, obbox_3::c0, dbl_range_expand(), DO_FACE, DO_MAX, EVAL_AT_0, GET_FACE, gll_lag_size, lob_bnd_size(), mat_inv_3(), dbl_range::max, dbl_range::min, mr, nr, ns, out, SETUP_DIR, tmalloc, work, obbox_3::x, and z.
static double obbox_test_2 (const struct obbox_2 *const b, const double x[2]) static
Definition at line 77 of file obbox.h.
References obbox_2::A, obbox_2::c0, and obbox_axis_test_2().
static double obbox_test_3 (const struct obbox_3 *const b, const double x[3]) static
Definition at line 99 of file obbox.h.
References obbox_3::A, obbox_3::c0, and obbox_axis_test_3().