Nek5000: jl/poly.h File Reference
poly.h File Reference
Macros
#define lagrange_size PREFIXED_NAME(lagrange_size)
#define lagrange_setup PREFIXED_NAME(lagrange_setup)
#define gauss_nodes PREFIXED_NAME(gauss_nodes)
#define gauss_quad PREFIXED_NAME(gauss_quad)
#define lobatto_nodes PREFIXED_NAME(lobatto_nodes)
#define lobatto_quad PREFIXED_NAME(lobatto_quad)
#define gll_lag_size PREFIXED_NAME(gll_lag_size)
#define gll_lag_setup PREFIXED_NAME(gll_lag_setup)
Typedefs
typedef void lagrange_fun(double *restrict p, double *restrict data, unsigned n, int d, double x)
Functions
void gauss_nodes (double *restrict z, int n)
void lobatto_nodes (double *restrict z, int n)
void gauss_quad (double *restrict z, double *restrict w, int n)
void lobatto_quad (double *restrict z, double *restrict w, int n)
unsigned lagrange_size (unsigned n)
lagrange_fun * lagrange_setup (double *restrict data, const double *restrict z, unsigned n)
unsigned gll_lag_size (unsigned n)
lagrange_fun * gll_lag_setup (double *restrict data, int n)
Macro Definition Documentation
#define gauss_nodes PREFIXED_NAME(gauss_nodes)
Definition at line 10 of file poly.h.
#define gauss_quad PREFIXED_NAME(gauss_quad)
Definition at line 11 of file poly.h.
#define gll_lag_setup PREFIXED_NAME(gll_lag_setup)
Definition at line 15 of file poly.h.
#define gll_lag_size PREFIXED_NAME(gll_lag_size)
Definition at line 14 of file poly.h.
#define lagrange_setup PREFIXED_NAME(lagrange_setup)
Definition at line 9 of file poly.h.
#define lagrange_size PREFIXED_NAME(lagrange_size)
Definition at line 8 of file poly.h.
#define lobatto_nodes PREFIXED_NAME(lobatto_nodes)
Definition at line 12 of file poly.h.
#define lobatto_quad PREFIXED_NAME(lobatto_quad)
Definition at line 13 of file poly.h.
Typedef Documentation
typedef void lagrange_fun(double *restrict p, double *restrict data, unsigned n, int d, double x)
Definition at line 53 of file poly.h.
Function Documentation
void gauss_nodes (double *restrict z, int n)
Definition at line 139 of file poly.c.
References EPS, i, legendre(), legendre_d1(), n, PI, and x.
void gauss_quad (double *restrict z, double *restrict w, int n)
Definition at line 195 of file poly.c.
References gauss_nodes, i, legendre(), and n.
lagrange_fun* gll_lag_setup (double *restrict data, int n)
Definition at line 222 of file poly.c.
References GLL_LAG_FIX_MAX, gll_lag_table, lagrange_coef(), lagrange_eval(), lobatto_nodes, n, p, tmalloc, and z.
unsigned gll_lag_size (unsigned n)
Definition at line 217 of file poly.c.
References GLL_LAG_FIX_MAX, and n.
lagrange_fun* lagrange_setup (double *restrict data, const double *restrict z, unsigned n)
Definition at line 64 of file poly.c.
References lagrange_coef(), lagrange_eval(), p, restrict, and tmalloc.
unsigned lagrange_size (unsigned n)
Definition at line 59 of file poly.c.
References n.
void lobatto_nodes (double *restrict z, int n)
Definition at line 189 of file poly.c.
References GLL_LAG_FIX_MAX, lobatto_nodes_fix(), and lobatto_nodes_n().
void lobatto_quad (double *restrict z, double *restrict w, int n)
Definition at line 206 of file poly.c.
References i, legendre(), lobatto_nodes, and n.