Nek5000: jl/tests/rand_elt_test.c File Reference
rand_elt_test.c File Reference
#include <stdlib.h>
#include <math.h>
#include "c99.h"
#include "types.h"
#include "name.h"
#include "poly.h"
#include "lob_bnd.h"
Macros
#define PI 3.1415926535897932384626433832795028841971693993751058209749445923
Functions
static double det_2 (const double A[4])
static double quad_2 (const double x0, const double g[2], const double H[3], const double r[2])
static void quad_2_grad (double grad[2], const double g[2], const double H[3], const double r[2])
static double quad_2_jac (const double g[4], const double H[6], const double r[2])
static double det_3 (const double A[9])
static double quad_3 (const double x0, const double g[3], const double H[6], const double r[3])
static void quad_3_grad (double grad[3], const double g[3], const double H[6], const double r[3])
static double quad_3_jac (const double g[9], const double H[18], const double r[3])
void rand_elt_2 (double *x, double *y, const double *zr, unsigned nr, const double *zs, unsigned ns)
void rand_elt_3 (double *x, double *y, double *z, const double *zr, unsigned nr, const double *zs, unsigned ns, const double *zt, unsigned nt)
void bubble_elt (double *x, double *y, double *z, const double *zr, unsigned nr, const double *zs, unsigned ns, const double *zt, unsigned nt, int type)
Macro Definition Documentation
#define PI 3.1415926535897932384626433832795028841971693993751058209749445923
Definition at line 147 of file rand_elt_test.c.
Referenced by bubble_elt().
Function Documentation
void bubble_elt (double * x, double * y, double * z, const double * zr, unsigned nr, const double * zs, unsigned ns, const double * zt, unsigned nt, int type)
Definition at line 149 of file rand_elt_test.c.
References i, nr, ns, and PI.
Referenced by main().
static double det_2 (const double A[4]) static
Definition at line 9 of file rand_elt_test.c.
Referenced by quad_2_jac().
static double det_3 (const double A[9]) static
Definition at line 35 of file rand_elt_test.c.
Referenced by quad_3_jac().
static double quad_2 (const double x0, const double g[2], const double H[3], const double r[2]) static
Definition at line 11 of file rand_elt_test.c.
Referenced by rand_elt_2().
static void quad_2_grad (double grad[2], const double g[2], const double H[3], const double r[2]) static
Definition at line 19 of file rand_elt_test.c.
Referenced by quad_2_jac().
static double quad_2_jac (const double g[4], const double H[6], const double r[2]) static
Definition at line 26 of file rand_elt_test.c.
References det_2(), and quad_2_grad().
Referenced by rand_elt_2().
static double quad_3 (const double x0, const double g[3], const double H[6], const double r[3]) static
Definition at line 43 of file rand_elt_test.c.
Referenced by rand_elt_3().
static void quad_3_grad (double grad[3], const double g[3], const double H[6], const double r[3]) static
Definition at line 52 of file rand_elt_test.c.
Referenced by quad_3_jac().
static double quad_3_jac (const double g[9], const double H[18], const double r[3]) static
Definition at line 60 of file rand_elt_test.c.
References det_3(), and quad_3_grad().
Referenced by rand_elt_3().
void rand_elt_2 (double * x, double * y, const double * zr, unsigned nr, const double * zs, unsigned ns)
Definition at line 70 of file rand_elt_test.c.
References i, lob_bnd_2, lob_bnd_setup, lobatto_nodes, dbl_range::max, dbl_range::min, nr, ns, quad_2(), quad_2_jac(), and work.
Referenced by main(), and rand_mesh().
void rand_elt_3 (double * x, double * y, double * z, const double * zr, unsigned nr, const double * zs, unsigned ns, const double * zt, unsigned nt)
Definition at line 105 of file rand_elt_test.c.
References i, lob_bnd_3, lob_bnd_setup, lobatto_nodes, dbl_range::max, dbl_range::min, nr, ns, quad_3(), quad_3_jac(), and work.
Referenced by main(), and rand_mesh().