Nek5000: jl/rand_elt_test.h File Reference
rand_elt_test.h File Reference
Functions
void rand_elt_2 (double *x, double *y, const double *zr, unsigned nr, const double *zs, unsigned ns)
void rand_elt_3 (double *x, double *y, double *z, const double *zr, unsigned nr, const double *zs, unsigned ns, const double *zt, unsigned nt)
void bubble_elt (double *x, double *y, double *z, const double *zr, unsigned nr, const double *zs, unsigned ns, const double *zt, unsigned nt, int type)
Function Documentation
void bubble_elt (double * x, double * y, double * z, const double * zr, unsigned nr, const double * zs, unsigned ns, const double * zt, unsigned nt, int type)
Definition at line 149 of file rand_elt_test.c.
References i, nr, ns, and PI.
Referenced by main().
void rand_elt_2 (double * x, double * y, const double * zr, unsigned nr, const double * zs, unsigned ns)
Definition at line 70 of file rand_elt_test.c.
References i, lob_bnd_2, lob_bnd_setup, lobatto_nodes, dbl_range::max, dbl_range::min, nr, ns, quad_2(), quad_2_jac(), and work.
Referenced by main(), and rand_mesh().
void rand_elt_3 (double * x, double * y, double * z, const double * zr, unsigned nr, const double * zs, unsigned ns, const double * zt, unsigned nt)
Definition at line 105 of file rand_elt_test.c.
References i, lob_bnd_3, lob_bnd_setup, lobatto_nodes, dbl_range::max, dbl_range::min, nr, ns, quad_3(), quad_3_jac(), and work.
Referenced by main(), and rand_mesh().