Nek5000: jl/sarray_transfer.h File Reference
sarray_transfer.h File Reference
Macros
#define sarray_transfer_many PREFIXED_NAME(sarray_transfer_many)
#define sarray_transfer_ PREFIXED_NAME(sarray_transfer_)
#define sarray_transfer_ext_ PREFIXED_NAME(sarray_transfer_ext_)
#define sarray_transfer(T, A, proc_field, set_src, cr) sarray_transfer_(A,sizeof(T),offsetof(T,proc_field),set_src,cr)
#define sarray_transfer_ext(T, A, proc, proc_stride, cr) sarray_transfer_ext_(A,sizeof(T),proc,proc_stride,cr)
Functions
uint sarray_transfer_many (struct array *const *const A, const unsigned *const size, const unsigned An, const int fixed, const int ext, const int set_src, const unsigned p_off, const uint *const restrict proc, const unsigned proc_stride, struct crystal *const cr)
void sarray_transfer_ (struct array *const A, const unsigned size, const unsigned p_off, const int set_src, struct crystal *const cr)
void sarray_transfer_ext_ (struct array *const A, const unsigned size, const uint *const proc, const unsigned proc_stride, struct crystal *const cr)
Macro Definition Documentation
#define sarray_transfer (T, A, proc_field, set_src, cr) sarray_transfer_(A,sizeof(T),offsetof(T,proc_field),set_src,cr)
Definition at line 89 of file sarray_transfer.h.
Referenced by findpts(), findpts_eval(), hash_build(), main(), shared_ids(), and test_mesh().
#define sarray_transfer_ PREFIXED_NAME(sarray_transfer_)
Definition at line 74 of file sarray_transfer.h.
#define sarray_transfer_ext (T, A, proc, proc_stride, cr) sarray_transfer_ext_(A,sizeof(T),proc,proc_stride,cr)
Definition at line 92 of file sarray_transfer.h.
Referenced by findpts().
#define sarray_transfer_ext_ PREFIXED_NAME(sarray_transfer_ext_)
Definition at line 75 of file sarray_transfer.h.
#define sarray_transfer_many PREFIXED_NAME(sarray_transfer_many)
Definition at line 73 of file sarray_transfer.h.
Function Documentation
void sarray_transfer_ (struct array *const A, const unsigned size, const unsigned p_off, const int set_src, struct crystal *const cr)
Definition at line 183 of file sarray_transfer.c.
References array::ptr, sarray_transfer_many, and uint.
void sarray_transfer_ext_ (struct array *const A, const unsigned size, const uint *const proc, const unsigned proc_stride, struct crystal *const cr)
Definition at line 191 of file sarray_transfer.c.
References sarray_transfer_many.
uint sarray_transfer_many (struct array *const *const A, const unsigned *const size, const unsigned An, const int fixed, const int ext, const int set_src, const unsigned p_off, const uint *const restrict proc, const unsigned proc_stride, struct crystal *const cr)
Definition at line 137 of file sarray_transfer.c.
References array_reserve_(), cap_rows(), crystal::comm, crystal_router, crystal::data, i, comm::id, dbl_range::max, array::max, n, array::n, num_rows(), pack_ext(), pack_int(), pack_more(), array::ptr, sortp(), uint, unpack_int(), unpack_more(), and crystal::work.