Nek5000: singlmesh.F90 File Reference
singlmesh.F90 File Reference
Functions/Subroutines
subroutine get_session_info (intracomm)
subroutine userchk_set_xfer
Dummy for singlmesh.
subroutine setintercomm (nekcommtrue, nptrue)
Dummy for singlmesh.
subroutine unsetintercomm (nekcommtrue, nptrue)
Dummy for singlmesh.
subroutine uglmin (a, n)
Dummy for singlmesh.
subroutine happy_check (iflag)
Dummy for singlmesh.
Function/Subroutine Documentation
subroutine get_session_info (integer intracomm)
Definition at line 2 of file singlmesh.F90.
References bcast(), blank(), chcopy(), err_chk(), iniproc(), mpi_comm_dup(), mpi_init(), and mpi_initialized().
Referenced by nek_init().
subroutine happy_check (integer iflag)
Dummy for singlmesh.
Definition at line 85 of file singlmesh.F90.
Referenced by exitt().
subroutine setintercomm (integer nekcommtrue, integer nptrue)
Dummy for singlmesh.
Definition at line 61 of file singlmesh.F90.
subroutine uglmin (real(dp) a, integer n)
Dummy for singlmesh.
Definition at line 76 of file singlmesh.F90.
subroutine unsetintercomm (integer nekcommtrue, integer nptrue)
Dummy for singlmesh.
Definition at line 69 of file singlmesh.F90.
subroutine userchk_set_xfer ()
Dummy for singlmesh.
Definition at line 55 of file singlmesh.F90.
Referenced by nek_advance().