Nek5000: jl/sparse_cholesky.c File Reference
sparse_cholesky.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "c99.h"
#include "name.h"
#include "fail.h"
#include "types.h"
#include "mem.h"
#include "sort.h"
Classes
struct sparse_cholesky
Macros
#define sparse_cholesky_factor PREFIXED_NAME(sparse_cholesky_factor)
#define sparse_cholesky_solve PREFIXED_NAME(sparse_cholesky_solve)
#define sparse_cholesky_free PREFIXED_NAME(sparse_cholesky_free)
Functions
static void factor_symbolic (uint n, const uint *Arp, const uint *Aj, struct sparse_cholesky *out, buffer *buf)
static void factor_numeric (uint n, const uint *Arp, const uint *Aj, const double *A, struct sparse_cholesky *out, uint *visit, double *y)
void sparse_cholesky_solve (double *x, const struct sparse_cholesky *fac, double *b)
void sparse_cholesky_factor (uint n, const uint *Arp, const uint *Aj, const double *A, struct sparse_cholesky *out, buffer *buf)
void sparse_cholesky_free (struct sparse_cholesky *fac)
Macro Definition Documentation
#define sparse_cholesky_factor PREFIXED_NAME(sparse_cholesky_factor)
Definition at line 12 of file sparse_cholesky.c.
Referenced by crs_setup(), and main().
#define sparse_cholesky_free PREFIXED_NAME(sparse_cholesky_free)
Definition at line 14 of file sparse_cholesky.c.
Referenced by crs_free(), and main().
#define sparse_cholesky_solve PREFIXED_NAME(sparse_cholesky_solve)
Definition at line 13 of file sparse_cholesky.c.
Referenced by apply_S(), apply_S_col(), crs_solve(), and main().
Function Documentation
static void factor_numeric (uint n, const uint * Arp, const uint * Aj, const double * A, struct sparse_cholesky * out, uint * visit, double * y) static
Definition at line 105 of file sparse_cholesky.c.
References sparse_cholesky::D, D, i, sparse_cholesky::L, sparse_cholesky::Lj, sparse_cholesky::Lrp, n, p, tmalloc, and uint.
Referenced by sparse_cholesky_factor().
static void factor_symbolic (uint n, const uint * Arp, const uint * Aj, struct sparse_cholesky * out, buffer * buf) static
Definition at line 46 of file sparse_cholesky.c.
References i, sparse_cholesky::Lj, sparse_cholesky::Lrp, sparse_cholesky::n, n, nz, p, sortv(), tmalloc, and uint.
Referenced by sparse_cholesky_factor().
void sparse_cholesky_factor (uint n, const uint * Arp, const uint * Aj, const double * A, struct sparse_cholesky * out, buffer * buf)
Definition at line 160 of file sparse_cholesky.c.
References buffer_reserve, factor_numeric(), factor_symbolic(), array::ptr, and uint.
void sparse_cholesky_free (struct sparse_cholesky * fac)
Definition at line 170 of file sparse_cholesky.c.
References sparse_cholesky::D, sparse_cholesky::L, sparse_cholesky::Lj, and sparse_cholesky::Lrp.
void sparse_cholesky_solve (double * x, const struct sparse_cholesky * fac, double * b)
Definition at line 142 of file sparse_cholesky.c.
References sparse_cholesky::D, D, i, sparse_cholesky::L, sparse_cholesky::Lj, sparse_cholesky::Lrp, sparse_cholesky::n, n, p, and uint.