Nek5000: subs1.F90 File Reference
subs1.F90 File Reference
Functions/Subroutines
subroutine setdt
Set the new time step. All cases covered.
subroutine cvgnlps (ifconv)
Check convergence for non-linear passisve scalar solver. Relevant for solving heat transport problems with radiation b.c.
subroutine unorm
Norm calculation.
subroutine setdtc (umax, uxmax)
Compute new timestep based on CFL-condition.
subroutine cumax (v1, v2, v3, u, v, w, umax, uxmax)
compute max(U/dx) and max(U * dx)
subroutine faccl2 (a, b, iface1)
Collocate B with A on the surface IFACE1 of element IE. A is a (NX,NY,NZ) data structure B is a (NX,NY,IFACE) data structure IFACE1 is in the preprocessor notation IFACE is the dssum notation. 5 Jan 1989 15:12:22 PFF.
subroutine faccl3 (a, b, c, iface1)
subroutine sethlm (h1, h2, intloc)
Set the variable property arrays H1 and H2 in the Helmholtz equation. (associated with variable IFIELD) INTLOC = integration type.
subroutine vprops
Set material properties Material type: 0 for default (PARAM and PCOND/PRHOCP) 1 for constant props; 2 for fortran function;.
subroutine setsolv
Set ifsolv = .FALSE.
subroutine flush_io
subroutine facexv (A1, A2, A3, B1, B2, B3, IFACE1, IOP)
subroutine updmsys (IFLD)
subroutine setcdof
Function/Subroutine Documentation
subroutine cumax (real(dp), dimension(lx1,ly1,lz1,lelv), intent(in) v1, real(dp), dimension(lx1,ly1,lz1,lelv), intent(in) v2, real(dp), dimension(lx1,ly1,lz1,lelv), intent(in) v3, real(dp), dimension(lx1,ly1,lz1,lelv), intent(out) u, real(dp), dimension(lx1,ly1,lz1,lelv), intent(out) v, real(dp), dimension(lx1,ly1,lz1,lelv), intent(out) w, real(dp), intent(out) umax, real(dp), intent(out) uxmax)
compute max(U/dx) and max(U * dx)
Todo:
This routine is sloppy, could reuse state from elsewhere
Definition at line 405 of file subs1.F90.
References xyzrst().
Referenced by setdtc().
subroutine cvgnlps (logical ifconv)
Check convergence for non-linear passisve scalar solver. Relevant for solving heat transport problems with radiation b.c.
Definition at line 135 of file subs1.F90.
References unorm().
Referenced by cdscal().
subroutine faccl2 (real(dp), dimension(lx1,ly1,lz1) a, real(dp), dimension(lx1,ly1) b, integer iface1)
Collocate B with A on the surface IFACE1 of element IE. A is a (NX,NY,NZ) data structure B is a (NX,NY,IFACE) data structure IFACE1 is in the preprocessor notation IFACE is the dssum notation. 5 Jan 1989 15:12:22 PFF.
Definition at line 604 of file subs1.F90.
References dsset().
Referenced by crespsp().
subroutine faccl3 (real(dp), dimension(lx1,ly1,lz1) a, real(dp), dimension(lx1,ly1,lz1) b, real(dp), dimension(lx1,ly1) c, integer iface1)
Definition at line 641 of file subs1.F90.
References dsset().
Referenced by crespsp().
subroutine facexv (real(dp), dimension(lx1,ly1) A1, real(dp), dimension(lx1,ly1) A2, real(dp), dimension(lx1,ly1) A3, real(dp), dimension(lx1,ly1,lz1) B1, real(dp), dimension(lx1,ly1,lz1) B2, real(dp), dimension(lx1,ly1,lz1) B3, integer IFACE1, integer IOP)
Definition at line 903 of file subs1.F90.
References dsset().
Referenced by area3().
subroutine flush_io ()
Definition at line 890 of file subs1.F90.
Referenced by exitt(), and exitt0().
subroutine setcdof ()
Definition at line 979 of file subs1.F90.
Referenced by setup_topo().
subroutine setdt ()
Set the new time step. All cases covered.
Definition at line 3 of file subs1.F90.
References compute_cfl(), and setdtc().
Referenced by settime().
subroutine setdtc (real(dp), intent(out) umax, real(dp), intent(out) uxmax)
Compute new timestep based on CFL-condition.
Definition at line 207 of file subs1.F90.
References bcdirvc(), cumax(), makeuf(), opdssum(), and setprop().
Referenced by setdt().
subroutine sethlm (real(dp), dimension(lx1,ly1,lz1,lelt) h1, real(dp), dimension(lx1,ly1,lz1,lelt) h2, integer intloc)
Set the variable property arrays H1 and H2 in the Helmholtz equation. (associated with variable IFIELD) INTLOC = integration type.
Definition at line 694 of file subs1.F90.
References copy().
Referenced by cdscal(), cresvsp(), and eigenv().
subroutine setsolv ()
Set ifsolv = .FALSE.
Definition at line 881 of file subs1.F90.
Referenced by nek_advance().
subroutine unorm ()
Norm calculation.
Definition at line 163 of file subs1.F90.
References normsc(), and normvc().
Referenced by cvgnlps(), fluid(), and heat().
subroutine updmsys (integer, intent(in) IFLD)
Definition at line 962 of file subs1.F90.
Referenced by geom_reset().
subroutine vprops ()
Set material properties Material type: 0 for default (PARAM and PCOND/PRHOCP) 1 for constant props; 2 for fortran function;.
Definition at line 750 of file subs1.F90.
References exitt().
Referenced by setprop().