Nek5000: jl/tensor.h File Reference
tensor.h File Reference
Macros
#define tensor_dot PREFIXED_NAME(tensor_dot)
#define tensor_mtxm PREFIXED_NAME(tensor_mtxm)
#define nek_mxm FORTRAN_UNPREFIXED(mxm,MXM)
Functions
double tensor_dot (const double *a, const double *b, uint n)
void tensor_mtxm (double *C, uint nc, const double *A, uint na, const double *B, uint nb)
void nek_mxm (const double *A, const uint *na, const double *B, const uint *nb, double *C, const uint *nc)
static void tensor_mxm (double *C, uint nc, const double *A, uint na, const double *B, uint nb)
static void tensor_mxv (double *y, uint ny, const double *A, const double *x, uint nx)
static void tensor_mtxv (double *y, uint ny, const double *A, const double *x, uint nx)
static double tensor_i1 (const double *Jr, uint nr, const double *u)
static double tensor_i2 (const double *Jr, uint nr, const double *Js, uint ns, const double *u, double *work)
static double tensor_i3 (const double *Jr, uint nr, const double *Js, uint ns, const double *Jt, uint nt, const double *u, double *work)
static double tensor_ig1 (double g[1], const double *wtr, uint nr, const double *u)
static double tensor_ig2 (double g[2], const double *wtr, uint nr, const double *wts, uint ns, const double *u, double *work)
static double tensor_ig3 (double g[3], const double *wtr, uint nr, const double *wts, uint ns, const double *wtt, uint nt, const double *u, double *work)
static void tensor_2t (double *out, const double *Jrt, uint nr, uint mr, const double *Jst, uint ns, uint ms, const double *u, double *work)
static void tensor_3t (double *out, const double *Jrt, uint nr, uint mr, const double *Jst, uint ns, uint ms, const double *Jtt, uint nt, uint mt, const double *u, double *work)
Macro Definition Documentation
#define nek_mxm FORTRAN_UNPREFIXED(mxm,MXM)
Definition at line 47 of file tensor.h.
Referenced by tensor_mtxv(), tensor_mxm(), and tensor_mxv().
#define tensor_dot PREFIXED_NAME(tensor_dot)
Definition at line 26 of file tensor.h.
Referenced by tensor_i1(), tensor_i2(), tensor_i3(), tensor_ig1(), tensor_ig2(), and tensor_ig3().
#define tensor_mtxm PREFIXED_NAME(tensor_mtxm)
Definition at line 27 of file tensor.h.
Referenced by tensor_2t(), and tensor_3t().
Function Documentation
void nek_mxm (const double * A, const uint * na, const double * B, const uint * nb, double * C, const uint * nc)
static void tensor_2t (double * out, const double * Jrt, uint nr, uint mr, const double * Jst, uint ns, uint ms, const double * u, double * work) static
Definition at line 168 of file tensor.h.
References tensor_mtxm, and tensor_mxm().
Referenced by main().
static void tensor_3t (double * out, const double * Jrt, uint nr, uint mr, const double * Jst, uint ns, uint ms, const double * Jtt, uint nt, uint mt, const double * u, double * work) static
Definition at line 183 of file tensor.h.
References ns, p, tensor_mtxm, tensor_mxm(), and uint.
Referenced by main().
double tensor_dot (const double * a, const double * b, uint n)
Definition at line 12 of file tensor.c.
References n, and sum().
static double tensor_i1 (const double * Jr, uint nr, const double * u) static
Definition at line 81 of file tensor.h.
References tensor_dot.
Referenced by findpt_area(), and findpts_el_eval_2().
static double tensor_i2 (const double * Jr, uint nr, const double * Js, uint ns, const double * u, double * work) static
Definition at line 87 of file tensor.h.
References tensor_dot, and tensor_mtxv().
Referenced by findpt_vol(), findpts_el_eval_3(), and main().
static double tensor_i3 (const double * Jr, uint nr, const double * Js, uint ns, const double * Jt, uint nt, const double * u, double * work) static
Definition at line 96 of file tensor.h.
References tensor_dot, and tensor_mtxv().
Referenced by main().
static double tensor_ig1 (double g[1], const double * wtr, uint nr, const double * u) static
Definition at line 124 of file tensor.h.
References tensor_dot.
Referenced by findpt_area().
static double tensor_ig2 (double g[2], const double * wtr, uint nr, const double * wts, uint ns, const double * u, double * work) static
Definition at line 133 of file tensor.h.
References tensor_dot, and tensor_mxm().
Referenced by findpt_vol(), and obbox_calc_2().
static double tensor_ig3 (double g[3], const double * wtr, uint nr, const double * wts, uint ns, const double * wtt, uint nt, const double * u, double * work) static
Definition at line 145 of file tensor.h.
References nr, ns, tensor_dot, tensor_mxm(), tensor_mxv(), uint, and work.
void tensor_mtxm (double * C, uint nc, const double * A, uint na, const double * B, uint nb)
static void tensor_mtxv (double * y, uint ny, const double * A, const double * x, uint nx) static
Definition at line 63 of file tensor.h.
References nek_mxm, and uint.
Referenced by compute_pt_data(), findpt_edge(), tensor_i2(), and tensor_i3().
static void tensor_mxm (double * C, uint nc, const double * A, uint na, const double * B, uint nb) static
Definition at line 53 of file tensor.h.
References nek_mxm.
Referenced by compute_edge_data(), compute_edge_data_r(), compute_face_data_rs(), compute_face_data_tr(), compute_pt_data(), findpt_area(), findpt_face(), findpt_vol(), findpts_el_eval_2(), findpts_el_eval_3(), tensor_2t(), tensor_3t(), tensor_ig2(), and tensor_ig3().
static void tensor_mxv (double * y, uint ny, const double * A, const double * x, uint nx) static
Definition at line 58 of file tensor.h.
References nek_mxm, and uint.
Referenced by tensor_ig3().