Nek5000: jl/tests/xxt_test.m File Reference
xxt_test.m File Reference
Functions
*Als eye (ns)]
norm (M-em *[inv(All) 0 *Als;0 *Als'Qs *inv(Qs'*dS *Qs)*Qs']*em')
X (:, i)
pause end norm (M-em *[inv(All) 0 *Als;0 *Als'Qs *X *X'*Qs']*em') norm(M-em *[inv(All) 0 *Als
*Als dX *Qf *Qf *dX *em X inv (chol(A)) Ai
Ai ([6 1 7 1 7 2 8],[6 3 1 7 5 2 8 4])'Ai([6 3 7 5]
Variables
function xxt_test Al0 =[8 -1
Ac0 =[-2 -2 -2
As0 =[4 -1 0
Al1 =[4]
Ac1 =[-1 -1 -2]
As1 =[4 -2 -1
Al2 =[4]
Ac2 =[-1 -2 -1]
As2 =[4 -1 -2
A0 =[Al0 Ac0
A1 =[Al1 Ac1
A2 =[Al2 Ac2
Il =eye(4)
Is =eye(4)
gI =eye(8)
Rl0 =Il([1 2],:)
Rl1 =Il([3],:)
Rl2 =Il([4],:)
Rs0 =Is([6 7 8]-4,:)
Rs1 =Is([5 6 7]-4,:)
Rs2 =Is([5 7 8]-4,:)
Zls0 = zeros(length(Rl0(:,1)),length(Rs0(1,:)))
Zls1 = zeros(length(Rl1(:,1)),length(Rs1(1,:)))
Zls2 = zeros(length(Rl2(:,1)),length(Rs2(1,:)))
Zsl0 = zeros(length(Rs0(:,1)),length(Rl0(1,:)))
Zsl1 = zeros(length(Rs1(:,1)),length(Rl1(1,:)))
Zsl2 = zeros(length(Rs2(:,1)),length(Rl2(1,:)))
R0 =[Rl0 Zls0
R1 =[Rl1 Zls1
R2 =[Rl2 Zls2
A =R0'*A0*R0+R1'*A1*R1+R2'*A2*R2
All = bdiag(Al0,Al1,Al2)
Als = bdiag(Ac0,Ac1,Ac2)
Ass = bdiag(As0,As1,As2)
Qs = [Rs0
ns = length(Qs(:,1))
Q = bdiag(eye(4),Qs,[])
M = Q*(A\Q')
S0 = As0-Ac0'*(Al0\Ac0)
S1 = As1-Ac1'*(Al1\Ac1)
S2 = As2-Ac2'*(Al2\Ac2)
dS = bdiag(S0,S1,S2)
em =[eye(4) -All\Als
Rf0 =Is([6 7 8]-4,:)
Rf1 =Is([5 6 7 8]-4,:)
Rf2 =Is([5 6 7 8]-4,:)
Qf = [Rf0
X0 = zeros(length(Rs0(:,1)),length(Rf0(:,1)))
X1 = zeros(length(Rs1(:,1)),length(Rf1(:,1)))
X2 = zeros(length(Rs2(:,1)),length(Rf2(:,1)))
dX = bdiag(X0,X1,X2)
X = Qs'*dX*Qf
n = length(Qs(1,:))
for i
Ri = Is([1:i-1],:)
se
Function Documentation
Ai ()
* Als eye (ns)
* Als dX* Qf* Qf* dX* em X inv (chol(A))
norm (M-em **em' [inv(All) 0 *Als;0 *Als'Qs *inv(Qs'*dS *Qs)*Qs'])
pause end norm (M-em **em' [inv(All) 0 *Als;0 *Als'Qs *X *X'*Qs'])
X (: , i)
Variable Documentation
A =R0'*A0*R0+R1'*A1*R1+R2'*A2*R2
Definition at line 37 of file xxt_test.m.
A0 =[Al0 Ac0
Definition at line 15 of file xxt_test.m.
A1 =[Al1 Ac1
Definition at line 16 of file xxt_test.m.
A2 =[Al2 Ac2
Definition at line 17 of file xxt_test.m.
Ac0 =[-2 -2 -2
Definition at line 4 of file xxt_test.m.
Ac1 =[-1 -1 -2]
Definition at line 8 of file xxt_test.m.
Ac2 =[-1 -2 -1]
Definition at line 12 of file xxt_test.m.
function xxt_test Al0 =[8 -1
Definition at line 3 of file xxt_test.m.
Al1 =[4]
Definition at line 7 of file xxt_test.m.
Al2 =[4]
Definition at line 11 of file xxt_test.m.
All = bdiag(Al0,Al1,Al2)
Definition at line 39 of file xxt_test.m.
Als = bdiag(Ac0,Ac1,Ac2)
Definition at line 40 of file xxt_test.m.
Ac0 As0 =[4 -1 0
Definition at line 5 of file xxt_test.m.
Ac1 As1 =[4 -2 -1
Definition at line 9 of file xxt_test.m.
Ac2 As2 =[4 -1 -2
Definition at line 13 of file xxt_test.m.
Ass = bdiag(As0,As1,As2)
Definition at line 41 of file xxt_test.m.
Referenced by apply_S(), and apply_S_col().
dS = bdiag(S0,S1,S2)
Definition at line 55 of file xxt_test.m.
dX = bdiag(X0,X1,X2)
Definition at line 68 of file xxt_test.m.
em =[eye(4) -All\Als
Definition at line 57 of file xxt_test.m.
gI =eye(8)
Definition at line 20 of file xxt_test.m.
for i
Initial value:
= [1:n]
  ei = Is(:,i)
Definition at line 74 of file xxt_test.m.
Referenced by allocate_X(), apply_m_Asl(), apply_p_Als(), apply_QQt(), apply_S(), apply_S_col(), apply_X(), apply_Xt(), axhelm(), bbox_2_tfm(), bbox_3_tfm(), bubble_elt(), byte_open(), comm_init(), compute_edge_data(), compute_face_data_st(), compute_face_data_tr(), compute_pt_data(), condense_matrix(), cr_setup_aux(), crs_setup(), crs_solve(), discover_dofs(), discover_sep_sizes(), dry_run_time(), factor_numeric(), factor_symbolic(), fgs_fields(), find_perm_x2c(), findpt_area(), findpt_edge(), findpt_face(), findpt_pt(), findpt_vol(), findpts(), findpts_el_2(), findpts_el_3(), findpts_el_eval_2(), findpts_el_eval_3(), findpts_el_setup_2(), findpts_el_setup_3(), findpts_local(), findpts_local_eval(), gauss_nodes(), gauss_quad(), geom2(), gs_gather_vec_to_many(), gs_scatter_many_to_vec(), gs_scatter_vec(), gs_scatter_vec_to_many(), hash_build(), hash_count(), hash_index_aux(), heap_sortv(), init_sep_ids(), initab(), lagrange_coef(), lagrange_eval(), legendre(), legendre_d1(), legendre_d2(), lob_bnd_ext(), lob_bnd_fst(), lob_bnd_lin_2(), lob_bnd_lin_3(), lob_bnd_setup(), lobatto_nodes_aux(), lobatto_nodes_fix(), lobatto_quad(), madd(), main(), make_topology_unique(), merge_copy_perm(), mxf1(), mxf10(), mxf11(), mxf12(), mxf13(), mxf14(), mxf15(), mxf16(), mxf17(), mxf18(), mxf19(), mxf2(), mxf20(), mxf21(), mxf22(), mxf23(), mxf24(), mxf3(), mxf4(), mxf5(), mxf6(), mxf7(), mxf8(), mxf9(), mxm44_0(), mxm44_0_t(), mxm44_2(), mxm44_2_t(), mxmf3_1(), mxmf3_10(), mxmf3_11(), mxmf3_12(), mxmf3_13(), mxmf3_14(), mxmf3_15(), mxmf3_16(), mxmf3_17(), mxmf3_18(), mxmf3_19(), mxmf3_2(), mxmf3_20(), mxmf3_21(), mxmf3_22(), mxmf3_23(), mxmf3_24(), mxmf3_3(), mxmf3_4(), mxmf3_5(), mxmf3_6(), mxmf3_7(), mxmf3_8(), mxmf3_9(), mxmfb_1(), mxmfb_10(), mxmfb_11(), mxmfb_12(), mxmfb_13(), mxmfb_14(), mxmfb_15(), mxmfb_16(), mxmfb_17(), mxmfb_18(), mxmfb_19(), mxmfb_2(), mxmfb_20(), mxmfb_21(), mxmfb_22(), mxmfb_23(), mxmfb_24(), mxmfb_3(), mxmfb_4(), mxmfb_5(), mxmfb_6(), mxmfb_7(), mxmfb_8(), mxmfb_9(), mxms(), mxmu4(), mxmur2(), mxmur2_1(), mxmur2_10(), mxmur2_11(), mxmur2_12(), mxmur2_13(), mxmur2_14(), mxmur2_15(), mxmur2_16(), mxmur2_2(), mxmur2_3(), mxmur2_4(), mxmur2_5(), mxmur2_6(), mxmur2_7(), mxmur2_8(), mxmur2_9(), mxmur3(), mxmur3_1(), mxmur3_10(), mxmur3_11(), mxmur3_12(), mxmur3_13(), mxmur3_14(), mxmur3_15(), mxmur3_16(), mxmur3_2(), mxmur3_3(), mxmur3_4(), mxmur3_5(), mxmur3_6(), mxmur3_7(), mxmur3_8(), mxmur3_9(), nek_comm_getstat(), newton_face(), nonzero_ids(), orthogonalize(), outfld(), print_ptdata(), pw_map_setup(), radix_passp0_b(), radix_passp0_be(), radix_sortp(), rand_elt_2(), rand_elt_3(), rand_mesh(), ref_gauss_nodes(), ref_gauss_weights(), ref_lagrange_0(), ref_lagrange_1(), ref_lagrange_2(), ref_lagrange_2u(), ref_lagrange_setup(), ref_lobatto_weights(), sarray_perm_invert(), sarray_permute_(), sarray_transfer_many(), seed(), separate_matrix(), shared_ids_aux(), sparse_cholesky_solve(), table_from_hash(), tensor_mtxm(), test(), test_mesh(), unique_ids(), vdiagnostic(), and wgradm1().
Il =eye(4)
Definition at line 19 of file xxt_test.m.
Is =eye(4)
Definition at line 19 of file xxt_test.m.
M = Q*(A\Q')
Definition at line 49 of file xxt_test.m.
n = length(Qs(1,:))
Definition at line 73 of file xxt_test.m.
Referenced by allreduce_imp(), apply_QQt(), apply_X(), array_cat_(), bbox_2_tfm(), bbox_3_tfm(), byte_reverse(), byte_reverse8(), cap_rows(), compute_edge_data(), copy_strided(), count_bits(), cr_learn(), cr_schedule(), crl_bi_to_si(), crl_ri_to_bi(), crystal_move(), crystal_router(), discover_dofs(), discover_sep_sizes(), factor_numeric(), factor_symbolic(), fcrystal_ituple_transfer(), fcrystal_tuple_transfer(), ffindpts_setup(), findpt_edge(), findpts(), findpts_el_3(), findpts_el_setup_2(), findpts_el_setup_3(), findpts_eval(), findpts_local_setup(), findpts_setup(), gauss_nodes(), gauss_quad(), gll_lag_setup(), gll_lag_size(), hash_index(), hash_setfac(), heap_sortv(), init_sep_ids(), initab(), speclib::jacobf(), lagrange_coef(), lagrange_eval(), lagrange_size(), legendre(), legendre_d1(), legendre_d2(), lob_bnd_1(), lob_bnd_ext(), lob_bnd_fst(), lob_bnd_lin_1(), lob_bnd_setup(), lobatto_nodes_aux(), lobatto_quad(), locate_proc(), main(), mpi_reduce_double_precision(), mpi_reduce_integer(), mpi_reduce_integer8(), mpi_reduce_real(), mxm44_0(), mxm44_0_t(), mxm44_2(), mxm44_2_t(), nonzero_ids(), num_rows(), pw_comm_setup(), radix_passp0_b(), radix_passp0_be(), radix_passp_b(), radix_passp_be(), radix_sortp(), ref_gauss_nodes(), ref_gauss_weights(), ref_lagrange_0(), ref_lagrange_1(), ref_lagrange_2(), ref_lagrange_2u(), ref_lagrange_setup(), ref_lobatto_weights(), sarray_perm_invert(), sarray_permute_(), sarray_transfer_many(), scan_imp(), separate_matrix(), setup_aux(), sparse_cholesky_solve(), sum(), table_from_hash(), tensor_dot(), unique_ids(), vdiagnostic(), and work_size().
ns = length(Qs(:,1))
Definition at line 43 of file xxt_test.m.
Referenced by apply_m_Asl(), apply_p_Als(), apply_S(), apply_X(), bubble_elt(), compute_edge_data(), compute_edge_data_r(), compute_edge_data_s(), compute_face_data_rs(), compute_face_data_st(), compute_face_data_tr(), compute_pt_data(), discover_dofs(), discover_sep_ids(), discover_sep_sizes(), ffindpts_setup(), findpt_area(), findpt_vol(), findpts_el_eval_2(), findpts_el_eval_3(), findpts_el_setup_2(), findpts_el_setup_3(), init_sep_ids(), lob_bnd_2(), lob_bnd_3(), lob_bnd_lin_2(), lob_bnd_lin_3(), merge_sep_ids(), obbox_calc_2(), obbox_calc_3(), orthogonalize(), rand_elt_2(), rand_elt_3(), seed(), tensor_3t(), tensor_ig3(), and work_size().
Q = bdiag(eye(4),Qs,[])
Definition at line 45 of file xxt_test.m.
Qf = [Rf0
Definition at line 63 of file xxt_test.m.
Qs *Als Qs *Ass * Qs = [Rs0
Definition at line 42 of file xxt_test.m.
Referenced by lob_bnd_lin_2(), and lob_bnd_lin_3().
R0 =[Rl0 Zls0
Definition at line 33 of file xxt_test.m.
R1 =[Rl1 Zls1
Definition at line 34 of file xxt_test.m.
R2 =[Rl2 Zls2
Definition at line 35 of file xxt_test.m.
Rf0 =Is([6 7 8]-4,:)
Definition at line 60 of file xxt_test.m.
Rf1 =Is([5 6 7 8]-4,:)
Definition at line 61 of file xxt_test.m.
Rf2 =Is([5 6 7 8]-4,:)
Definition at line 62 of file xxt_test.m.
Ri = Is([1:i-1],:)
Definition at line 76 of file xxt_test.m.
Rl0 =Il([1 2],:)
Definition at line 21 of file xxt_test.m.
Rl1 =Il([3],:)
Definition at line 22 of file xxt_test.m.
Rl2 =Il([4],:)
Definition at line 23 of file xxt_test.m.
Zsl0 Rs0 =Is([6 7 8]-4,:)
Definition at line 24 of file xxt_test.m.
Zsl1 Rs1 =Is([5 6 7]-4,:)
Definition at line 25 of file xxt_test.m.
Zsl2 Rs2 =Is([5 7 8]-4,:)
Definition at line 26 of file xxt_test.m.
S0 = As0-Ac0'*(Al0\Ac0)
Definition at line 51 of file xxt_test.m.
S1 = As1-Ac1'*(Al1\Ac1)
Definition at line 52 of file xxt_test.m.
S2 = As2-Ac2'*(Al2\Ac2)
Definition at line 53 of file xxt_test.m.
se
Initial value:
= dS*Qs*ei
  Xtse = dX'*se
  QQtXtse = Qf*Ri'*Ri*Qf'*Xtse
  Qy = Qs*ei - dX*QQtXtse
  ytsy = Qy'*dS*Qy
  Qx = Qy/sqrt(ytsy)
  xv = inv(Qs'*Qs)*Qs'*Qx
Definition at line 77 of file xxt_test.m.
Referenced by crl_work_init(), edge_index(), pw_comm_setup(), and pw_map_setup().
X = Qs'*dX*Qf
Definition at line 69 of file xxt_test.m.
Referenced by apply_X(), and apply_Xt().
X0 = zeros(length(Rs0(:,1)),length(Rf0(:,1)))
Definition at line 65 of file xxt_test.m.
X1 = zeros(length(Rs1(:,1)),length(Rf1(:,1)))
Definition at line 66 of file xxt_test.m.
X2 = zeros(length(Rs2(:,1)),length(Rf2(:,1)))
Definition at line 67 of file xxt_test.m.
Zls0 = zeros(length(Rl0(:,1)),length(Rs0(1,:)))
Definition at line 27 of file xxt_test.m.
Zls1 = zeros(length(Rl1(:,1)),length(Rs1(1,:)))
Definition at line 28 of file xxt_test.m.
Zls2 = zeros(length(Rl2(:,1)),length(Rs2(1,:)))
Definition at line 29 of file xxt_test.m.
Zsl0 = zeros(length(Rs0(:,1)),length(Rl0(1,:)))
Definition at line 30 of file xxt_test.m.
Zsl1 = zeros(length(Rs1(:,1)),length(Rl1(1,:)))
Definition at line 31 of file xxt_test.m.
Zsl2 = zeros(length(Rs2(:,1)),length(Rl2(1,:)))
Definition at line 32 of file xxt_test.m.